import { revalidatePath } from "next/cache";
import { NextResponse } from "next/server";
import { isAdmin } from "../../../../lib/admin-auth";
import { createStory, deleteStory, listStories, updateStory, type QueueStatus, type QueuedStory } from "../../../../lib/news-queue";
import { recordAudit, recordVersion, visibleAdminStories } from "../../../../lib/admin-recovery";
import { applyContentFlags, duplicateCandidates, isBreaking, isFeatured } from "../../../../lib/admin-content-flags";
import { getGalleryImages, setGalleryImages } from "../../../../lib/story-gallery";
import { publicationQuality } from "../../../../lib/publishing-quality";
import { deadlineChange } from "../../../../lib/deadline-audit";
import { verifyExternalSource } from "../../../../lib/source-verification";
const allowedStatuses:QueueStatus[]=["draft","approved","published","rejected","archived"];
function safeHttpUrl(value:unknown){if(!value)return null;const raw=String(value).trim();if(!raw)return null;try{const url=new URL(raw);return url.protocol==="http:"||url.protocol==="https:"?url.toString():null}catch{return null}}
function valuesFrom(body:Record<string,unknown>){const details=applyContentFlags(String(body.details||"").trim(),body.featured===true,body.breaking===true);return{title:String(body.title||"").trim(),institution:String(body.institution||"To be confirmed").trim(),category:String(body.category||"Admission").trim(),summary:String(body.summary||"").trim(),details,deadline:body.deadline?String(body.deadline).trim():null,deadline_iso:body.deadline_iso?String(body.deadline_iso):null,image_url:body.image_url?String(body.image_url):null,document_url:body.document_url?String(body.document_url):null,document_name:body.document_name?String(body.document_name):null,official_source_name:body.official_source_name?String(body.official_source_name).trim():null,official_source_url:safeHttpUrl(body.official_source_url),status:allowedStatuses.includes(body.status as QueueStatus)?body.status as QueueStatus:"draft" as QueueStatus}}
function validationError(v:ReturnType<typeof valuesFrom>,body:Record<string,unknown>){if(!v.title)return"A title is required.";if(body.official_source_url&&!v.official_source_url)return"Official source link must be a valid http:// or https:// URL.";if(v.deadline_iso&&Number.isNaN(Date.parse(v.deadline_iso)))return"Deadline must contain a valid date.";if((v.status==="approved"||v.status==="published")&&(!v.summary||!v.details))return"Summary and details are required before approving or publishing an update.";return null}
function refreshPublic(id?:string){revalidatePath("/");revalidatePath("/updates");revalidatePath("/admin");revalidatePath("/admin/recovery");revalidatePath("/admin/modules");revalidatePath("/admin/media");if(id)revalidatePath(`/updates/imported/${id}`)}
function publicStory(s:QueuedStory){return{...s,featured:isFeatured(s),breaking:isBreaking(s)}}
function mergeGallery(values:ReturnType<typeof valuesFrom>,body:Record<string,unknown>,previous:QueuedStory){const explicit=Array.isArray(body.gallery_images);const images=explicit?(body.gallery_images as unknown[]).filter((x):x is string=>typeof x==="string"&&/^https?:\/\//.test(x)).slice(0,4):getGalleryImages(previous.details);return{...values,details:setGalleryImages(values.details,images)};}
function qualityError(story:QueuedStory,all:QueuedStory[]){const issues=publicationQuality(story,all);return issues.length?`Publishing quality check failed: ${issues.join(" ")}`:null;}
async function networkQualityError(story:QueuedStory){if((story.status!=="approved"&&story.status!=="published")||!story.official_source_url)return null;const source=await verifyExternalSource(story.official_source_url);return source.ok?null:`Publishing quality check failed: ${source.reason}`;}
export async function GET(){if(!(await isAdmin()))return NextResponse.json({error:"Unauthorized"},{status:401});try{return NextResponse.json({stories:visibleAdminStories(await listStories()).map(publicStory)})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to load stories."},{status:500})}}
export async function POST(request:Request){if(!(await isAdmin()))return NextResponse.json({error:"Unauthorized"},{status:401});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return NextResponse.json({error:"Invalid request."},{status:400});const values=valuesFrom(body),error=validationError(values,body);if(error)return NextResponse.json({error},{status:400});try{const existing=visibleAdminStories(await listStories());const candidate={...values,id:"new",source_name:"S.O.H CONSULTS",source_url:"manual:new",source_published_at:null,created_at:new Date().toISOString(),updated_at:new Date().toISOString()} as QueuedStory;if(values.status==="approved"||values.status==="published"){const quality=qualityError(candidate,existing);if(quality)return NextResponse.json({error:quality},{status:400});const network=await networkQualityError(candidate);if(network)return NextResponse.json({error:network},{status:400});}const dupes=duplicateCandidates(values.title,existing,undefined,values.official_source_url);if(dupes.length&&body.allow_duplicate!==true)return NextResponse.json({error:"Possible duplicate update detected.",duplicates:dupes.map(d=>({id:d.story.id,title:d.story.title,status:d.story.status,same_source:d.sameSource}))},{status:409});const story=await createStory(values);await recordAudit("Created update",story,`Initial status: ${story.status}.`).catch(()=>{});refreshPublic(story.id);return NextResponse.json({story:publicStory(story)},{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to create story."},{status:500})}}
export async function PATCH(request:Request){if(!(await isAdmin()))return NextResponse.json({error:"Unauthorized"},{status:401});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body?.id)return NextResponse.json({error:"Story ID is required."},{status:400});const rawValues=valuesFrom(body);try{const all=visibleAdminStories(await listStories()),previous=all.find((s:QueuedStory)=>s.id===String(body.id));if(!previous)return NextResponse.json({error:"Update not found."},{status:404});const values=mergeGallery(rawValues,body,previous),error=validationError(values,body);if(error)return NextResponse.json({error},{status:400});const candidate={...previous,...values} as QueuedStory;if(values.status==="approved"||values.status==="published"){const quality=qualityError(candidate,all);if(quality)return NextResponse.json({error:quality},{status:400});const network=await networkQualityError(candidate);if(network)return NextResponse.json({error:network},{status:400});}const dupes=duplicateCandidates(values.title,all,previous.id,values.official_source_url);if(dupes.length&&body.allow_duplicate!==true)return NextResponse.json({error:"Possible duplicate update detected.",duplicates:dupes.map(d=>({id:d.story.id,title:d.story.title,status:d.story.status,same_source:d.sameSource}))},{status:409});await recordVersion(previous,"before_edit");const story=await updateStory(String(body.id),values);if(!story)return NextResponse.json({error:"Update not found."},{status:404});const change=deadlineChange(previous,story);if(change)await recordAudit("Deadline changed",story,`Previous: ${change.oldDeadline||"none"}; New: ${change.newDeadline||"none"}; Actor: authenticated shared admin session; Source: ${story.official_source_url||"none"}; Modified: ${new Date().toISOString()}.`).catch(()=>{});const action=previous.status!==story.status?`Status changed ${previous.status} → ${story.status}`:"Edited update";await recordAudit(action,story,`Featured: ${isFeatured(story)?"yes":"no"}; Breaking: ${isBreaking(story)?"yes":"no"}.`).catch(()=>{});refreshPublic(String(body.id));return NextResponse.json({story:publicStory(story)})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to update story."},{status:500})}}
export async function DELETE(request:Request){if(!(await isAdmin()))return NextResponse.json({error:"Unauthorized"},{status:401});const body=await request.json().catch(()=>null) as {id?:string;confirm?:string}|null;if(!body?.id||body.confirm!=="PERMANENTLY DELETE")return NextResponse.json({error:"Permanent deletion requires confirmation."},{status:400});try{const story=visibleAdminStories(await listStories()).find(s=>s.id===body.id);if(story){await recordVersion(story,"before_permanent_delete").catch(()=>{});await recordAudit("Permanently deleted update",story,"Protected confirmation completed.").catch(()=>{})}const deleted=await deleteStory(body.id);if(!deleted)return NextResponse.json({error:"Update not found."},{status:404});refreshPublic(body.id);return NextResponse.json({success:true})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to delete story."},{status:500})}}
