"use client";
import {useMemo,useState} from "react";
import {updates,opportunities,getUpdateSlug} from "../../data/updates";
import {admissionDeadlines} from "../../data/admission-deadlines";
import {guides} from "../../data/guides";
import {unifiedSearch,type DiscoveryItem} from "../../lib/algorithm-phase2";
import SiteContact from "../components/SiteContact";

function corpus():DiscoveryItem[]{
 const updateItems:DiscoveryItem[]=updates.map(u=>({id:`update-${u.id}`,href:`/updates/${getUpdateSlug(u)}`,kind:"update",title:u.title,summary:u.summary,body:u.details,institution:u.institution,category:u.category,publishedAt:u.date,deadline:u.deadlineISO||u.deadline,isOfficial:Boolean(u.source)}));
 const opportunityItems:DiscoveryItem[]=opportunities.map((o,i)=>({id:`opportunity-${i}`,href:"/opportunities",kind:"opportunity",title:`${o.institution} ${o.programme}`,summary:o.description,institution:o.institution,category:o.category,deadline:o.deadline}));
 const deadlineItems:DiscoveryItem[]=admissionDeadlines.map((d,i)=>({id:`deadline-${i}`,href:"/deadlines",kind:"deadline",title:`${d.institution} ${d.programme}`,summary:`Application deadline: ${d.deadline}`,institution:d.institution,category:d.category,deadline:d.deadline}));
 const guideItems:DiscoveryItem[]=guides.map(g=>({id:`guide-${g.slug}`,href:`/guides/${g.slug}`,kind:"guide",title:g.title,summary:g.summary,body:g.sections.map(s=>`${s.heading} ${s.body}`).join(" "),category:g.category,isOfficial:true}));
 return [...updateItems,...opportunityItems,...deadlineItems,...guideItems];
}
export default function SearchPage(){const[q,setQ]=useState("");const results=useMemo(()=>q.trim()?unifiedSearch(corpus(),q).slice(0,30):[],[q]);return <main className="min-h-screen bg-gray-50 text-gray-900"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><a href="/"><img src="/soh-logo.jpg" alt="S.O.H CONSULTS" className="h-14 w-auto"/></a><a href="/" className="font-black text-green-700">Home</a></div></header><section className="bg-gradient-to-br from-green-950 to-green-700 py-14 text-white"><div className="mx-auto max-w-4xl px-5"><p className="font-black uppercase tracking-widest text-green-300">S.O.H CONSULTS</p><h1 className="mt-3 text-4xl font-black">Search Everything</h1><p className="mt-3 text-green-50">Updates, opportunities, deadlines and guides ranked together by relevance, freshness and importance.</p><input autoFocus type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search school, admission, scholarship, JAMB CAPS..." className="mt-7 w-full rounded-2xl border-0 bg-white px-5 py-4 text-gray-900 shadow-lg outline-none ring-green-300 focus:ring-4"/></div></section><section className="py-10"><div className="mx-auto max-w-4xl px-5">{q.trim()&&<p className="mb-5 text-sm font-bold text-gray-500">{results.length} ranked result{results.length===1?"":"s"}</p>}{results.length?<div className="space-y-4">{results.map(({item})=><a key={item.id} href={item.href} className="block rounded-2xl border bg-white p-5 shadow-sm transition hover:border-green-400 hover:shadow-md"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-black uppercase text-green-800">{item.kind}</span>{item.institution&&<span className="text-xs font-bold text-gray-500">{item.institution}</span>}</div><h2 className="mt-3 text-xl font-black">{item.title}</h2>{item.summary&&<p className="mt-2 line-clamp-2 leading-7 text-gray-600">{item.summary}</p>}</a>)}</div>:q.trim()?<div className="rounded-2xl border border-dashed bg-white p-10 text-center"><h2 className="text-xl font-black">No results found</h2><p className="mt-2 text-gray-600">Try the school name, programme, admission type or a shorter phrase.</p></div>:<div className="rounded-2xl bg-white p-8 shadow-sm"><h2 className="font-black">One search across S.O.H CONSULTS</h2><p className="mt-2 text-gray-600">Start typing to search the website&apos;s admission information.</p></div>}</div></section><SiteContact/></main>}
