"use client";
import {useRef} from "react";
type Props={value:string;onChange:(value:string)=>void;disabled:boolean;heading:boolean;label:string};
const actions=[{label:"Bold",before:"**",after:"**",example:"bold text"},{label:"Italic",before:"*",after:"*",example:"italic text"},{label:"Underline",before:"++",after:"++",example:"underlined text"},{label:"Strike",before:"~~",after:"~~",example:"struck text"},{label:"Link",before:"[",after:"](https://example.com)",example:"link text"}] as const;
export default function FormattedTextInput({value,onChange,disabled,heading,label}:Props){
 const ref=useRef<HTMLTextAreaElement>(null);
 function wrap(before:string,after:string,example:string){const area=ref.current;if(!area)return;const start=area.selectionStart,end=area.selectionEnd;const selected=value.slice(start,end)||example;onChange(value.slice(0,start)+before+selected+after+value.slice(end));requestAnimationFrame(()=>{area.focus();area.setSelectionRange(start+before.length,start+before.length+selected.length);});}
 function line(prefix:string){const area=ref.current;if(!area)return;const start=area.selectionStart,end=area.selectionEnd;const lineStart=value.lastIndexOf("\n",start-1)+1;const selection=value.slice(lineStart,end);const replacement=selection.split("\n").map(line=>prefix+line).join("\n");onChange(value.slice(0,lineStart)+replacement+value.slice(end));requestAnimationFrame(()=>area.focus());}
 return <div className="space-y-2"><div role="toolbar" aria-label={`${label} formatting`} className="flex flex-wrap gap-1 rounded-xl border border-gray-200 bg-gray-50 p-2">{actions.map(action=><button key={action.label} type="button" disabled={disabled} onClick={()=>wrap(action.before,action.after,action.example)} className="rounded-lg border bg-white px-3 py-2 text-sm font-bold text-gray-800 disabled:opacity-50" title={`Format selected text: ${action.label}`}>{action.label}</button>)}{!heading&&<><button type="button" disabled={disabled} onClick={()=>line("- ")} className="rounded-lg border bg-white px-3 py-2 text-sm font-bold">• List</button><button type="button" disabled={disabled} onClick={()=>line("1. ")} className="rounded-lg border bg-white px-3 py-2 text-sm font-bold">1. List</button></>}</div><textarea ref={ref} aria-label={label} rows={heading?2:7} value={value} onChange={event=>onChange(event.target.value)} disabled={disabled} className="w-full min-w-0 rounded-xl border border-gray-300 bg-white px-3 py-3 text-base text-gray-950 focus:border-green-700 focus:outline-none focus:ring-2 focus:ring-green-200" placeholder={heading?"Section heading":"Write your paragraph"}/><p className="text-xs text-gray-500">Select text, then use the toolbar. Formatting appears in the published article.</p></div>;
}
