"use client";
import {useEffect,useState} from "react";
type Run={id:string;status:string;at:string;details:string};
export default function ImportHistory(){
 const [runs,setRuns]=useState<Run[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const response=await fetch("/api/admin/import-history",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"History unavailable");setRuns(data.runs||[]);setError("")}catch(e){setError(e instanceof Error?e.message:"History unavailable")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 return <section className="mb-6 rounded-3xl border border-green-200 bg-green-50 p-5" aria-label="Scheduled import history"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase text-green-800">Automatic news monitoring</p><h2 className="text-xl font-black text-gray-950">Scheduled import history</h2><p className="text-sm text-gray-700">Recent persisted cron results. The configured schedule is daily at 06:00 UTC; Vercel may execute later. This is not real-time monitoring.</p></div><button type="button" onClick={()=>void load()} disabled={loading} className="rounded-xl bg-green-800 px-4 py-2 font-bold text-white disabled:opacity-50">{loading?"Loading...":"Refresh history"}</button></div>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}{!loading&&!error&&runs.length===0&&<p className="mt-3 text-sm">No saved scheduled runs found. Check Vercel cron execution and CRON_SECRET if runs are expected.</p>}<div className="mt-4 space-y-2">{runs.map(run=>{let data:Record<string,unknown>={};try{data=JSON.parse(run.details)}catch{data={message:run.details}}const failed=Boolean(data.error)||run.status!=="OK"&&!Array.isArray(data.failures);const partial=!failed&&Array.isArray(data.failures)&&data.failures.length>0;return <article key={run.id} className="rounded-xl border bg-white p-3"><div className="flex flex-wrap justify-between gap-2"><strong className={failed?"text-red-700":partial?"text-amber-700":"text-green-800"}>{failed?"Import failed":partial?"Import completed with source errors":"Import completed"}</strong><time className="text-sm" dateTime={run.at}>{new Date(run.at).toLocaleString()}</time></div><p className="mt-2 text-sm">Discovered: {String(data.discovered??"Unknown")} · New drafts: {String(data.added??"Unknown")} · Old skipped: {String(data.skippedOld??"Unknown")} · Undated: {String(data.skippedUndated??"Unknown")}</p>{Array.isArray(data.failures)&&data.failures.length>0&&<details className="mt-2 text-sm"><summary className="cursor-pointer font-semibold">Source errors ({data.failures.length})</summary><ul className="list-disc pl-5">{data.failures.map((failure,index)=><li key={index}>{String(failure)}</li>)}</ul></details>}{Boolean(data.error)&&<p className="mt-2 break-words text-sm text-red-700">{String(data.error)}</p>}{Boolean(data.message)&&<p className="mt-2 break-words text-sm">{String(data.message)}</p>}</article>})}</div></section>
}
