"use client";
import {useState} from "react";
type Suggestion={source_name:string;source_url:string;title:string;institution:string;category:string;official:boolean};
type Discovery={suggestions:Suggestion[];failures:string[];skippedOld:number;skippedUndated:number};
type ImportResult={discovered:number;added:number;skippedOld:number;skippedUndated:number;failures:string[]};
export default function SourcePreview(){
 const [report,setReport]=useState<Discovery|null>(null);
 const [importResult,setImportResult]=useState<ImportResult|null>(null);
 const [checkedAt,setCheckedAt]=useState<string|null>(null);
 const [importedAt,setImportedAt]=useState<string|null>(null);
 const [busy,setBusy]=useState(false);
 const [message,setMessage]=useState("");
 async function preview(){setBusy(true);setMessage("Checking configured sources. This may take a while...");try{const response=await fetch("/api/admin/import",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Discovery failed.");setReport(data);setCheckedAt(new Date().toLocaleString());setMessage(`${data.suggestions.length} suggestions found. Preview does not save drafts.`)}catch(error){setMessage(error instanceof Error?error.message:"Discovery failed.")}finally{setBusy(false)}}
 async function importAll(){if(!confirm("Run a fresh discovery and create drafts? Review each draft before publishing."))return;setBusy(true);setMessage("Importing drafts...");try{const response=await fetch("/api/admin/import",{method:"POST"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Import failed.");setImportResult(data);setImportedAt(new Date().toLocaleString());setMessage(`${data.added} new drafts saved. Reload the page to see them in the queue.`)}catch(error){setMessage(error instanceof Error?error.message:"Import failed.")}finally{setBusy(false)}}
 const counts=report?Object.entries(report.suggestions.reduce<Record<string,number>>((acc,item)=>{acc[item.source_name]=(acc[item.source_name]||0)+1;return acc},{})).sort((a,b)=>b[1]-a[1]):[];
 return <section className="mb-6 rounded-3xl border border-blue-200 bg-blue-50 p-5" aria-label="News import monitoring"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-blue-700">News source monitoring</p><h2 className="mt-1 text-xl font-black text-gray-950">Live discovery and import diagnostics</h2><p className="mt-1 text-sm text-gray-700">Run a live check to see source results. These timestamps describe checks performed in this browser, not the scheduled cron history. Myschool and MySchoolGist are private discovery references, not official sources.</p></div><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void preview()} className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">{busy?"Checking...":"Preview Sources"}</button><button disabled={busy} onClick={()=>void importAll()} className="rounded-xl bg-green-700 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">Create Drafts</button></div></div>
 {message&&<p role="status" className="mt-4 rounded-xl bg-white p-3 text-sm font-bold text-gray-950">{message}</p>}
 {report&&<div className="mt-4 space-y-3"><p className="text-xs font-semibold text-gray-700">Last manual preview: {checkedAt}</p><div className="grid gap-2 sm:grid-cols-3"><div className="rounded-xl bg-white p-3"><strong className="block text-2xl">{report.suggestions.length}</strong><span className="text-xs">Relevant suggestions</span></div><div className="rounded-xl bg-white p-3"><strong className="block text-2xl">{report.skippedOld} / {report.skippedUndated}</strong><span className="text-xs">Old / undated articles</span></div><div className="rounded-xl bg-white p-3"><strong className="block text-2xl">{report.failures.length}</strong><span className="text-xs">Source and article errors</span></div></div><details className="rounded-xl bg-white p-3" open><summary className="cursor-pointer font-bold">Results by source ({counts.length} with suggestions)</summary><ul className="mt-2 space-y-1 text-sm">{counts.map(([name,count])=><li key={name}>{name}: {count} suggestions</li>)}</ul><p className="mt-2 text-xs text-gray-600">Sources with zero results may have no qualifying recent articles or may have failed. Review errors below.</p></details><details className="rounded-xl bg-white p-3" open={report.failures.length>0}><summary className="cursor-pointer font-bold">Source errors ({report.failures.length})</summary>{report.failures.length?<ul className="mt-2 list-disc space-y-1 pl-5 text-sm">{report.failures.map((error,index)=><li key={index} className="break-words">{error}</li>)}</ul>:<p className="mt-2 text-sm">No fetch or extraction errors reported in this check.</p>}</details><details className="rounded-xl bg-white p-3"><summary className="cursor-pointer font-bold">Discovered articles ({report.suggestions.length})</summary><div className="mt-3 max-h-96 space-y-2 overflow-auto">{report.suggestions.map(item=><article key={item.source_url} className="rounded-lg border p-3"><p className="text-sm font-bold">{item.title}</p><p className="mt-1 text-xs">{item.source_name} · {item.category} · {item.official?"Official":"Discovery reference"}</p><a href={item.source_url} target="_blank" rel="noopener noreferrer" className="mt-1 inline-block break-all text-xs font-semibold text-blue-700 underline">Inspect article</a></article>)}</div></details></div>}
 {importResult&&<div className="mt-4 rounded-xl border border-green-200 bg-white p-4 text-sm"><h3 className="font-black">Last manual import: {importedAt}</h3><p>Discovered: {importResult.discovered} · New drafts: {importResult.added} · Existing/unsaved: {Math.max(0,importResult.discovered-importResult.added)}</p><p>Old skipped: {importResult.skippedOld} · Undated: {importResult.skippedUndated} · Errors: {importResult.failures.length}</p><p className="mt-1 text-xs text-gray-600">Existing/unsaved is a difference, not a verified duplicate count. Import runs a new discovery rather than importing the preview snapshot.</p>{importResult.failures.length>0&&<details className="mt-2"><summary className="cursor-pointer font-bold">Import errors</summary><ul className="mt-2 list-disc pl-5">{importResult.failures.map((error,index)=><li key={index} className="break-words">{error}</li>)}</ul></details>}</div>}
 </section>
}
