import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { isAdmin } from "../../../../lib/admin-auth";
import { createManagedOpportunity,deleteManagedOpportunity,listManagedOpportunities,updateManagedOpportunity } from "../../../../lib/opportunities-store";
const statuses=["OPEN","CLOSING SOON","EXTENDED","CLOSED"];
function values(b:Record<string,unknown>){return{institution:String(b.institution||"").trim(),programme:String(b.programme||"").trim(),category:String(b.category||"Other").trim(),status:statuses.includes(String(b.status))?String(b.status):"OPEN",deadline:String(b.deadline||"Check latest deadline").trim(),description:String(b.description||"").trim(),application_url:b.application_url?String(b.application_url).trim():null}}
function valid(v:ReturnType<typeof values>){if(!v.institution||!v.programme)return"Institution and programme are required.";if(v.application_url){try{const u=new URL(v.application_url);if(!["http:","https:"].includes(u.protocol))return"Application link must be http or https."}catch{return"Application link is invalid."}}return null}
export async function GET(){if(!(await isAdmin()))return NextResponse.json({error:"Unauthorized"},{status:401});try{return NextResponse.json({opportunities:await listManagedOpportunities()})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to load opportunities."},{status:500})}}
export async function POST(r:Request){if(!(await isAdmin()))return NextResponse.json({error:"Unauthorized"},{status:401});const b=await r.json().catch(()=>null) as Record<string,unknown>|null;if(!b)return NextResponse.json({error:"Invalid request."},{status:400});const v=values(b),err=valid(v);if(err)return NextResponse.json({error:err},{status:400});try{const opportunity=await createManagedOpportunity(v);revalidatePath("/opportunities");return NextResponse.json({opportunity},{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to create opportunity."},{status:500})}}
export async function PATCH(r:Request){if(!(await isAdmin()))return NextResponse.json({error:"Unauthorized"},{status:401});const b=await r.json().catch(()=>null) as Record<string,unknown>|null;if(!b?.id)return NextResponse.json({error:"Opportunity ID is required."},{status:400});const v=values(b),err=valid(v);if(err)return NextResponse.json({error:err},{status:400});try{const opportunity=await updateManagedOpportunity(String(b.id),v);revalidatePath("/opportunities");return NextResponse.json({opportunity})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to update opportunity."},{status:500})}}
export async function DELETE(r:Request){if(!(await isAdmin()))return NextResponse.json({error:"Unauthorized"},{status:401});const b=await r.json().catch(()=>null) as {id?:string;confirm?:string}|null;if(!b?.id||b.confirm!=="DELETE OPPORTUNITY")return NextResponse.json({error:"Deletion requires confirmation."},{status:400});try{await deleteManagedOpportunity(b.id);revalidatePath("/opportunities");return NextResponse.json({success:true})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to delete opportunity."},{status:500})}}
