import Link from "next/link";
import {listStories,getStorySlug} from "../../lib/news-queue";
import {publishedOperations,moduleFor,deadlineDate,deadlineState,todayUTC,articleMedia,type OperationsModule} from "../../lib/operations-insights";
import LinkedUpdateActions from "./LinkedUpdateActions";
export default async function PublishedUpdateModuleFeed({module}:{module:OperationsModule}){
 const matches=publishedOperations(await listStories()).filter(s=>moduleFor(s,module));const today=todayUTC();
 const dates=matches.filter(s=>deadlineDate(s)).sort((a,b)=>(deadlineDate(a)||"").localeCompare(deadlineDate(b)||""));
 const month=today.slice(0,7),first=new Date(`${month}-01T00:00:00Z`),offset=first.getUTCDay(),days=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate();
 const status=(s:typeof matches[number])=>deadlineState(s,today);
 return <section className="mb-6 rounded-2xl border border-green-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-green-700">Published Updates · Live module</p><h2 className="mt-1 text-xl font-black">Linked updates ({matches.length})</h2><p className="mt-1 text-sm text-gray-600">One original article per update. Categories are suggested from its category/title; correct mistakes by editing the article category in its main editor. Calendar entries require a verified ISO deadline.</p></div><Link href="/admin/updates" className="rounded-xl bg-green-700 px-4 py-2 text-sm font-black text-white">Manage Updates →</Link></div>
 {module==="forms"&&<div className="mt-4 flex flex-wrap gap-2 text-xs font-bold">{(["Open","Closing soon","Closed","Date unverified"] as const).map(label=><span key={label} className="rounded-full border bg-gray-50 px-3 py-2">{label}: {matches.filter(s=>status(s)===label).length}</span>)}</div>}
 {module==="calendar"&&<div className="mt-5 rounded-xl border p-3"><h3 className="mb-3 font-black">{first.toLocaleString("en-GB",{month:"long",year:"numeric",timeZone:"UTC"})} · Deadline calendar</h3><div className="grid grid-cols-7 gap-1 text-center text-xs">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(day=><span key={day} className="p-2 font-bold">{day}</span>)}{Array.from({length:offset},(_,i)=><span key={`empty-${i}`}/>)}{Array.from({length:days},(_,i)=>{const day=String(i+1).padStart(2,"0"),date=`${month}-${day}`,items=dates.filter(s=>deadlineDate(s)===date);return <div key={day} className={`min-h-16 rounded-lg border p-1 text-left ${items.length?"border-amber-400 bg-amber-50":"bg-gray-50"}`}><span className="font-bold">{i+1}</span>{items.map(s=><a key={s.id} href={`#linked-${s.id}`} className="mt-1 block truncate rounded bg-white p-1 text-[10px] text-green-800" title={s.title}>{s.title}</a>)}</div>;})}</div><p className="mt-3 text-xs text-gray-600">Showing this month. All verified dated deadlines, including other months, appear below.</p></div>}
 {module==="calendar"&&dates.filter(s=>status(s)==="Closing soon").length>0&&<div role="status" className="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm font-bold text-amber-900">Deadline reminder: {dates.filter(s=>status(s)==="Closing soon").length} item(s) close within seven days.</div>}
 {matches.length===0?<p className="mt-5 rounded-xl bg-gray-50 p-4 text-sm text-gray-600">No matching published updates yet.</p>:<div className="mt-5 divide-y rounded-xl border">{matches.map(s=>{const media=articleMedia(s);return <article id={`linked-${s.id}`} key={s.id} className="flex flex-wrap items-start justify-between gap-3 p-4"><div className="min-w-0 flex-1"><p className="text-xs font-bold text-green-700">{s.category||"Uncategorised"} · Published</p><h3 className="mt-1 font-black text-gray-950">{s.title}</h3>{s.summary&&<p className="mt-1 line-clamp-2 text-sm text-gray-600">{s.summary}</p>}{module==="forms"&&<p className="mt-2 text-xs font-bold text-gray-700">{status(s)} · {deadlineDate(s)||s.deadline||"No verified deadline"}</p>}{module==="calendar"&&<p className="mt-2 text-xs font-bold text-gray-700">{status(s)} · {deadlineDate(s)}</p>}{module==="media"&&<div className="mt-3 flex flex-wrap items-start gap-3">{media.images.slice(0,6).map((url,index)=><a key={url} href={url} target="_blank" rel="noopener noreferrer" title="Open image"><img src={url} alt={`Media ${index+1} for ${s.title}`} loading="lazy" className="h-28 w-36 rounded-lg border object-contain"/></a>)}{media.documentUrl&&<a href={media.documentUrl} target="_blank" rel="noopener noreferrer" className="rounded-lg border bg-gray-50 p-3 text-xs font-bold text-green-800">📄 {media.documentName||"View document"} ↗</a>}</div>}</div><div className="flex flex-wrap gap-2"><Link href={`/updates/${getStorySlug(s)}`} className="rounded-lg border px-3 py-2 text-xs font-bold text-green-800">View article</Link><LinkedUpdateActions story={s}/>{module==="media"&&media.images[0]&&<a href={media.images[0]} target="_blank" rel="noopener noreferrer" className="rounded-lg border px-3 py-2 text-xs font-bold">Reuse image URL ↗</a>}</div></article>;})}</div>}</section>;
}
