import {NextRequest,NextResponse} from "next/server";
import {isAdmin} from "../../../../lib/admin-auth";
import {listKnowledgeFacts} from "../../../../lib/ask-soh/knowledge-repository";
const URL=process.env.SUPABASE_URL,KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
function headers(prefer?:string){if(!URL||!KEY)throw new Error("Knowledge store unavailable");return{apikey:KEY,...(KEY.startsWith("eyJ")?{Authorization:`Bearer ${KEY}`}:{}),"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})};}
export async function GET(){if(!(await isAdmin()))return NextResponse.json({error:"Unauthorized"},{status:401});return NextResponse.json({facts:await listKnowledgeFacts()});}
export async function POST(request:NextRequest){if(!(await isAdmin()))return NextResponse.json({error:"Unauthorized"},{status:401});if(!URL||!KEY)return NextResponse.json({error:"Knowledge store unavailable"},{status:503});
 const body=await request.json();const required=["topic","intent","value_text","source_name","source_url"];if(required.some(k=>!String(body[k]||"").trim()))return NextResponse.json({error:"Missing required knowledge fields"},{status:400});
 const row={id:crypto.randomUUID(),institution_key:body.institution_key||null,topic:String(body.topic).trim(),intent:String(body.intent).trim(),value_text:String(body.value_text).trim(),answer_text:body.answer_text?String(body.answer_text).trim():null,answer_mode:body.answer_mode||"short",academic_session:body.academic_session||null,source_name:String(body.source_name).trim(),source_url:String(body.source_url).trim(),evidence_text:body.evidence_text||null,source_authority:Number(body.source_authority||80),status:"draft",review_due_at:body.review_due_at||null,metadata:body.metadata||{}};
 const r=await fetch(`${URL}/rest/v1/ask_soh_facts`,{method:"POST",headers:headers("return=representation"),body:JSON.stringify(row),cache:"no-store"});return NextResponse.json(r.ok?(await r.json())[0]:{error:"Unable to create fact"},{status:r.ok?201:500});}
export async function PATCH(request:NextRequest){if(!(await isAdmin()))return NextResponse.json({error:"Unauthorized"},{status:401});if(!URL||!KEY)return NextResponse.json({error:"Knowledge store unavailable"},{status:503});
 const body=await request.json();if(!body.id)return NextResponse.json({error:"Missing id"},{status:400});
 const before=await fetch(`${URL}/rest/v1/ask_soh_facts?select=*&id=eq.${encodeURIComponent(body.id)}&limit=1`,{headers:headers(),cache:"no-store"}).then(r=>r.ok?r.json():[]);
 if(before[0])await fetch(`${URL}/rest/v1/ask_soh_fact_versions`,{method:"POST",headers:headers(),body:JSON.stringify({fact_id:body.id,snapshot:before[0],change_reason:body.change_reason||"Admin update"}),cache:"no-store"});
 const allowed=["institution_key","topic","intent","value_text","answer_text","answer_mode","academic_session","source_name","source_url","evidence_text","source_authority","status","verified_at","review_due_at","valid_from","valid_until","metadata"];const patch=Object.fromEntries(allowed.filter(k=>body[k]!==undefined).map(k=>[k,body[k]]));patch.updated_at=new Date().toISOString();
 const r=await fetch(`${URL}/rest/v1/ask_soh_facts?id=eq.${encodeURIComponent(body.id)}`,{method:"PATCH",headers:headers("return=representation"),body:JSON.stringify(patch),cache:"no-store"});return NextResponse.json(r.ok?(await r.json())[0]:{error:"Unable to update fact"},{status:r.ok?200:500});}
