import {NextRequest,NextResponse} from "next/server";
import {isAdmin} from "../../../../lib/admin-auth";
import {listKnowledgeFacts} from "../../../../lib/ask-soh/knowledge-repository";
const URL=process.env.SUPABASE_URL,KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
function headers(prefer?:string){if(!URL||!KEY)throw new Error("Knowledge store unavailable");return{apikey:KEY,...(KEY.startsWith("eyJ")?{Authorization:`Bearer ${KEY}`}:{}),"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})};}
export async function GET(){if(!(await isAdmin()))return NextResponse.json({error:"Unauthorized"},{status:401});return NextResponse.json({facts:await listKnowledgeFacts()});}
export async function POST(request:NextRequest){if(!(await isAdmin()))return NextResponse.json({error:"Unauthorized"},{status:401});if(!URL||!KEY)return NextResponse.json({error:"Knowledge store unavailable"},{status:503});
 const body=await request.json();const required=["topic","intent","value_text","source_name","source_url"];if(required.some(k=>!String(body[k]||"").trim()))return NextResponse.json({error:"Missing required knowledge fields"},{status:400});
 try{const u=new globalThis.URL(String(body.source_url));if(!["http:","https:"].includes(u.protocol))throw new Error("bad protocol");}catch{return NextResponse.json({error:"Source URL must be a valid HTTP(S) URL"},{status:400});}
 const institution=body.institution_key?String(body.institution_key).trim():null,session=body.academic_session?String(body.academic_session).trim():null,intent=String(body.intent).trim(),value=String(body.value_text).trim();
 const filters=[`intent=eq.${encodeURIComponent(intent)}`,`value_text=eq.${encodeURIComponent(value)}`,institution?`institution_key=eq.${encodeURIComponent(institution)}`:"institution_key=is.null",session?`academic_session=eq.${encodeURIComponent(session)}`:"academic_session=is.null","status=not.in.(expired,archived)"].join("&");const duplicate=await fetch(`${URL}/rest/v1/ask_soh_facts?select=id&${filters}&limit=1`,{headers:headers(),cache:"no-store"}).then(r=>r.ok?r.json():[]);if(duplicate.length)return NextResponse.json({error:"An active fact with the same institution, intent, session and value already exists"},{status:409});
 const row={id:crypto.randomUUID(),institution_key:institution,topic:String(body.topic).trim(),intent,value_text:value,answer_text:body.answer_text?String(body.answer_text).trim():null,answer_mode:body.answer_mode||"short",academic_session:session,source_name:String(body.source_name).trim(),source_url:String(body.source_url).trim(),evidence_text:body.evidence_text||null,source_authority:Number(body.source_authority||80),status:"draft",review_due_at:body.review_due_at||null,metadata:body.metadata||{}};
 const r=await fetch(`${URL}/rest/v1/ask_soh_facts`,{method:"POST",headers:headers("return=representation"),body:JSON.stringify(row),cache:"no-store"});return NextResponse.json(r.ok?(await r.json())[0]:{error:"Unable to create fact"},{status:r.ok?201:500});}
export async function PATCH(request:NextRequest){if(!(await isAdmin()))return NextResponse.json({error:"Unauthorized"},{status:401});if(!URL||!KEY)return NextResponse.json({error:"Knowledge store unavailable"},{status:503});
 const body=await request.json();if(!body.id)return NextResponse.json({error:"Missing id"},{status:400});
 const before=await fetch(`${URL}/rest/v1/ask_soh_facts?select=*&id=eq.${encodeURIComponent(body.id)}&limit=1`,{headers:headers(),cache:"no-store"}).then(r=>r.ok?r.json():[]);
 if(!before[0])return NextResponse.json({error:"Fact not found"},{status:404});
 const transitions:Record<string,string[]>={draft:["review","archived"],review:["verified","draft","archived"],verified:["published","due_review","archived"],published:["due_review","expired","archived"],due_review:["verified","expired","archived"],expired:["review","archived"],archived:["draft"]};
 if(body.status&&before[0]&&!transitions[before[0].status]?.includes(body.status))return NextResponse.json({error:`Invalid knowledge transition: ${before[0].status} → ${body.status}`},{status:409});
 if(body.status==="verified"||body.status==="published"){body.verified_at=body.verified_at||new Date().toISOString();}
 const allowed=["institution_key","topic","intent","value_text","answer_text","answer_mode","academic_session","source_name","source_url","evidence_text","source_authority","status","verified_at","review_due_at","valid_from","valid_until","metadata","source_published_at","conflicting_evidence"];const patch=Object.fromEntries(allowed.filter(k=>body[k]!==undefined).map(k=>[k,body[k]]));patch.updated_at=new Date().toISOString();
 const r=await fetch(`${URL}/rest/v1/ask_soh_facts?id=eq.${encodeURIComponent(body.id)}&updated_at=eq.${encodeURIComponent(before[0].updated_at)}`,{method:"PATCH",headers:headers("return=representation"),body:JSON.stringify(patch),cache:"no-store"});if(!r.ok)return NextResponse.json({error:"Unable to update fact. Verify official provenance and review date."},{status:400});const rows=await r.json();return rows.length?NextResponse.json(rows[0]):NextResponse.json({error:"Fact changed during editing; reload before saving"},{status:409});}
