const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(path,imports={},extra={}){const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module:m,exports:m.exports,require:n=>imports[n]||require(n),URL,URLSearchParams,Date,crypto:require('node:crypto').webcrypto,process:{env:{SUPABASE_URL:'https://qa.example',SUPABASE_SERVICE_ROLE_KEY:'fixture',CRON_SECRET:'cron-fixture'}},...extra});return m.exports;}
const story={id:'fixture',title:'Latest edited title',details:'Latest article with attachment',summary:'Latest summary',category:'Admission',institution:'QA',status:'draft',source_name:'S.O.H CONSULTS',updated_at:'2026-10-03T12:00:00.000Z',document_url:'https://qa.example/file.pdf',document_name:'PDF'};
function storiesRoute({authorized=true,race=false}={}){const writes=[];const prefix='../../../../lib/';const imports={'next/cache':{revalidatePath(){}},'next/server':{NextResponse:{json:(body,opts={})=>({body,status:opts.status||200})}}};imports[prefix+'admin-auth']={isAdmin:async()=>authorized};imports[prefix+'news-queue']={listStories:async()=>[story],updateStory:async(id,values,expected)=>{writes.push({id,values,expected});return race?null:{...story,...values}}};imports[prefix+'admin-recovery']={visibleAdminStories:s=>s,recordVersion:async()=>{},recordAudit:async()=>{}};imports[prefix+'admin-content-flags']={applyContentFlags:s=>s,duplicateCandidates:()=>[],isBreaking:()=>false,isFeatured:()=>false};imports[prefix+'story-gallery']={getGalleryImages:()=>[],setGalleryImages:s=>s};imports[prefix+'publishing-quality']={publicationQuality:()=>[]};imports[prefix+'deadline-audit']={deadlineChange:()=>null};imports[prefix+'source-verification']={verifyExternalSource:async()=>({ok:true})};imports[prefix+'auto-summary']={resolveArticleSummary:s=>s};imports[prefix+'article-blocks']={readArticleBlocks:()=>[],articleBlocksError:()=>null};return{api:load('app/api/admin/stories/route.ts',imports),writes};}
const req=body=>({json:async()=>body});
test('status action preserves latest content and attachments instead of using stale browser fields',async()=>{const{api,writes}=storiesRoute();const result=await api.PATCH(req({id:story.id,action:'status',status:'archived',expected_updated_at:story.updated_at,title:'STALE',details:'STALE',document_url:null}));assert.equal(result.status,200);assert.equal(writes[0].values.title,story.title);assert.equal(writes[0].values.details,story.details);assert.equal(writes[0].values.document_url,story.document_url);assert.equal(writes[0].expected.updated_at,story.updated_at);});
test('stale status action fails before writing',async()=>{const{api,writes}=storiesRoute();const result=await api.PATCH(req({id:story.id,action:'status',status:'archived',expected_updated_at:'older'}));assert.equal(result.status,409);assert.equal(writes.length,0);});
test('concurrent edit after initial read returns conflict',async()=>{const{api}=storiesRoute({race:true});const result=await api.PATCH(req({id:story.id,action:'status',status:'archived',expected_updated_at:story.updated_at}));assert.equal(result.status,409);});
test('unauthenticated status changes cannot write',async()=>{const{api,writes}=storiesRoute({authorized:false});assert.equal((await api.PATCH(req({id:story.id,action:'status',status:'archived'}))).status,401);assert.equal(writes.length,0);});
test('storage compare-and-swap includes source and update timestamp; race performs no attachment cleanup',async()=>{let patch;let deletes=0;const api=load('lib/news-queue.ts',{'../data/updates':{updates:[],getUpdateImage(){},getUpdateSlug(){}}},{fetch:async(url,opts)=>{if(opts.method==='DELETE'){deletes++;return new Response(null,{status:200});}if(opts.method==='PATCH'){patch={url,opts};return Response.json([]);}return Response.json([story]);}});assert.equal(await api.updateStory(story.id,{status:'archived'},story),undefined);const url=new URL(patch.url);assert.equal(url.searchParams.get('source_name'),'eq.'+story.source_name);assert.equal(url.searchParams.get('updated_at'),'eq.'+story.updated_at);assert.equal(deletes,0);});
test('manual content backup includes opportunity records and requires authentication',async()=>{let include;const records=[story,{...story,id:'opportunity',source_name:'S.O.H Opportunity:fixture'}];const imports={'next/server':{NextResponse:{json:(body,opts={})=>({body,status:opts.status||200})}},'../../../../lib/admin-auth':{isAdmin:async()=>true},'../../../../lib/news-queue':{listStories:async flag=>{include=flag;return flag?records:[story];}}};const api=load('app/api/admin/backup/route.ts',imports,{Response});const response=await api.GET({url:'https://qa.example/api/admin/backup'});assert.equal(include,true);assert.equal((await response.json()).records.length,2);imports['../../../../lib/admin-auth'].isAdmin=async()=>false;assert.equal((await api.GET({url:'https://qa.example/api/admin/backup'})).status,401);});
test('daily snapshots retain opportunity records and omit system records',async()=>{let row,include;const records=[story,{...story,id:'opportunity',source_name:'S.O.H Opportunity:fixture'},{...story,id:'system',source_name:'S.O.H System:audit:fixture'}];const api=load('app/api/cron/backup-updates/route.ts',{'next/server':{NextResponse:{json:(body,opts={})=>({body,status:opts.status||200})}},'../../../../lib/news-queue':{listStories:async flag=>{include=flag;return records;}},'../../../../lib/admin-recovery':{isSystemStory:s=>s.source_name.startsWith('S.O.H System:')}},{fetch:async(url,opts)=>{if(opts.method==='POST'){row=JSON.parse(opts.body);return new Response(null,{status:201});}return Response.json([]);}});const result=await api.GET({headers:{get:()=> 'Bearer cron-fixture'}});assert.equal(result.status,200);assert.equal(include,true);assert.equal(JSON.parse(row.details).records.length,2);});
