require('../scripts/ask-soh-test-loader.cjs');
const test=require('node:test'),assert=require('node:assert/strict');
const {verifyAnswer,parseCalendarDate,rankDocuments}=require('../lib/ask-soh/answer-verification.ts');
const {resolveQuestion}=require('../lib/ask-soh/question-resolver.ts');
const q=resolveQuestion('LASU 2026/2027 screening deadline');
const doc=(text,extra={})=>({title:'LASU 2026/2027 Post-UTME screening',url:'https://lasu.edu.ng/notice',snippet:text,official:true,verified:true,kind:'article',fetchedAt:new Date().toISOString(),publishedAt:'2026-07-01T00:00:00Z',...extra});
for(const [raw,expected] of [['15 October 2026','2026-10-15'],['15/10/2026','2026-10-15'],['August 9, 2026','2026-08-09'],['2026-10-15','2026-10-15'],['31 February 2026',null]])test('calendar '+raw,()=>assert.equal(parseCalendarDate(raw),expected));
for(const label of ['Closing date:','Registration closes on','Registration deadline is','Deadline for application:'])test(label,()=>assert.equal(verifyAnswer('LASU 2026/2027 Post-UTME screening deadline',q,[doc('2026/2027 screening. '+label+' 15 October 2026.')]).confidence,'high'));
test('extension marker dates extracted',()=>assert.match(verifyAnswer('LASU 2026/2027 Post-UTME screening deadline',q,[doc('2026/2027 screening registration extended to 15 October 2026.')]).answer,/15 October/));
test('newer dated extension supersedes original',()=>{const result=verifyAnswer('LASU 2026/2027 Post-UTME screening deadline',q,[doc('2026/2027 screening. Closing date: 12 July 2026.'),doc('2026/2027 screening. Registration extended to 9 August 2026.',{url:'https://lasu.edu.ng/extension',publishedAt:'2026-07-10T00:00:00Z'})]);assert.equal(result.confidence,'high');assert.match(result.answer,/9 August/);});
for(const [label,docs] of [
 ['undated extension',[doc('2026/2027 screening. Closing date: 12 July 2026.'),doc('2026/2027 screening. Registration extended to 9 August 2026.',{publishedAt:null,url:'https://lasu.edu.ng/extension'})]],
 ['competing notices',[doc('2026/2027 screening. Closing date: 12 July 2026.'),doc('2026/2027 screening. Closing date: 9 August 2026.',{url:'https://lasu.edu.ng/other'})]]
])test(label,()=>{const r=verifyAnswer('LASU 2026/2027 Post-UTME screening deadline',q,docs);assert.equal(r.contradiction,true);assert.equal(r.needsHuman,true);assert.equal(r.confidence,'low');});
for(const [label,extra,text] of [
 ['wrong session',{},'2025/2026 screening. Closing date: 15 October 2026.'],
 ['mixed sessions',{},'2026/2027 screening. Closing date: 15 October 2026. 2025/2026 admissions.'],
 ['homepage',{kind:'homepage'},'2026/2027 screening. Closing date: 15 October 2026.'],
 ['search snippet',{verified:false,kind:'search'},'2026/2027 screening. Closing date: 15 October 2026.'],
 ['lookalike domain',{url:'https://lasu.edu.ng.evil.test/notice'},'2026/2027 screening. Closing date: 15 October 2026.'],
 ['old fetch',{fetchedAt:'2020-01-01T00:00:00Z'},'2026/2027 screening. Closing date: 15 October 2026.'],
 ['portal action',{kind:'portal'},'2026/2027 screening. Start Screening.']
])test('refuses '+label,()=>{const r=verifyAnswer('LASU 2026/2027 Post-UTME screening deadline',q,[doc(text,extra)]);assert.equal(r.confidence,'low');assert.equal(r.needsHuman,true);});
test('missing session asks clarification',()=>assert.match(verifyAnswer('',resolveQuestion('LASU screening deadline'),[doc('2026/2027 screening. Closing date: 15 October 2026.')]).answer,/academic session/));
test('publication date missing is never high',()=>assert.equal(verifyAnswer('LASU 2026/2027 Post-UTME screening deadline',q,[doc('2026/2027 screening. Closing date: 15 October 2026.',{publishedAt:null})]).confidence,'medium'));
test('cutoff conflict cannot select first score',()=>{const c=resolveQuestion('LASU 2026/2027 minimum JAMB score');const r=verifyAnswer('',c,[doc('2026/2027 Minimum UTME score of 195.'),doc('2026/2027 Minimum UTME score of 200.',{url:'https://lasu.edu.ng/other'})]);assert.equal(r.contradiction,true);});
test('rank article above homepage',()=>assert.equal(rankDocuments([doc('2026/2027 screening',{kind:'homepage',url:'https://lasu.edu.ng/'}),doc('2026/2027 screening')],'screening',q)[0].kind,'article'));
test('generic deadline cannot silently select inter-university transfer',()=>{const query='LASU 2026/2027 registration deadline';const r=verifyAnswer(query,resolveQuestion(query),[doc('2026/2027 Transfer application. Closing date: 31 August 2026.',{title:'Inter-university transfer 2026/2027'})]);assert.equal(r.confidence,'low');assert.match(r.answer,/application type/);});
test('Post-UTME deadline excludes transfer and JUPEB notices',()=>{const query='LASU 2026/2027 Post-UTME screening deadline';const r=verifyAnswer(query,resolveQuestion(query),[doc('2026/2027 transfer applicants. Closing date: 31 August 2026. Post-UTME documents are required.',{title:'Transfer application 2026/2027'}),doc('2026/2027 screening. Closing date: 15 October 2026.')]);assert.equal(r.confidence,'high');assert.match(r.answer,/15 October/);});
for(const text of ['Submission of forms closes at 12.00 Noon on Thursday, 17th September, 2026.','The portal will close at 11:59 p.m. on Friday, 31st July, 2026.','To end at 12:00 midnight on Sunday, 11th October 2026.'])test('time-prefixed deadline '+text,()=>assert.equal(verifyAnswer('LASU 2026/2027 Post-UTME screening deadline',q,[doc('2026/2027 admission screening. '+text)]).confidence,'high'));
test('later reopening without exact closing date blocks obsolete high confidence',()=>{const r=verifyAnswer('LASU 2026/2027 Post-UTME screening deadline',q,[doc('2026/2027 admission screening. Closing date: 31 July 2026.'),doc('2026/2027 admission screening portal reopened for two weeks.',{title:'Post-UTME portal reopening',url:'https://lasu.edu.ng/reopened',publishedAt:'2026-08-11T00:00:00Z'})]);assert.equal(r.confidence,'low');assert.match(r.answer,/reopening/);});
test('Direct Entry-only extension cannot answer UTME question',()=>{const r=verifyAnswer('LASU 2026/2027 Post-UTME screening deadline',q,[doc('2026/2027 admission screening. Closing date: 14 July 2026.'),doc('2026/2027 admission screening. To end at 12:00 midnight on Sunday, 11th October 2026.',{title:'Extension of online admission screening for Direct Entry candidates',url:'https://lasu.edu.ng/de',publishedAt:'2026-10-09T00:00:00Z'})]);assert.match(r.answer,/14 July/);});
test('portal categories do not leak DE deadline to UTME',()=>{const d=doc('2026/2027 admission screening portal.',{kind:'portal',portalDeclarations:[{category:'utme',status:'closed'},{category:'direct-entry',status:'open',deadline:'2026-10-10'}],publishedAt:null});const r=verifyAnswer('LASU 2026/2027 Post-UTME screening deadline',q,[d]);assert.equal(r.confidence,'low');const query='LASU 2026/2027 Direct Entry screening deadline';assert.match(verifyAnswer(query,resolveQuestion(query),[d]).answer,/10 October/);});
test('explicit portal status answers without guessing from accessibility',()=>{const query='LASU 2026/2027 Post-UTME screening still open';const r=verifyAnswer(query,resolveQuestion(query),[doc('2026/2027 admission screening portal.',{kind:'portal',portalDeclarations:[{category:'utme',status:'closed'}]})]);assert.equal(r.confidence,'medium');assert.match(r.answer,/UTME as closed/);});
test('annual exam year is distinct from academic session',()=>{const query='NECO 2026 SSCE external normal registration deadline';const r=verifyAnswer(query,resolveQuestion(query),[doc('2026 SSCE External. Normal registration period ends on 26th October, 2026. Late registration ends on 30 October 2026.',{title:'2026 SSCE External registration guideline',url:'https://neco.gov.ng/guideline.pdf',kind:'pdf'})]);assert.equal(resolveQuestion(query).academicYear,'2026');assert.equal(r.confidence,'high');assert.match(r.answer,/26 October/);});
test('wrong exam year and SSCE category rejected',()=>{const query='NECO 2026 SSCE external registration deadline';for(const title of ['2025 SSCE External registration guidelines','2026 SSCE Internal registration guidelines'])assert.equal(verifyAnswer(query,resolveQuestion(query),[doc('2026 SSCE. Closing date: 25 May 2026.',{title,url:'https://neco.gov.ng/guideline.pdf',kind:'pdf'})]).confidence,'low');});
test('explicit reopened duration endpoint is parsed without calculating relative weeks',()=>{const query='LASU 2026/2027 Post-UTME screening deadline';const r=verifyAnswer(query,resolveQuestion(query),[doc('2026/2027 admission screening. Please note that approved duration for re-opening of the University Portal for sales of Post UTME Form is Wednesday, 12th through Tuesday, 25th August, 2026.',{title:'Re-open Post-UTME portal'})]);assert.match(r.answer,/25 August 2026/);});
test('SSCE external question cannot receive BECE deadline',()=>{const query='NECO 2026 SSCE external normal registration deadline';const r=verifyAnswer(query,resolveQuestion(query),[doc('2026 Basic Education Certificate Examination. Normal registration ends on 25 May 2026.',{title:'2026 BECE guidelines',url:'https://neco.gov.ng/bece.pdf',kind:'pdf'})]);assert.equal(r.confidence,'low');});
test('exam deadline year must match request even when page footer mentions current year',()=>{const query='NECO 2026 SSCE external registration deadline';const r=verifyAnswer(query,resolveQuestion(query),[doc('2025 SSCE External. Closing date: 26 October 2025. Copyright 2026.',{title:'SSCE External registration',url:'https://neco.gov.ng/external',kind:'portal'})]);assert.equal(r.confidence,'low');});
