const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(path,imports={},extra={}){const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module:m,exports:m.exports,require:name=>imports[name]||require(name),URL,File,Buffer,Uint8Array,Set,AbortController,setTimeout,clearTimeout,process:{env:{SUPABASE_URL:'https://qafixture.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'fixture-server-secret'}},...extra});return m.exports;}
const validation=load('lib/article-uploads.ts');
function server(fetch){return load('lib/direct-article-upload.ts',{'./article-uploads':validation},{fetch});}
const input={kind:'video',type:'video/mp4',size:12*1024*1024,name:'test.mp4'};
const mp4=Buffer.concat([Buffer.from([0,0,0,24]),Buffer.from('ftypisom'),Buffer.alloc(4),Buffer.from('mp42')]);
function fixture({size=input.size,type=input.type,prefix=mp4}={}){const calls=[];const api=server(async(url,options)=>{calls.push({url,options});if(url.includes('/object/upload/sign/'))return Response.json({url:'/object/upload/sign/news-attachments/videos/test.mp4?token=fixture-upload-token'});if(options.method==='HEAD')return new Response(null,{headers:{'content-length':String(size),'content-type':type}});return new Response(prefix,{status:206,headers:{'content-range':`bytes 0-${prefix.length-1}/${size}`}});});return {api,calls};}
test('direct upload signs a unique path and exposes only a path-scoped storage token',async()=>{const {api,calls}=fixture();const r=await api.prepareArticleUpload(input);assert.equal(r.endpoint,'https://qafixture.storage.supabase.co/storage/v1/upload/resumable');assert.equal(r.bucket,'news-attachments');assert.match(r.path,/^videos\/[a-f0-9-]{36}\.mp4$/);assert.equal(r.token,'fixture-upload-token');assert.doesNotMatch(JSON.stringify(r),/fixture-server-secret/);assert.equal(calls[0].options.headers['x-upsert'],'false');assert.equal(calls[0].options.body,'{}');assert.equal(calls[0].options.headers.apikey,'fixture-server-secret');});
test('limits accept larger videos while rejecting unsupported kinds/types and oversized PDFs',async()=>{assert.equal(validation.articleUploadMetadataError(50*1024*1024,'video/mp4','video'),null);assert.ok(validation.articleUploadMetadataError(50*1024*1024+1,'video/mp4','video'));assert.ok(validation.articleUploadMetadataError(11*1024*1024,'application/pdf','document'));assert.ok(validation.articleUploadMetadataError(10,'text/html','document'));assert.ok(validation.articleUploadMetadataError(10,'video/mp4','__proto__'));const {api,calls}=fixture();await assert.rejects(api.prepareArticleUpload({...input,size:51*1024*1024}));assert.equal(calls.length,0);});
test('completion authenticates the receipt, checks actual size/type and reads only the file signature',async()=>{const {api,calls}=fixture();const target=await api.prepareArticleUpload(input);const r=await api.completeArticleUpload(target.receipt);assert.equal(r.url,`https://qafixture.supabase.co/storage/v1/object/public/news-attachments/${target.path}`);assert.equal(r.name,input.name);assert.equal(calls[1].options.method,'HEAD');assert.equal(calls[2].options.headers.Range,'bytes=0-63');const before=calls.length;await assert.rejects(api.completeArticleUpload(target.receipt.slice(0,-5)+'abcde'),/Invalid upload receipt/);assert.equal(calls.length,before);await assert.rejects(api.completeArticleUpload('https://attacker.invalid/path'),/Invalid upload receipt/);});
test('completion rejects storage mismatches and spoofed content',async()=>{for(const options of [{size:12},{type:'text/html'},{prefix:Buffer.from('<html>spoofed video</html>')}]){const {api}=fixture(options);const target=await api.prepareArticleUpload(input);await assert.rejects(api.completeArticleUpload(target.receipt),/does not match|signature is invalid/);}});
test('expired receipts fail without storage access',async()=>{let now=Date.now();class Clock extends Date{static now(){return now;}}let calls=0;const api=load('lib/direct-article-upload.ts',{'./article-uploads':validation},{Date:Clock,fetch:async()=>{calls++;return Response.json({url:'/object/upload/sign/news-attachments/file?token=fixture'});}});const target=await api.prepareArticleUpload(input);now+=2*60*60*1000+1;await assert.rejects(api.completeArticleUpload(target.receipt),/expired/);assert.equal(calls,1);});
test('browser sends only metadata/receipt through Vercel and transfers files through resumable storage',async()=>{const file=new File([mp4,Buffer.alloc(8*1024*1024)],'large.mp4',{type:'video/mp4'});let tusOptions;let transferred;const calls=[];class Upload{constructor(body,options){transferred=body;tusOptions=options;}start(){tusOptions.onProgress(file.size,file.size);tusOptions.onSuccess();}}const client=load('lib/article-upload-client.ts',{'./article-uploads':validation,'tus-js-client':{Upload}},{fetch:async(url,options)=>{calls.push({url,options});if(JSON.parse(options.body).action==='prepare')return Response.json({endpoint:'https://qafixture.storage.supabase.co/storage/v1/upload/resumable',token:'path-token',bucket:'news-attachments',path:'videos/random.mp4',receipt:'receipt'});return Response.json({url:'https://qafixture.supabase.co/storage/v1/object/public/news-attachments/videos/random.mp4',name:file.name});}});const progress=[];const r=await client.uploadArticleFile(file,'video',p=>progress.push(p));assert.equal(transferred,file);assert.equal(calls.length,2);for(const call of calls){assert.equal(call.url,'/api/admin/uploads');assert.ok(call.options.body.length<1000);assert.equal(typeof call.options.body,'string');}assert.equal(tusOptions.chunkSize,6*1024*1024);assert.equal(tusOptions.headers['x-signature'],'path-token');assert.equal(tusOptions.headers['x-upsert'],'false');assert.equal(tusOptions.metadata.objectName,'videos/random.mp4');assert.ok(tusOptions.retryDelays.length>1);assert.equal(progress[0],99);assert.equal(progress[1],100);assert.match(r.url,/videos\/random.mp4$/);});
test('browser does not return an attachment URL when final server verification fails',async()=>{class Upload{constructor(body,options){this.options=options;}start(){this.options.onSuccess();}}const client=load('lib/article-upload-client.ts',{'./article-uploads':validation,'tus-js-client':{Upload}},{fetch:async(url,options)=>JSON.parse(options.body).action==='prepare'?Response.json({endpoint:'https://qafixture.supabase.co',token:'token',receipt:'receipt'}):Response.json({error:'Verification failed'},{status:400})});await assert.rejects(client.uploadArticleFile(new File([mp4],'clip.mp4',{type:'video/mp4'}),'video'),/Verification failed/);});
test('admin CSP permits only configured project and its direct storage origin',()=>{const {storageConnectSources}=load('lib/storage-origin.ts');assert.equal(storageConnectSources('https://qafixture.supabase.co/path'),'https://qafixture.supabase.co https://qafixture.storage.supabase.co');for(const value of ['javascript:alert(1)','https://user:secret@example.com','http://example.com','invalid'])assert.equal(storageConnectSources(value),'');assert.equal(storageConnectSources('https://custom.example.com'),'https://custom.example.com');});
test('real TUS client transfers an 8 MB file in storage chunks and recovers an interrupted chunk',async()=>{const http=require('node:http'),{once}=require('node:events'),{Upload:RealUpload}=require('tus-js-client');let stored=0,failed=false;const requests=[];const storage=http.createServer(async(req,res)=>{let bytes=0;for await(const chunk of req)bytes+=chunk.length;requests.push({method:req.method,bytes,token:req.headers['x-signature']});res.setHeader('Tus-Resumable','1.0.0');if(req.method==='HEAD'){res.setHeader('Upload-Offset',stored);res.setHeader('Upload-Length',8*1024*1024+mp4.length);res.writeHead(200).end();return;}if(req.method==='PATCH'&&!failed){failed=true;res.writeHead(503).end();return;}if(req.method==='PATCH')assert.equal(Number(req.headers['upload-offset']),stored);stored+=bytes;res.setHeader('Upload-Offset',stored);if(req.method==='POST'){res.setHeader('Location','/upload/fixture');res.writeHead(201).end();}else res.writeHead(204).end();});storage.listen(0,'127.0.0.1');await once(storage,'listening');try{const endpoint=`http://127.0.0.1:${storage.address().port}/upload/resumable`;const file=new File([mp4,Buffer.alloc(8*1024*1024)],'large.mp4',{type:'video/mp4'});class Upload{constructor(body,options){this.body=body;this.options=options;}start(){this.body.arrayBuffer().then(bytes=>{new RealUpload(Buffer.from(bytes),this.options).start();});}}const client=load('lib/article-upload-client.ts',{'./article-uploads':validation,'tus-js-client':{Upload}},{fetch:async(url,options)=>JSON.parse(options.body).action==='prepare'?Response.json({endpoint,token:'path-token',bucket:'news-attachments',path:'videos/fixture.mp4',receipt:'fixture'}):Response.json({url:'https://qafixture.supabase.co/storage/v1/object/public/news-attachments/videos/fixture.mp4',name:file.name})});const r=await client.uploadArticleFile(file,'video');assert.equal(stored,file.size);assert.ok(failed);assert.ok(requests.some(r=>r.method==='HEAD'));assert.ok(requests.some(r=>r.bytes>4.5*1024*1024));assert.ok(requests.every(r=>r.token==='path-token'));assert.match(r.url,/fixture.mp4$/);}finally{storage.closeAllConnections();await new Promise(resolve=>storage.close(resolve));}});
test('prepare and completion routes require admin authentication and reject invalid metadata before signing',async()=>{let prepares=0,completes=0;const NextResponse={json:(body,options={})=>({body,status:options.status||200,headers:options.headers})};function route(authorized){return load('app/api/admin/uploads/route.ts',{'next/server':{NextResponse},'../../../../lib/admin-auth':{isAdmin:async()=>authorized},'../../../../lib/news-queue':{},'../../../../lib/article-uploads':validation,'../../../../lib/direct-article-upload':{prepareArticleUpload:async()=>{prepares++;return {token:'token'};},completeArticleUpload:async()=>{completes++;return {url:'https://fixture.example/file.mp4'};}}});}const request=body=>({headers:{get:()=> 'application/json'},json:async()=>body});for(const action of ['prepare','complete'])assert.equal((await route(false).POST(request({action,...input}))).status,401);assert.equal(prepares+completes,0);assert.equal((await route(true).POST(request({action:'prepare',...input,size:999999999}))).status,400);assert.equal(prepares,0);const signed=await route(true).POST(request({action:'prepare',...input}));assert.equal(signed.status,200);assert.equal(signed.headers['Cache-Control'],'no-store');assert.equal(prepares,1);assert.equal((await route(true).POST(request({action:'complete',receipt:'receipt'}))).status,200);assert.equal(completes,1);});

test('expired admin session gives actionable feedback before starting storage upload',async()=>{let started=false;class Upload{constructor(){started=true;}}const client=load('lib/article-upload-client.ts',{'./article-uploads':validation,'tus-js-client':{Upload}},{fetch:async()=>Response.json({error:'Unauthorized'},{status:401})});await assert.rejects(client.uploadArticleFile(new File([mp4],'clip.mp4',{type:'video/mp4'}),'video'),/Keep this editor open.*another tab/);assert.equal(started,false);});
test('stalled storage upload aborts and releases the pending upload',async()=>{let timers=[],aborted=false;class Upload{start(){}abort(){aborted=true;return Promise.resolve();}}const client=load('lib/article-upload-client.ts',{'./article-uploads':validation,'tus-js-client':{Upload}},{setTimeout:(fn,delay)=>{const t={fn,delay};timers.push(t);return t;},clearTimeout:t=>{timers=timers.filter(x=>x!==t);},fetch:async()=>Response.json({endpoint:'https://fixture.example',token:'token',receipt:'receipt'})});const pending=client.uploadArticleFile(new File([mp4],'clip.mp4',{type:'video/mp4'}),'video');await new Promise(resolve=>setImmediate(resolve));const watchdog=timers.find(t=>t.delay===120000);assert.ok(watchdog);watchdog.fn();await assert.rejects(pending,/No upload progress/);assert.equal(aborted,true);});


for (const kind of ['document','video']) test(`signed PUT fallback completes ${kind} after TUS rejects its signed token`,async()=>{
 const file=kind==='document'?new File(['%PDF-1.7 fixture'],'test.pdf',{type:'application/pdf'}):new File([mp4],'test.mp4',{type:'video/mp4'});
 const calls=[];class Upload{constructor(body,options){this.options=options;}start(){this.options.onError(Error('Invalid Compact JWS'));}}
 const signedUploadUrl='https://qafixture.supabase.co/storage/v1/object/upload/sign/news-attachments/fixture?token=path-token';
 const client=load('lib/article-upload-client.ts',{'./article-uploads':validation,'tus-js-client':{Upload}},{fetch:async(url,options)=>{calls.push({url,options});if(url===signedUploadUrl)return new Response(null,{status:200});return JSON.parse(options.body).action==='prepare'?Response.json({signedUploadUrl,token:'path-token',receipt:'receipt'}):Response.json({url:'https://fixture.example/attachment',name:file.name});}});
 await client.uploadArticleFile(file,kind);assert.equal(calls.length,3);assert.equal(calls[1].options.method,'PUT');assert.equal(calls[1].options.body,file);assert.equal(calls[1].options.credentials,'omit');assert.equal(calls[1].options.headers['Content-Type'],file.type);assert.equal(JSON.parse(calls[2].options.body).action,'complete');
});
test('other TUS errors do not trigger fallback or completion',async()=>{let calls=0;class Upload{constructor(body,options){this.options=options;}start(){this.options.onError(Error('Permission denied'));}}const client=load('lib/article-upload-client.ts',{'./article-uploads':validation,'tus-js-client':{Upload}},{fetch:async()=>{calls++;return Response.json({signedUploadUrl:'https://fixture.example/upload'});}});await assert.rejects(client.uploadArticleFile(new File([mp4],'test.mp4',{type:'video/mp4'}),'video'),/Permission denied/);assert.equal(calls,1);});
test('failed signed PUT never invokes completion',async()=>{let calls=0;class Upload{constructor(body,options){this.options=options;}start(){this.options.onError(Error('Invalid Compact JWS'));}}const client=load('lib/article-upload-client.ts',{'./article-uploads':validation,'tus-js-client':{Upload}},{fetch:async()=>{calls++;return calls===1?Response.json({signedUploadUrl:'https://fixture.example/upload'}):new Response(null,{status:403});}});await assert.rejects(client.uploadArticleFile(new File([mp4],'test.mp4',{type:'video/mp4'}),'video'),/HTTP 403/);assert.equal(calls,2);});

test('verification returns even when cancelling the signature stream never settles',async()=>{
 let cancelled=false;
 const api=server(async(url,options)=>{
  if(url.includes('/upload/sign/'))return Response.json({url:'/object/upload/sign/news-attachments/file?token=fixture'});
  if(options.method==='HEAD')return new Response(null,{headers:{'content-length':'64','content-type':'application/pdf'}});
  return {ok:true,body:{getReader:()=>({read:async()=>({done:false,value:Buffer.concat([Buffer.from('%PDF-1.7'),Buffer.alloc(56)])}),cancel:()=>{cancelled=true;return new Promise(()=>{});}})}};
 });
 const target=await api.prepareArticleUpload({kind:'document',type:'application/pdf',size:64,name:'fixture.pdf'});
 const result=await api.completeArticleUpload(target.receipt);assert.equal(cancelled,true);assert.equal(result.name,'fixture.pdf');
});
test('stalled storage verification rejects within its deadline even if fetch ignores abort',async()=>{
 let timers=[];
 const api=load('lib/direct-article-upload.ts',{'./article-uploads':validation},{setTimeout:(fn,delay)=>{const t={fn,delay};timers.push(t);return t;},clearTimeout:t=>{timers=timers.filter(x=>x!==t);},fetch:async(url)=>url.includes('/upload/sign/')?Response.json({url:'/object/upload/sign/news-attachments/file?token=fixture'}):new Promise(()=>{})});
 const target=await api.prepareArticleUpload(input);const pending=api.completeArticleUpload(target.receipt);const timer=timers.find(t=>t.delay===20000);assert.ok(timer);timer.fn();await assert.rejects(pending,/Storage verification timed out/);
});
test('100 percent transfer without storage acknowledgement aborts instead of waiting indefinitely',async()=>{
 let timers=[],aborted=false;
 class Upload{constructor(body,options){this.options=options;}start(){this.options.onProgress(24,24);this.options.onProgress(24,24);}abort(){aborted=true;return Promise.resolve();}}
 const client=load('lib/article-upload-client.ts',{'./article-uploads':validation,'tus-js-client':{Upload}},{setTimeout:(fn,delay)=>{const t={fn,delay};timers.push(t);return t;},clearTimeout:t=>{timers=timers.filter(x=>x!==t);},fetch:async()=>Response.json({endpoint:'https://fixture.example',token:'token',receipt:'receipt'})});
 const pending=client.uploadArticleFile(new File([mp4],'clip.mp4',{type:'video/mp4'}),'video');await new Promise(resolve=>setImmediate(resolve));const watchdog=timers.find(t=>t.delay===30000);assert.ok(watchdog);watchdog.fn();await assert.rejects(pending,/Storage did not confirm/);assert.equal(aborted,true);
});
