const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const ts=require('typescript');
const vm=require('node:vm');
function load(path,dependencies={}){const source=fs.readFileSync(path,'utf8');const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const module={exports:{}};vm.runInNewContext(`(function(require,module,exports){${js}\n})`,{Date,URL,AbortSignal,fetch:()=>{throw Error('No network in tests')}})((name)=>{if(!(name in dependencies))throw Error(`Unexpected import ${name}`);return dependencies[name]},module,module.exports);return module.exports;}
test('deadline audit detects extension and removal but not unchanged values',()=>{const {deadlineChange}=load('lib/deadline-audit.ts');assert.equal(deadlineChange({deadline:'18 September 2026',deadline_iso:null},{deadline:'18 September 2026',deadline_iso:null}),null);assert.equal(deadlineChange({deadline:'18 September 2026',deadline_iso:null},{deadline:'25 September 2026',deadline_iso:null}).newDeadline,'25 September 2026');assert.equal(deadlineChange({deadline:'18 September 2026',deadline_iso:null},{deadline:null,deadline_iso:null}).newDeadline,null);});
test('freshness rejects undated, stale and future articles',()=>{const {isFreshPublication,articlePublicationDate}=load('lib/news-importer.ts',{'./news-queue':{}});const now=Date.parse('2026-09-17T12:00:00Z');assert.equal(isFreshPublication(null,now),false);assert.equal(isFreshPublication('2026-09-14T12:00:00Z',now),false);assert.equal(isFreshPublication('2026-09-17T11:00:00Z',now),true);assert.equal(isFreshPublication('2026-09-18T12:00:00Z',now),false);assert.equal(articlePublicationDate('<meta property="article:published_time" content="2026-09-17T11:00:00Z">'),'2026-09-17T11:00:00.000Z');assert.equal(articlePublicationDate('<meta property="article:modified_time" content="2026-09-17T11:00:00Z">'),null);});
test('deadline evidence requires parseable ISO date and official source',()=>{const {deadlineEvidencePresent}=load('lib/source-verification.ts');assert.equal(deadlineEvidencePresent(null,null,null),true);assert.equal(deadlineEvidencePresent('18 September 2026',null,'https://example.com'),false);assert.equal(deadlineEvidencePresent('18 September 2026','2026-09-18T23:59:00+01:00',null),false);assert.equal(deadlineEvidencePresent('18 September 2026','2026-09-18T23:59:00+01:00','https://example.com'),true);});
test('publication quality blocks missing source, deadline evidence and duplicates',()=>{const dependencies={'./news-queue':{},'./operations-insights':{deadlineDate:s=>s.deadline_iso?new Date(s.deadline_iso):null},'./admin-content-flags':{duplicateCandidates:(title,others,id,url)=>others.filter(x=>x.id!==id&&(x.title===title||x.official_source_url===url)).map(story=>({story}))},'./article-blocks':{readArticleBlocks:()=>null,removeArticleBlocks:v=>v},'./source-verification':{deadlineEvidencePresent:(d,i,u)=>!d||!!(i&&u)}};const {publicationQuality}=load('lib/publishing-quality.ts',dependencies);const base={id:'1',title:'Fresh update',summary:'Summary',details:'Body',deadline:'18 September 2026',deadline_iso:'2026-09-18T23:59:00+01:00',official_source_url:'https://example.com'};assert.equal(publicationQuality(base,[]).length,0);assert.ok(publicationQuality({...base,official_source_url:null},[]).some(x=>x.includes('Official source')));assert.ok(publicationQuality({...base,deadline_iso:null},[]).some(x=>x.includes('Deadline')));assert.ok(publicationQuality(base,[{...base,id:'2'}]).some(x=>x.includes('Possible duplicate')));});
