import {INSTITUTIONS, resolveInstitution} from './institution-registry';
import {resolveQuestion} from './question-resolver';
import {redactQuestion} from './privacy';
export type ConversationState={version:2;institutionKey:string|null;academicSession:string|null;academicYear:string|null;intent:string;category:string|null;programme:string|null;utmeScore:number|null;lastQuestion:string;pending:'institution'|'session'|'year'|'programme'|'category'|null;detailed:boolean;offered:'requirements'|'deadline'|null;updatedAt:number};
export type ConversationTurn={role:'user'|'assistant';content:string};
export type ConversationPlan={state:ConversationState;questions:string[];reply?:string;clarification?:boolean;reset?:boolean;closed?:boolean;context:string};
export const CONVERSATION_TTL=30*60*1000;
export function emptyConversation(now=Date.now()):ConversationState{return {version:2,institutionKey:null,academicSession:null,academicYear:null,intent:'general',category:null,programme:null,utmeScore:null,lastQuestion:'',pending:null,detailed:false,offered:null,updatedAt:now};}
const intents=['general','cutoff','deadline','status','requirements','vice_chancellor','fees','result','certificate','caps'];
function short(value:unknown,max=160){return typeof value==='string'?redactQuestion(value).slice(0,max):'';}
export function readConversation(input:unknown,now=Date.now()):ConversationState{
 if(!input||typeof input!=='object')return emptyConversation(now);const x=input as Record<string,unknown>;
 if(x.version!==2||typeof x.updatedAt!=='number'||!Number.isFinite(x.updatedAt)||x.updatedAt>now+60000||now-x.updatedAt>CONVERSATION_TTL)return emptyConversation(now);
 const state=emptyConversation(now);state.institutionKey=INSTITUTIONS.some(i=>i.key===x.institutionKey)?String(x.institutionKey):null;
 state.academicSession=typeof x.academicSession==='string'&&/^20\d{2}\/20\d{2}$/.test(x.academicSession)?x.academicSession:null;
 state.academicYear=typeof x.academicYear==='string'&&/^20\d{2}$/.test(x.academicYear)?x.academicYear:null;
 state.intent=intents.includes(String(x.intent))?String(x.intent):'general';
 state.category=['UTME','Direct Entry','SSCE External','SSCE Internal','Private first series','Private second series','PIN vending','normal registration','late registration','walk-in registration'].includes(String(x.category))?String(x.category):null;
 state.programme=short(x.programme,80)||null;state.utmeScore=typeof x.utmeScore==='number'&&x.utmeScore>=0&&x.utmeScore<=400?x.utmeScore:null;
 state.lastQuestion=short(x.lastQuestion,500);state.pending=['institution','session','year','programme','category'].includes(String(x.pending))?x.pending as ConversationState['pending']:null;state.detailed=x.detailed===true;state.offered=['requirements','deadline'].includes(String(x.offered))?x.offered as ConversationState['offered']:null;return state;
}
const substitutions:[RegExp,string][]=[[/\b(?:putme|pume|post ume|postutme)\b/gi,'Post-UTME'],[/\b(?:cutof|cutoff|cut off|cut-off)\b/gi,'cutoff'],[/\b(?:requirments|requiremnts|requirements?)\b/gi,'requirements'],[/\b(?:deadine|deadlin|closing day)\b/gi,'deadline'],[/\b(?:wen|when e)\b/gi,'when'],[/\b(?:wetin be|wetin|watin)\b/gi,'what'],[/\b(?:how much be|how much e be)\b/gi,'how much'],[/\b(?:dey still open|still dey open|form still dey|form dey on sale)\b/gi,'is it still open'],[/\b(?:e go close|e dey close|form go close|dem go close)\b/gi,'registration deadline'],[/\b(?:i wan|i want to)\b/gi,'I want to'],[/\b(?:abeg|pls|plz)\b/gi,'please']];
function distance(a:string,b:string){const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let diagonal=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const old=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,diagonal+Number(a[i-1]!==b[j-1]));diagonal=old;}}return row[b.length];}
export function normalizeConversationQuestion(input:string){let text=input.normalize('NFKC').replace(/\s+/g,' ').trim();for(const [pattern,replacement]of substitutions)text=text.replace(pattern,replacement);
 // Correct only unambiguous near-spellings of registered institution abbreviations.
 text=text.replace(/\b[a-z]{5,12}\b/gi,word=>{if(resolveInstitution(word))return word;const candidates=INSTITUTIONS.filter(i=>i.key.length>=4&&distance(word.toLowerCase(),i.key)===1);return candidates.length===1?candidates[0].key.toUpperCase():word;});return text.slice(0,500);
}
function subjectOf(q:string){const named=resolveInstitution(q);return named?.key==='jamb'&&resolveQuestion(q).intent==='cutoff'?null:named;}
function intentOf(q:string){if(/\b(fees?|cost|price|how much)\b/i.test(q))return 'fees';if(/\b(certificate|digicert)\b/i.test(q))return 'certificate';if(/\b(result|token|scratch.?card)\b/i.test(q)&&!/minimum|score|cutoff|screening/i.test(q))return 'result';if(/\bcaps\b|admission in progress|not admitted/i.test(q))return 'caps';return resolveQuestion(q).intent;}
function categoryOf(q:string){if(/\b(pin|e.?pin)\b.*\b(vending|sale|deadline)\b/i.test(q))return 'PIN vending';if(/\bdirect entry\b|\bde\b/i.test(q))return 'Direct Entry';if(/ssce external/i.test(q))return 'SSCE External';if(/ssce internal/i.test(q))return 'SSCE Internal';if(/private.{0,30}(?:second|2nd) series/i.test(q))return 'Private second series';if(/private.{0,30}(?:first|1st) series/i.test(q))return 'Private first series';if(/walk.?in/i.test(q))return 'walk-in registration';if(/late registration/i.test(q))return 'late registration';if(/normal registration/i.test(q))return 'normal registration';if(/\butme\b|post.?utme|(?:minimum|my) jamb (?:score|mark)/i.test(q))return 'UTME';return null;}
function programmeOf(q:string){return q.match(/^(accounting|marketing|medicine(?: and surgery)?|nursing|law|computer science|mass communication|business administration|economics|engineering)$/i)?.[1]?.toLowerCase()||q.match(/(?:study|studying|course is|programme is|program is|for the course|for)\s+(?:b[.]?sc[.]?\s+)?(accounting|marketing|medicine(?: and surgery)?|nursing|law|computer science|mass communication|business administration|economics|engineering)\b/i)?.[1]||null;}
const labels:Record<string,string>={cutoff:'minimum JAMB score',deadline:'registration deadline',status:'is registration still open',requirements:'admission requirements',vice_chancellor:'vice chancellor',fees:'fees',result:'result checking',certificate:'certificate',caps:'JAMB CAPS'};
export function conversationContext(state:ConversationState){return [state.institutionKey?.toUpperCase(),state.academicSession||state.academicYear,state.category,state.programme,labels[state.intent]].filter(Boolean).join(' ');}
function scopedQuestion(q:string,state:ConversationState){const explicit=resolveQuestion(q);return [q,!subjectOf(q)?state.institutionKey?.toUpperCase():null,!explicit.academicSession&&!explicit.academicYear?state.academicSession||state.academicYear:null,state.category&&!categoryOf(q)?state.category:null,state.programme&&!programmeOf(q)?state.programme:null].filter(Boolean).join(' ').slice(0,650);}
function needsScope(state:ConversationState){if(!['cutoff','deadline','status','requirements','fees','vice_chancellor'].includes(state.intent))return null;if(!state.institutionKey)return 'institution';if(state.intent==='vice_chancellor')return null;if(state.intent==='requirements'&&!['jamb','waec','neco','nysc'].includes(state.institutionKey)&&!state.category)return 'category';if(['jamb','waec','neco'].includes(state.institutionKey))return state.intent==='fees'||state.academicYear?null:'year';return state.academicSession?null:'session';}
function clarification(state:ConversationState):ConversationPlan{state.pending=needsScope(state);const name=state.institutionKey?.toUpperCase();return {state,questions:[],context:conversationContext(state),clarification:true,reply:state.pending==='category'?`Do you mean UTME or Direct Entry requirements for ${name}?`:state.pending==='institution'?'Which institution or examination body do you mean?':state.pending==='year'?`Which examination year do you mean for ${name}?`:`Which academic session do you mean for ${name}? For example, 2026/2027.`};}
export function planConversation(input:string,prior:unknown=null,history:ConversationTurn[]=[],now=Date.now()):ConversationPlan{
 let state=readConversation(prior,now);if(!state.lastQuestion){for(const turn of history.slice(-40)){if(turn?.role!=='user'||typeof turn.content!=='string')continue;const previous=planConversation(turn.content,state,[],now);state=previous.state;}}
 const q=normalizeConversationQuestion(input),control=q.toLowerCase().replace(/[.!?]+$/,'').trim();
 if(/^(reset|restart|start (?:again|over)|new conversation|forget (?:everything|the previous conversation))$/.test(control))return {state:emptyConversation(now),questions:[],context:'',reply:'Conversation cleared. What would you like help with?',reset:true};
 if(/^(stop|end chat|bye|goodbye|that(?:'s| is) all|no thanks|we(?:'re| are) done)$/.test(control))return {state:emptyConversation(now),questions:[],context:'',reply:'Understood. I’ll stop here. You can return whenever you need guidance.',closed:true};
 if(/^(hi|hello|good (?:morning|afternoon|evening)|hey)$/.test(control))return {state,questions:[],context:conversationContext(state),reply:state.institutionKey?`Hello! We’re discussing ${conversationContext(state)}. What would you like to check next?`:'Hello! What admission, education or S.O.H CONSULTS question can I help you with?'};
 const acknowledgement=/^(yes|yeah|yep|okay|ok|alright|sure|oya|next|continue|proceed|go ahead|what next)$/.test(control);
 if(acknowledgement){if(state.pending)return state.pending==='programme'?{state,questions:[],context:conversationContext(state),clarification:true,reply:'Which programme are you considering?'}:clarification(state);if(!state.lastQuestion)return {state,questions:[],context:'',reply:'What admission, education or S.O.H CONSULTS question would you like help with?'};const active=conversationContext(state);if(!/^(okay|ok|alright)$/.test(control)&&(state.offered||['cutoff','deadline','requirements','status'].includes(state.intent))){state.intent=state.offered||(state.intent==='requirements'?'deadline':'requirements');state.offered=null;if(needsScope(state))return clarification(state);const next=scopedQuestion(labels[state.intent],state);state.lastQuestion=next;return {state,questions:[next],context:conversationContext(state)};}return {state,questions:[],context:active,reply:`For ${active||'your question'}, the next step is to confirm the official requirements and current application window before paying. Would you like me to check the requirements or registration deadline?`};}
 const detail=/^(?:explain(?: it| that)? (?:more|in detail)|more details|tell me more|break it down|make it (?:short|shorter)|summari[sz]e(?: it)?)$/.test(control);
 if(detail){state.detailed=!/short|summari/.test(control);if(!state.lastQuestion)return {state,questions:[],context:'',reply:'What would you like me to explain?'};return {state,questions:[state.lastQuestion],context:conversationContext(state)};}
 state.offered=null;
 const named=subjectOf(q),explicit=resolveQuestion(q),topic=intentOf(q),category=categoryOf(q),programme=programmeOf(q)||(named&&/am i eligible|my chances|admission chance/i.test(q)?q.match(/\b(marketing|accounting|medicine(?: and surgery)?|nursing|law|computer science|mass communication|business administration|economics|engineering)\b/i)?.[1]?.toLowerCase():null)||(state.pending==='programme'&&!named&&!explicit.academicSession&&topic==='general'&&/^[a-z][a-z &’'-]{1,79}$/i.test(q)?q.toLowerCase():null);
 const comparison=/^(?:and |what about |how about |what of |(?:no[, ]+)?i meant |sorry[, ]+)/i.test(q);
 const unrelated=/\b(weather|football|movie|recipe|girlfriend|bitcoin)\b/i.test(q);
 const unknownSchool=/^(?:what about|how about|what of)\s+[a-z]{2,12}[?!.]*$/i.test(input.trim())&&!named&&topic==='general'&&!category&&!programme;
 if(unrelated||unknownSchool){state=emptyConversation(now);return {state,questions:[],context:'',clarification:true,reply:unknownSchool?'Which institution do you mean? Please give its full name.':'I can help with education, admissions and S.O.H CONSULTS services. What would you like to check?'};}
 if(named&&named.key!==state.institutionKey){const old=state;state=emptyConversation(now);state.institutionKey=named.key;const universitySwitch=!['jamb','waec','neco','nysc'].includes(named.key)&&!!old.institutionKey&&!['jamb','waec','neco','nysc'].includes(old.institutionKey);if(comparison||old.pending==='institution'){state.intent=old.intent;if(old.pending==='institution'){state.pending='institution';state.category=old.category;state.programme=old.programme;state.utmeScore=old.utmeScore;if(!['jamb','waec','neco','nysc'].includes(named.key))state.academicSession=old.academicSession;if(/am i eligible|my chances|admission chance/i.test(old.lastQuestion))state.intent='requirements';}if(universitySwitch){state.academicSession=old.academicSession;if(comparison){state.category=old.category;state.programme=old.programme;state.utmeScore=old.utmeScore;}}} }
 if(named)state.institutionKey=named.key;
 if(explicit.academicSession){state.academicSession=explicit.academicSession;state.academicYear=null;}else {const year=q.match(/\b20\d{2}\b/)?.[0];if(year&&state.institutionKey&&['jamb','waec','neco'].includes(state.institutionKey)){state.academicYear=year;state.academicSession=null;}}
 if(topic!=='general'){if(topic!==state.intent){state.pending=null;if(['certificate','result','caps','vice_chancellor'].includes(topic)){state.academicSession=explicit.academicSession;state.academicYear=q.match(/\b20\d{2}\b/)?.[0]||null;state.category=null;state.programme=null;}}state.intent=topic;}
 if(category)state.category=category;if(programme)state.programme=programme;
 const score=q.match(/(?:i (?:scored|got|have)|my (?:utme|jamb) score (?:is)?|score of)\s*(\d{2,3})\b/i)?.[1];if(score&&Number(score)<=400&&(/\b(?:utme|jamb)\b/i.test(q)||state.category==='UTME')){state.utmeScore=Number(score);state.category='UTME';}
 if(/\b(will i gain|can i gain|am i eligible|my chances|admission chance)\b/i.test(q)){state.lastQuestion=redactQuestion(q);state.offered='requirements';state.pending=!state.institutionKey?'institution':!state.programme?'programme':null;return {state,questions:[],context:conversationContext(state),clarification:!!state.pending,reply:state.pending==='institution'?'Which institution and programme are you considering?':state.pending==='programme'?`Which programme at ${state.institutionKey?.toUpperCase()} are you considering? I can explain the published requirements, but cannot guarantee admission.`:`For ${state.programme} at ${state.institutionKey?.toUpperCase()}, compare your stated results${state.utmeScore!==null?' (UTME '+state.utmeScore+')':''} with the official programme requirements, subject combination and application window. A score alone does not establish eligibility or guarantee admission. Would you like the published requirements?`};}
 if(state.pending==='programme'&&programme){state.pending=null;state.intent='requirements';}
 if(named&&topic==='general'&&state.intent==='general'&&q.toLowerCase()===named.key)return {state,questions:[],context:conversationContext(state),reply:`What would you like to know about ${named.key.toUpperCase()}: requirements, minimum score or registration deadline?`};
 let effective=q;if((state.pending&&/^(?:20\d{2}(?:[/_-]20\d{2})?|[a-z -]{2,80})$/i.test(q))||(comparison&&topic==='general')||(/^(?:requirements|deadline|cutoff|fees)$/i.test(q))){effective=labels[state.intent]||q;}
 state.pending=null;state.updatedAt=now;const needed=needsScope(state);if(needed)return clarification(state);
 const namedInstitutions=INSTITUTIONS.filter(i=>!(i.key==='jamb'&&resolveQuestion(q).intent==='cutoff')&&i.aliases.some(alias=>new RegExp('(?:^|[^a-z])'+alias.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?:$|[^a-z])','i').test(q)));
 let parts=q.split(/\s*;\s*|\s+and\s+(?=(?:what|when|how|(?:the )?(?:deadline|requirements|cutoff|minimum|fees))\b)/i).filter(Boolean);
 if(parts.length>3||namedInstitutions.length>3)return {state,questions:[],context:conversationContext(state),clarification:true,reply:'Please choose up to three questions or institutions to check together.'};
 if(namedInstitutions.length>1){parts=namedInstitutions.map(i=>q.replace(new RegExp(namedInstitutions.filter(n=>n.key!==i.key).flatMap(n=>n.aliases).sort((a,b)=>b.length-a.length).join('|'),'gi'),'').replace(/\band\b/gi,' ').trim());}
 if(parts.length===1)parts=[effective];
 const questions=parts.map(part=>scopedQuestion(part,state));state.lastQuestion=redactQuestion(questions.at(-1)||effective).slice(0,500);return {state,questions,context:conversationContext(state)};
}
