import { extractText, getDocumentProxy } from 'unpdf';
import { InstitutionRecord, isOfficialInstitutionUrl } from './institution-registry';
import { publisherCookies, yearArchiveRequest, boundedText, publicFragment, portalDeclarations, publicAssetLinks, PortalDeclaration } from './public-source-adapters';
import { cacheGet, cacheSet } from './cache';

// Bound simultaneous adapter work across institutions; timeouts start after a slot
// is obtained so a busy outbound connection pool cannot erase source coverage.
let activeTasks=0;const waitingTasks:(()=>void)[]=[];
async function sourceTask<T>(work:()=>Promise<T>):Promise<T>{if(activeTasks>=8)await new Promise<void>(resolve=>waitingTasks.push(resolve));else activeTasks++;try{return await work();}finally{const next=waitingTasks.shift();if(next)next();else activeTasks--;}}
export type SourceDocument = {title:string;url:string;snippet:string;official:boolean;internal?:boolean;publishedAt?:string|null;fetchedAt?:string;session?:string|null;kind?:'article'|'portal'|'pdf'|'homepage'|'search';adapter?:string;verified?:boolean;retrievalUrl?:string;portalDeclarations?:PortalDeclaration[]};
export type CoverageGap = {adapter:string;url:string;reason:string};
type Link = {title:string;url:string;publishedAt?:string|null;abstract?:string};
export type DiscoveryOptions = {fetcher?:typeof fetch;timeoutMs?:number;maxDocuments?:number;useCache?:boolean};
export function plainText(raw:string){return raw.replace(/<!--[\s\S]*?-->/g,' ').replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<(nav|header|footer)\b[\s\S]*?<\/\1>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/\s+/g,' ').trim();}
export function sessionsIn(text:string){return [...new Set([...text.matchAll(/\b(20\d{2})\s*[\/_-]\s*(20\d{2})\b/g)].map(m=>m[1]+'/'+m[2]))];}
export function sourceAllowed(url:string,institution:InstitutionRecord){try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password&&isOfficialInstitutionUrl(url,institution.key);}catch{return false;}}
function publication(raw:string){const value=raw.match(/<meta[^>]+(?:property|name)=["'](?:article:published_time|date|datePublished)["'][^>]+content=["']([^"']+)/i)?.[1]||raw.match(/"datePublished"\s*:\s*"([^"]+)"/)?.[1]||plainText(raw.match(/<(?:span|div)[^>]*>\s*<i[^>]*class=["'][^"']*(?:calendar-check|calendar-day)[^"']*["'][^>]*><\/i>([^<]+)/i)?.[1]||'').replace(/,?\s+\d{1,2}:\d{2}(?:am|pm)?$/i,'')||raw.match(/<time[^>]+datetime=["']([^"']+)/i)?.[1];return value&&Number.isFinite(Date.parse(value))?new Date(/[a-z]{3}/i.test(value)&&!/(?:GMT|UTC|[+-]\d{4})/.test(value)?value+' UTC':value).toISOString():null;}
export function mainBody(raw:string){
 // WordPress/Elementor may use <article> only for unrelated news cards.
 // Prefer the balanced post-content container, including nested divs.
 const marker=raw.match(/<(div|section)\b[^>]*class=["'][^"']*(?:elementor-widget-theme-post-content|\bentry-content\b|\bpost-content\b|\bnews-details-content\b|\bev-detail-body\b)[^"']*["'][^>]*>/i);
 if(marker?.index!==undefined){const tag=marker[1],start=marker.index+marker[0].length,tokens=new RegExp('<'+tag+'\\b[^>]*>|</'+tag+'\\s*>','gi');tokens.lastIndex=start;let depth=1;let token;while((token=tokens.exec(raw))){depth+=token[0].startsWith('</')?-1:1;if(depth===0)return raw.slice(start,token.index);}}
 return raw.match(/<article\b[^>]*>([\s\S]*?)<\/article>/i)?.[1]||raw.match(/<main\b[^>]*>([\s\S]*?)<\/main>/i)?.[1]||raw;}
function balancedContent(raw:string,start:number,tag:string){const tokens=new RegExp('<'+tag+'\\b[^>]*>|</'+tag+'\\s*>','gi');tokens.lastIndex=start;let depth=1;let token;while((token=tokens.exec(raw))){depth+=token[0].startsWith('</')?-1:1;if(depth===0)return raw.slice(start,token.index);}return '';}
function anchorLinks(raw:string,base:string):Link[]{return [...raw.matchAll(/<a\b[^>]+href\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))[^>]*>([\s\S]*?)<\/a>/gi)].flatMap(m=>{try{const href=m[1]??m[2]??m[3];return href.startsWith('#')?[]:[{url:new URL(href.replace(/&amp;/g,'&'),base).href,title:plainText(m[4])}];}catch{return [];}});}
export function htmlLinks(raw:string,base:string):Link[]{
 const links=anchorLinks(raw,base);
 // Older news platforms put the headline on href="#" and the real URL on
 // "READ Now". Keep each card's headline, date and abstract with its own URL.
 for(const marker of raw.matchAll(/<(div|article)\b[^>]*class=["'][^"']*(?:\bsingle-latest-item\b|\bev-card\b|\bviews-row\b)[^"']*["'][^>]*>/gi)){
  const body=balancedContent(raw,marker.index!+marker[0].length,marker[1]);const title=plainText(body.match(/<h[1-4][^>]*>([\s\S]*?)<\/h[1-4]>/i)?.[1]||'');if(!title)continue;
  const abstract=plainText(body.match(/<p[^>]*>([\s\S]*?)<\/p>/i)?.[1]||'');
  for(const link of anchorLinks(body,base))links.push({...link,title,publishedAt:publication(body),abstract});
 }
 return links;
}
export function feedLinks(raw:string):Link[]{return [...raw.matchAll(/<(?:item|entry)\b[^>]*>([\s\S]*?)<\/(?:item|entry)>/gi)].flatMap(m=>{const body=m[1],url=body.match(/<link[^>]*>\s*(?:<!\[CDATA\[)?([^<\]]+)/i)?.[1]?.trim()||body.match(/<link[^>]+href=["']([^"']+)/i)?.[1];return url?[{url:url.replace(/&amp;/g,'&'),title:plainText(body.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||''),publishedAt:body.match(/<(?:pubDate|published)>([^<]+)/i)?.[1]||null}]:[];});}
const TOPIC=/admission|screening|post.?utme|registration|deadline|extension|circular|news|result|certificate|examination|cut.?off|vice.?chancellor/i;
function relevance(link:Link,question:string,session:string|null){const text=(link.title+' '+decodeURI(link.url)+' '+(link.abstract||'')).toLowerCase();const terms=question.toLowerCase().split(/[^a-z0-9]+/).filter(t=>t.length>3);return terms.reduce((n,t)=>n+(text.includes(t)?3:0),0)+(TOPIC.test(text)?4:0)+(/bulletin/i.test(text)&&/registration|deadline|news/i.test(question)?20:0)+(/deadline|closing date|registration closes|extended to/i.test(link.abstract||link.title)?35:0)+(/post.?utme|screening/i.test(question)&&/post.?utme|screening/i.test(link.title)?30:0)+(session&&sessionsIn(text).includes(session)?20:0)+(!session&&question.match(/\b20\d{2}\b/)?.[0]&&text.includes(question.match(/\b20\d{2}\b/)![0])?12:0)-(/\/tag\/|\/category\//.test(link.url)?5:0);}

// Every redirect must retain institution ownership; a successful fetch alone is not authority.
export function fetchOfficialDocument(link:Link,institution:InstitutionRecord,options:DiscoveryOptions={},adapter='direct'){return sourceTask(()=>extractOfficialDocument(link,institution,options,adapter));}
async function extractOfficialDocument(link:Link,institution:InstitutionRecord,options:DiscoveryOptions,adapter:string):Promise<{document:SourceDocument|null;gap?:CoverageGap}>{
 const fetcher=options.fetcher||fetch;let url=link.url;
 try{
  let response:Response|undefined;let cookies='';
  for(let hop=0;hop<4;hop++){
   if(!sourceAllowed(url,institution))throw new Error('Non-official URL or redirect');
   response=await fetcher(url,{redirect:'manual',headers:{'User-Agent':'AskSOH/2.0 (+https://sohconsults.com.ng)','Accept':'text/html,application/pdf,text/plain'},signal:AbortSignal.timeout(options.timeoutMs||6000),cache:'no-store'});
   if(response.status>=300&&response.status<400){const location=response.headers.get('location');if(!location)throw new Error('Redirect without location');url=new URL(location,url).href;continue;}break;
  }
  if(!response?.ok)throw new Error('HTTP '+response?.status);
  const type=response.headers.get('content-type')||'';
  const byteLimit=type.includes('pdf')||/\.pdf(?:$|\?)/i.test(url)?16_000_000:8_000_000;
  if(Number(response.headers.get('content-length'))>byteLimit)throw new Error('Source exceeds '+byteLimit/1_000_000+' MB extraction limit');
  // Stream limit also applies when content-length is absent or inaccurate.
  const reader=response.body?.getReader();if(!reader)throw new Error('Empty source');const chunks:Uint8Array[]=[];let length=0;
  while(true){const next=await reader.read();if(next.done)break;length+=next.value.length;if(length>byteLimit){await reader.cancel();throw new Error('Source exceeds '+byteLimit/1_000_000+' MB extraction limit');}chunks.push(next.value);}
  const bytes=new Uint8Array(length);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}
  let declarations:PortalDeclaration[]=[];let text='',title=link.title,publishedAt=link.publishedAt||null;let kind:SourceDocument['kind']='article';
  if(type.includes('pdf')||new TextDecoder().decode(bytes.slice(0,5))==='%PDF-'){const pdf=await getDocumentProxy(bytes);try{if(pdf.numPages>80)throw new Error('PDF exceeds 80 page extraction limit');text=(await extractText(pdf,{mergePages:true})).text;}finally{await pdf.destroy();}kind='pdf';}
  else {let raw=new TextDecoder().decode(bytes);if(!type.includes('html')&&!type.includes('text/plain')&&!/^\s*</.test(raw))throw new Error('Unsupported source format');const fragment=publicFragment(raw,url);if(fragment&&sourceAllowed(fragment,institution)&&new URL(fragment).origin===new URL(url).origin){cookies=response.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');const part=await fetcher(fragment,{redirect:'error',headers:{Accept:'text/html',...(cookies?{Cookie:cookies}:{})},signal:AbortSignal.timeout(options.timeoutMs||6000),cache:'no-store'});if(!part.ok)throw new Error('Public fragment HTTP '+part.status);cookies=publisherCookies(cookies,part);const body=await boundedText(part);const heading=plainText(body.match(/<h[1-3][^>]*>([\s\S]*?)<\/h[1-3]>/i)?.[1]||'');const pageTitle=plainText(raw.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||'');if(fragment.endsWith('/read.php')&&heading&&pageTitle&&!pageTitle.toLowerCase().includes(heading.toLowerCase()))throw new Error('Public fragment does not match requested notice');if(body.length>2_000_000)throw new Error('Public fragment too large');raw=raw.replace(/<script\b[\s\S]*?<\/script>/gi,'')+body;raw=(raw.match(/<title[^>]*>[\s\S]*?<\/title>/i)?.[0]||'')+body;}
   declarations=portalDeclarations(raw);title=plainText(raw.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||title);publishedAt=publication(raw)||publishedAt;text=plainText(mainBody(raw));const path=new URL(url).pathname;kind=/news\/?$|events\.php$|Bulletins(?:\.aspx)?$/i.test(path)&&!new URL(url).search?'search':declarations.length||/^(?:registration|admission|putme|ssceexternal|ssceinternal)[.]/i.test(new URL(url).hostname)?'portal':/^\/(?:home\/?)?$/.test(path)?'homepage':/portal|admission|putme/.test(path)&&!publishedAt?'portal':'article';}
  if(text.length<40||/just a moment|captcha|performing security verification|verifies you are not a bot|verify you are human|checking your browser|security service to protect against malicious bots|access denied|page not found/i.test(title+' '+text.slice(0,250)))throw new Error('No usable evidence or access challenge');
  const sessions=sessionsIn(title+' '+text);
  return {document:{title,url,snippet:text.slice(0,24000),official:true,publishedAt,fetchedAt:new Date().toISOString(),session:sessions.length===1?sessions[0]:null,kind,adapter,verified:true,...(declarations.length?{portalDeclarations:declarations}:{})}};
 }catch(e){return {document:null,gap:{adapter,url,reason:e instanceof Error?e.message:'Source unavailable'}};}
}

// Independent adapters expose URLs, never authoritative search snippets.
export async function discoverOfficialSources(institution:InstitutionRecord,question:string,session:string|null,options:DiscoveryOptions={}){
 const cacheKey='discovery:'+institution.key+':'+session+':'+question.toLowerCase();
 const cached=options.useCache!==false?cacheGet<{documents:SourceDocument[];gaps:CoverageGap[]}>(cacheKey):null;if(cached)return {...cached,cacheHit:true};
 const fetcher=options.fetcher||fetch,gaps:CoverageGap[]=[];const links:Link[]=[];const apiDocuments:SourceDocument[]=[];const roots=[...new Set(institution.officialDomains.map(d=>'https://'+d+'/'))];
 const bases=new Map<string,string>();const pending=new Map<string,Promise<string>>();const readRaw=async(url:string,adapter:string)=>{try{if(!sourceAllowed(url,institution))throw new Error('Non-official adapter URL');let target=url;let r:Response|undefined;for(let hop=0;hop<4;hop++){if(!sourceAllowed(target,institution))throw new Error('Non-official listing redirect');r=await fetcher(target,{redirect:'manual',signal:AbortSignal.timeout(options.timeoutMs||6000),headers:{Accept:'application/json,text/xml,text/html'},cache:'no-store'});if(r.status>=300&&r.status<400){const location=r.headers.get('location');if(!location)throw new Error('Redirect without location');target=new URL(location,target).href;continue;}break;}if(!r?.ok)throw new Error('HTTP '+r?.status);bases.set(url,target);const reader=r.body?.getReader();if(!reader)return '';const decoder=new TextDecoder();let text='';let size=0;while(true){const chunk=await reader.read();if(chunk.done)break;size+=chunk.value.length;if(size>2_000_000){await reader.cancel();throw new Error('Listing too large');}text+=decoder.decode(chunk.value,{stream:true});}text+=decoder.decode();const fragment=publicFragment(text,target);if(fragment&&sourceAllowed(fragment,institution)&&new URL(fragment).origin===new URL(target).origin){let cookie=publisherCookies('',r);const part=await fetcher(fragment,{redirect:'error',headers:{Accept:'text/html',...(cookie?{Cookie:cookie}:{})},signal:AbortSignal.timeout(options.timeoutMs||6000),cache:'no-store'});if(!part.ok)throw new Error('Public fragment HTTP '+part.status);cookie=publisherCookies(cookie,part);const body=await boundedText(part);if(body.length>2_000_000)throw new Error('Public fragment too large');text+=' '+body;const more=fragment.endsWith('/index.php')&&/ajax\/loadmore\.php/.test(text)?new URL('loadmore.php',fragment).href:null;if(more)for(let page=0;page<8;page++){const next=await fetcher(more,{redirect:'error',headers:{Accept:'text/html',...(cookie?{Cookie:cookie}:{})},signal:AbortSignal.timeout(options.timeoutMs||6000),cache:'no-store'});if(!next.ok)break;cookie=publisherCookies(cookie,next);const html=await boundedText(next);if(html.length>2_000_000)throw new Error('Public listing too large');if(html.trim().length<40)break;text+=' '+html;}}return text;}catch(e){gaps.push({adapter,url,reason:e instanceof Error?e.message:'Unavailable'});return '';}};
 const read=(url:string,adapter:string)=>{const key=url.replace(/(\/news)\/$/,'$1');let job=pending.get(key);if(!job){job=readRaw(url,adapter);pending.set(key,job);}return job.then(text=>{const base=bases.get(key)||bases.get(url)||url;bases.set(key,base);bases.set(url,base);return text;});};
 const primary=roots[0];
 const discoveryRoots=[...new Set([primary,'https://www.'+institution.officialDomains[0]+'/'])];
 for(const url of institution.sourceUrls||[])links.push({url,title:institution.name+' official portal'});
 const jobs=[
  ...discoveryRoots.map(root=>async()=>{const term=['jamb','waec','neco'].includes(institution.key)?(/registration|deadline/i.test(question)?'registration':question.replace(new RegExp(institution.key,'ig'),'').trim()):/screening|utme|admission|deadline/i.test(question)?'post-utme':/certificate/i.test(question)?'certificate':/result/i.test(question)?'result':question.replace(new RegExp(institution.key,'ig'),'').trim();const url=root+'wp-json/wp/v2/posts?search='+encodeURIComponent(term)+'&per_page=30';const raw=await read(url,'wordpress');try{const data=JSON.parse(raw);if(Array.isArray(data))for(const row of data)if(row.link){const title=plainText(row.title?.rendered||''),body=plainText(row.content?.rendered||''),publishedAt=row.date_gmt?row.date_gmt+'Z':null;links.push({url:row.link,title,publishedAt,abstract:body||plainText(row.excerpt?.rendered||'')});if(sourceAllowed(row.link,institution)){links.push(...htmlLinks(row.content?.rendered||'',row.link));if(row.status==='publish'&&!row.content?.protected&&body.length>=40&&publishedAt&&Number.isFinite(Date.parse(publishedAt))){const sessions=sessionsIn(title+' '+body);apiDocuments.push({title,url:row.link,retrievalUrl:url,snippet:body.slice(0,24000),official:true,verified:true,publishedAt,fetchedAt:new Date().toISOString(),session:sessions.length===1?sessions[0]:null,kind:'article',adapter:'wordpress-rest'});}}}}catch{}}),
  ...discoveryRoots.map(root=>async()=>{const raw=await read(root+'feed/','rss');for(const m of raw.matchAll(/<(?:item|entry)\b[^>]*>([\s\S]*?)<\/(?:item|entry)>/gi)){const body=m[1];const url=body.match(/<link[^>]*>\s*(?:<!\[CDATA\[)?([^<\]]+)/i)?.[1]?.trim()||body.match(/<link[^>]+href=["']([^"']+)/i)?.[1];if(url)links.push({url,title:plainText(body.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||''),publishedAt:body.match(/<(?:pubDate|published)>([^<]+)/i)?.[1]||null});}}),
  async()=>{const urls=discoveryRoots.flatMap(root=>[root+'sitemap.xml',root+'wp-sitemap.xml']);for(const url of urls){const raw=await read(url,'sitemap');const children=[...raw.matchAll(/<loc>\s*([^<]+)\s*<\/loc>/gi)].map(m=>m[1].trim().replace(/&amp;/g,'&'));if(/<sitemapindex/i.test(raw)){await Promise.all(children.filter(u=>sourceAllowed(u,institution)).sort((a,b)=>Number(/post|news/i.test(b))-Number(/post|news/i.test(a))).slice(0,3).map(async child=>{const xml=await read(child,'sitemap-child');for(const m of xml.matchAll(/<loc>\s*([^<]+)\s*<\/loc>/gi))links.push({url:m[1].trim().replace(/&amp;/g,'&'),title:''});}));}else children.forEach(u=>links.push({url:u,title:''}));}},
  ...[...discoveryRoots,...roots.slice(1,3),...(institution.sourceUrls||[])].map(root=>async()=>{const raw=await read(root,'html');links.push({url:root,title:institution.name});links.push(...htmlLinks(raw,bases.get(root)||root));const year=question.match(/\b20\d{2}\b/)?.[0];const archive=year?yearArchiveRequest(raw,bases.get(root)||root,year):null;if(archive&&sourceAllowed(archive.url,institution)){try{const response=await fetcher(archive.url,{method:'POST',body:archive.body,headers:{'Content-Type':'application/x-www-form-urlencoded'},redirect:'error',signal:AbortSignal.timeout(options.timeoutMs||6000),cache:'no-store'});if(!response.ok)throw new Error('Archive HTTP '+response.status);links.push(...htmlLinks(await boundedText(response),archive.url));}catch(e){gaps.push({adapter:'year-archive',url:archive.url,reason:e instanceof Error?e.message:'Unavailable'});}}const feeds=[...raw.matchAll(/<link\b[^>]*>/gi)].flatMap(m=>/application\/(?:rss|atom)\+xml/i.test(m[0])?[m[0].match(/href=["']([^"']+)/i)?.[1]||'']:[]);for(const feed of feeds.slice(0,2)){try{const url=new URL(feed,root).href;if(sourceAllowed(url,institution))links.push(...feedLinks(await read(url,'declared-feed')));}catch{}}})
 ];
 // Operational adapters stay bounded so one unavailable platform cannot block the others.
 await Promise.allSettled(jobs.map(job=>sourceTask(job)));
 // SPA assets may declare public PDF links. Follow at most two same-domain chunks;
 // only fetched PDFs become evidence, never JavaScript strings.
 if(!links.some(l=>/\.pdf(?:$|\?)/i.test(l.url))){const rootHtml=await read(primary,'spa-shell');const assets=publicAssetLinks(rootHtml,primary).filter(u=>sourceAllowed(u,institution)).slice(0,1);for(const asset of assets){const code=await read(asset,'spa-asset');const children=publicAssetLinks(code,asset).filter(u=>sourceAllowed(u,institution));for(const child of children.filter(u=>u.endsWith('.js')).slice(0,2)){const chunk=await read(child,'spa-chunk');for(const pdf of publicAssetLinks(chunk,child).filter(u=>/\.pdf$/i.test(u)))links.push({url:pdf,title:decodeURI(new URL(pdf).pathname)});}for(const pdf of children.filter(u=>/\.pdf$/i.test(u)))links.push({url:pdf,title:decodeURI(new URL(pdf).pathname)});}}
 // Follow news/admission listing links once, including non-WordPress platforms.
 const listings=links.filter(l=>sourceAllowed(l.url,institution)&&/news\/?$|admission\/?$|events\.php$|news\.php$|Bulletins\.aspx$/i.test(l.url)).slice(0,3);
 await Promise.all(listings.map(link=>sourceTask(async()=>links.push(...htmlLinks(await read(link.url,'news-listing'),bases.get(link.url)||link.url)))));
 for(const link of links){try{const url=new URL(link.url);for(const key of [...url.searchParams.keys()])if(key.startsWith('utm_'))url.searchParams.delete(key);url.hash='';link.url=url.href;}catch{}}
 const merged=new Map<string,Link>();for(const link of links.filter(l=>sourceAllowed(l.url,institution)&&!/[.](?:zip|exe|css|js|png|jpe?g|gif)(?:$|[?#])/i.test(l.url))){const previous=merged.get(link.url);merged.set(link.url,{...link,title:!previous?.title||/^(?:view event|read now|download)$/i.test(previous.title)?link.title:previous.title,abstract:previous?.abstract||link.abstract,publishedAt:previous?.publishedAt||link.publishedAt});}
 const ranked=[...merged.values()].sort((a,b)=>relevance(b,question,session)-relevance(a,question,session)).slice(0,options.maxDocuments||10);
 const stable=options.maxDocuments===1?[]:(institution.sourceUrls||[]).filter(url=>/admission|putme|screening/i.test(url)).slice(0,2).flatMap(url=>merged.get(url)?[merged.get(url)!]:[]);const unique=[...new Map([...stable,...ranked].map(l=>[l.url,l])).values()].slice(0,options.maxDocuments||10);
 const fetched=await Promise.all(unique.map(link=>fetchOfficialDocument(link,institution,options,'discovery')));
 fetched.forEach(r=>{if(r.gap)gaps.push(r.gap);});const direct=fetched.flatMap(r=>r.document?[r.document]:[]);const fallback=apiDocuments.filter(d=>unique.some(l=>l.url===d.url)&&!direct.some(doc=>doc.url===d.url));const result={documents:[...fallback,...direct],gaps};
 if(options.useCache!==false&&result.documents.length)cacheSet(cacheKey,result,180);return {...result,cacheHit:false};
}

export async function searchProviderSources(question:string,institution:InstitutionRecord,options:DiscoveryOptions={}){
 const fetcher=options.fetcher||fetch,gaps:CoverageGap[]=[];const candidates:Link[]=[];
 const providers=[
  {name:'brave',url:'https://api.search.brave.com/res/v1/web/search?q='+encodeURIComponent(question+' site:'+institution.officialDomains[0]),key:process.env.BRAVE_SEARCH_API_KEY},
  {name:'jina-google',url:'https://r.jina.ai/http://www.google.com/search?q='+encodeURIComponent(question+' site:'+institution.officialDomains[0])},
  {name:'jina-bing',url:'https://r.jina.ai/http://www.bing.com/search?q='+encodeURIComponent(question+' site:'+institution.officialDomains[0])}
 ];
 for(const provider of providers){if(provider.name==='brave'&&!provider.key)continue;try{const r=await fetcher(provider.url,{headers:provider.key?{'X-Subscription-Token':provider.key}: {Accept:'text/plain'},signal:AbortSignal.timeout(options.timeoutMs||4000),cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const raw=await r.text();if(provider.name==='brave'){const data=JSON.parse(raw);for(const item of data.web?.results||[])candidates.push({title:item.title,url:item.url});}else for(const m of raw.matchAll(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g))candidates.push({title:m[1],url:m[2]});if(candidates.some(l=>sourceAllowed(l.url,institution)))break;throw new Error('No institution-owned URLs');}catch(e){gaps.push({adapter:provider.name,url:provider.url,reason:e instanceof Error?e.message:'Provider unavailable'});}}
 const unique=[...new Map(candidates.filter(l=>sourceAllowed(l.url,institution)).map(l=>[l.url,l])).values()].slice(0,6);const fetched=await Promise.all(unique.map(l=>fetchOfficialDocument(l,institution,options,'search-provider')));fetched.forEach(r=>{if(r.gap)gaps.push(r.gap);});return {documents:fetched.flatMap(r=>r.document?[r.document]:[]),gaps};
}
