import { headers } from "next/headers";
import JsonLd from "./components/JsonLd";
import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PWARegister from "./components/PWARegister";
import InstallApp from "./components/InstallApp";
import AskSOH from "./components/AskSOH";
import MobileNav from "./components/MobileNav";
import WideViewportControls from "./components/WideViewportControls";
import VisitCounter from "./components/VisitCounter";
import HomeLatestUpdates from "./components/HomeLatestUpdates";
import HomeAnnouncement from "./components/HomeAnnouncement";
import BusinessAnalytics from "./components/BusinessAnalytics";
import CalculatorDisclaimerNotice from "./components/CalculatorDisclaimerNotice";
import BusinessContactSync from "./components/BusinessContactSync";
import { getSiteUrl } from "./site-url";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const siteUrl = getSiteUrl();
export const metadata: Metadata = {metadataBase:new URL(siteUrl),title:{default:"S.O.H CONSULTS | Admission, Education & Consultation",template:"%s | S.O.H CONSULTS"},description:"S.O.H CONSULTS provides admission guidance, educational updates, JAMB support, application assistance and the LASU Aggregate & Eligibility Checker.",keywords:["S.O.H CONSULTS","LASU aggregate calculator","LASU admission","LASU admission calculator","LASU eligibility checker","admission opportunities Nigeria","JAMB services","JAMB admission","education updates Nigeria","admission guidance","Post UTME registration","Direct Entry admission"],authors:[{name:"S.O.H CONSULTS"}],creator:"S.O.H CONSULTS",publisher:"S.O.H CONSULTS",robots:{index:true,follow:true,googleBot:{index:true,follow:true,"max-video-preview":-1,"max-image-preview":"large","max-snippet":-1}},icons:{icon:[{url:"/icon.png",type:"image/png",sizes:"512x512"},{url:"/icons/icon-192.png",type:"image/png",sizes:"192x192"}],shortcut:"/icon.png",apple:"/icons/icon-192.png"},openGraph:{type:"website",title:"S.O.H CONSULTS | Admission, Education & Consultation",description:"Admission guidance, educational opportunities, JAMB support and the LASU Aggregate & Eligibility Checker.",siteName:"S.O.H CONSULTS",url:siteUrl,images:[{url:"/soh-logo.jpg",alt:"S.O.H CONSULTS"}]},manifest:"/manifest.webmanifest",verification:{google:"BdoiW3GoHdajYLbbLSmm-UQpo3YrjBAAWT2NpoKTcBs"}};
export const viewport: Viewport = { themeColor: "#15803d", width:980, initialScale:undefined, userScalable:true, viewportFit:"cover" };
const organizationStructuredData={"@context":"https://schema.org","@type":"Organization","@id":`${siteUrl}/#organization`,name:"S.O.H CONSULTS",url:siteUrl,logo:`${siteUrl}/soh-logo.jpg`,description:"S.O.H CONSULTS provides admission guidance, educational consultation, JAMB support, application assistance, educational updates and admission tools for students and applicants in Nigeria.",email:"mailto:support@sohconsults.com.ng",telephone:"+2348182141088",founder:{"@type":"Person",name:"Oluyepe Adetayo Sunday"},sameAs:["https://www.instagram.com/sohconsults/","https://www.facebook.com/share/19Mzqo5Ggg/","https://whatsapp.com/channel/0029VbD6QQp3GJP68dl9TK29"],contactPoint:{"@type":"ContactPoint",telephone:"+2348182141088",email:"support@sohconsults.com.ng",contactType:"customer service",areaServed:"NG",availableLanguage:["English"]},areaServed:{"@type":"Country",name:"Nigeria"}};
export default async function RootLayout({children}:Readonly<{children:React.ReactNode}>){const requestHeaders=await headers();const nonce=requestHeaders.get("x-nonce")||undefined;const privatePage=requestHeaders.get("x-private-page")==="true";return <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}><head>{!privatePage&&<script nonce={nonce} async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9913781873857877" crossOrigin="anonymous"/>}<JsonLd data={[organizationStructuredData,{"@context":"https://schema.org","@type":"WebSite","@id":`${siteUrl}/#website`,name:"S.O.H CONSULTS",url:siteUrl,publisher:{"@id":`${siteUrl}/#organization`}}]}/></head><body className="min-h-full flex flex-col"><WideViewportControls/><PWARegister/><HomeAnnouncement/>{children}<CalculatorDisclaimerNotice/><footer aria-label="Legal information" className="bg-[#043b29] px-4 py-3 text-center text-xs text-white"><a href="/privacy-policy" className="inline-block rounded px-2 py-1 font-semibold underline underline-offset-4 hover:text-[#efc46e]">Privacy Policy</a><a href="/disclaimer" className="inline-block rounded px-2 py-1 font-semibold underline underline-offset-4 hover:text-[#efc46e]">Disclaimer</a><span className="block pt-1">CAC Registered Business | BN8780171</span></footer><HomeLatestUpdates/><VisitCounter/><BusinessAnalytics/><AskSOH/><InstallApp/><MobileNav/><BusinessContactSync/></body></html>}
