"use client";
import { useMemo, useState } from "react";
import { jsPDF } from "jspdf";
import SiteContact from "../components/SiteContact";

const grades=["A1","B2","B3","C4","C5","C6"];
const gradePoints:Record<string,number>={A1:6,B2:5,B3:4,C4:3,C5:2,C6:1};
const programmes=["Accounting","Adult Education","Agricultural Economics And Extension","Agricultural Education","Agricultural Engineering","Animal and Environmental Biology","Animal Production And Health","Anatomy","Architecture","Biochemistry","Biology Education","Broadcasting","Building","Business Administration","Business Education","Chemistry","Chemistry Education","Civil Engineering","Computer Engineering","Computer Science","Criminology and Security Studies","Crop Science and Horticulture","Cyber Security","Data Science And Analytic","Demography and Social Statistics","Doctor of Pharmacy","Economics and Development Studies","Economics Education","Educational Management","Educational Technology","Electrical and Electronics Engineering","English And Literary Studies","English Language Education","Environmental Management and Toxicology","Estate Management","Finance","Fisheries And Aquaculture","Food Science And Technology","Geology","Geophysics","Guidance And Counselling","Health Education","History And International Studies","Hospitality And Tourism Management","Human Kinetics","Industrial Chemistry","Information and Communication Engineering","LAW","Library And Information Science","Linguistics and languages","Mass Communication","Materials and Metallurgical Engineering","Mathematics","Mathematics Education","Mechanical Engineering","Mechatronics Engineering","Medical Laboratory Science","Medicine and Surgery","Microbiology","Nursing","Peace And Conflict Studies","Philosophy","Physics","Physics Education","Plant Science And Biotechnology","Political Science","Primary Education","Psychology","Public Administration","Public Relations","Quantity Surveying","Radiography and Radiation Science","Religious Studies","Sociology","Software Engineering","Soil Science And Land Resources Management","Statistics","Surveying and Geoinformatics","System Engineering","Theatre And Media Arts","Urban and Regional Planing","Water Resources Management And Agrometeorology"];
const subjects=["English Language","Mathematics","Biology","Chemistry","Physics","Agricultural Science","Economics","Government","Geography","Literature-in-English","Commerce","Accounting","Civic Education","Further Mathematics","Christian Religious Studies","Islamic Studies","History","Yoruba","French","Technical Drawing"].sort();
type Entry={subject:string;grade:string};

export default function FuoyeCalculator(){
 const [candidateName,setCandidateName]=useState("");
 const [programme,setProgramme]=useState("");
 const [jamb,setJamb]=useState(""); const [sittings,setSittings]=useState<1|2>(1);
 const [entries,setEntries]=useState<Entry[]>(Array.from({length:5},()=>({subject:"",grade:""}))); const [calculated,setCalculated]=useState(false);
 const jambNum=Math.max(0,Math.min(400,Number(jamb)||0)); const jambPoints=jambNum*0.15;
 const olevelPoints=useMemo(()=>entries.reduce((s,e)=>s+(gradePoints[e.grade]||0),0),[entries]);
 const bonus=sittings===1?10:6; const total=jambPoints+olevelPoints+bonus;
 const complete=candidateName.trim()!==""&&programme!==""&&jambNum>0&&entries.every(e=>e.subject&&e.grade)&&new Set(entries.map(e=>e.subject)).size===5;
 function update(i:number,key:keyof Entry,value:string){setEntries(v=>v.map((e,n)=>n===i?{...e,[key]:value}:e));setCalculated(false)}
 async function loadImage(src:string){return await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=src})}
 function roundedBox(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number,fill:string,stroke:string){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke()}
 function header(ctx:CanvasRenderingContext2D,title:string,x:number,y:number,w:number){ctx.fillStyle="#006837";ctx.fillRect(x,y,w,44);ctx.fillStyle="#fff";ctx.font="700 18px Arial";ctx.fillText(title,x+22,y+29)}
 async function buildReport(){
  const canvas=document.createElement("canvas");canvas.width=1240;canvas.height=1754;const c=canvas.getContext("2d");if(!c)throw new Error("Unable to create report");
  const GREEN="#006837",DARK="#0f172a",BORDER="#cbd5e1",LIGHT="#eef2f5";c.fillStyle="#fff";c.fillRect(0,0,1240,1754);
  c.beginPath();c.moveTo(1025,0);c.lineTo(1240,0);c.lineTo(1240,185);c.closePath();c.fillStyle="#062f28";c.fill();
  c.beginPath();c.moveTo(1075,0);c.lineTo(1240,0);c.lineTo(1240,135);c.closePath();c.fillStyle="#00853f";c.fill();
  c.beginPath();c.moveTo(1135,0);c.lineTo(1240,0);c.lineTo(1240,78);c.closePath();c.fillStyle="#16a34a";c.fill();
  c.beginPath();c.moveTo(0,1575);c.lineTo(0,1754);c.lineTo(180,1754);c.closePath();c.fillStyle="#062f28";c.fill();
  c.beginPath();c.moveTo(0,1630);c.lineTo(0,1754);c.lineTo(130,1754);c.closePath();c.fillStyle="#16a34a";c.fill();
  c.beginPath();c.moveTo(48,1685);c.lineTo(90,1754);c.lineTo(190,1754);c.closePath();c.fillStyle="#dc2626";c.fill();
  try{const logo=await loadImage("/soh-logo.jpg");const scale=Math.min(320/logo.width,140/logo.height);c.drawImage(logo,52,28,logo.width*scale,logo.height*scale)}catch{c.font="800 34px Arial";c.fillStyle=GREEN;c.fillText("S.O.H CONSULTS",55,90)}
  c.strokeStyle="#94a3b8";c.beginPath();c.moveTo(895,52);c.lineTo(895,126);c.stroke();c.font="italic 24px Arial";c.fillStyle=DARK;c.fillText("Your Admission",920,78);c.fillText("Journey, Our Priority",920,108);c.fillStyle=GREEN;c.fillRect(920,132,74,4);
  c.font="800 45px Arial";c.fillStyle=DARK;c.fillText("FUOYE SCREENING SCORE REPORT",55,218);c.font="400 18px Arial";c.fillStyle="#334155";c.fillText("F O R   G U I D A N C E   P U R P O S E S   O N L Y",57,255);c.fillStyle=GREEN;c.fillRect(55,276,1130,4);
  roundedBox(c,55,302,1130,220,10,"#fff",BORDER);header(c,"CANDIDATE INFORMATION",55,302,1130);
  const info=[["Candidate Name:",candidateName.trim()],["Selected Course:",programme],["Report Date:",new Date().toLocaleString("en-NG",{dateStyle:"medium",timeStyle:"short"})],["Generated By:","S.O.H CONSULTS"]];let iy=385;
  info.forEach(([a,b])=>{c.font="700 18px Arial";c.fillStyle=DARK;c.fillText(a,78,iy);c.font="400 18px Arial";c.fillText(b,290,iy);iy+=38});
  roundedBox(c,55,550,548,340,10,"#fff",BORDER);header(c,"SCREENING BREAKDOWN",55,550,548);
  const rows=[["JAMB Score",jambNum+"/400"],["JAMB Points (60%)",jambPoints.toFixed(2)+" / 60"],["O-Level Points",olevelPoints+" / 30"],["Sitting",sittings===1?"One sitting":"Two sittings"],["Sitting Bonus",bonus+" points"]];let ry=635;
  rows.forEach(([a,b])=>{c.font="700 17px Arial";c.fillStyle=DARK;c.fillText(a,78,ry);c.font="400 17px Arial";c.fillText(b,350,ry);c.strokeStyle="#e2e8f0";c.beginPath();c.moveTo(75,ry+14);c.lineTo(580,ry+14);c.stroke();ry+=50});
  roundedBox(c,628,550,557,340,10,"#fff",BORDER);header(c,"O-LEVEL RESULTS",628,550,557);c.fillStyle=LIGHT;c.fillRect(628,594,557,42);c.font="700 16px Arial";c.fillStyle=DARK;c.fillText("Subject",655,621);c.textAlign="center";c.fillText("Grade",1040,621);c.fillText("Point",1140,621);c.textAlign="left";let oy=675;
  entries.forEach((e,i)=>{c.font="400 16px Arial";c.fillStyle=DARK;c.fillText((i+1)+".  "+e.subject,655,oy);c.textAlign="center";c.fillText(e.grade,1040,oy);c.fillText(String(gradePoints[e.grade]||0),1140,oy);c.textAlign="left";c.strokeStyle="#e2e8f0";c.beginPath();c.moveTo(645,oy+13);c.lineTo(1170,oy+13);c.stroke();oy+=47});
  roundedBox(c,55,925,1130,250,10,"#f0fdf4","#bbf7d0");header(c,"FUOYE SCREENING SCORE",55,925,1130);c.textAlign="center";c.font="800 72px Arial";c.fillStyle=GREEN;c.fillText(total.toFixed(2)+" / 100",620,1045);c.font="400 20px Arial";c.fillStyle=DARK;c.fillText("JAMB "+jambPoints.toFixed(2)+"/60  +  O-Level "+olevelPoints+"/30  +  Sitting Bonus "+bonus,620,1095);c.textAlign="left";
  roundedBox(c,55,1210,1130,250,10,"#f8fafc","#e2e8f0");c.font="800 19px Arial";c.fillStyle=DARK;c.fillText("ⓘ  IMPORTANT NOTES",78,1250);c.font="400 16px Arial";c.fillText("• This report is generated by S.O.H CONSULTS for guidance and self-screening purposes only.",95,1300);c.fillText("• It is not an official FUOYE screening result, admission letter, or guarantee of admission.",95,1340);c.fillText("• Candidates should verify current programme requirements and admission information with FUOYE/JAMB.",95,1380);
  c.font="italic 18px Georgia";c.fillStyle=GREEN;c.fillText("Education  •  Opportunity  •  A Greater You",165,1686);c.strokeStyle=GREEN;c.beginPath();c.moveTo(745,1655);c.lineTo(745,1714);c.stroke();c.font="400 15px Arial";c.fillStyle=DARK;c.fillText("WhatsApp: 0818 214 1088",775,1680);c.fillText("Oluyepeadetayo@gmail.com",775,1706);c.font="400 14px Arial";c.fillText("Page 1 of 1",1090,1693);return canvas
 }
 async function reportImage(){try{const c=await buildReport();const a=document.createElement("a");a.download="FUOYE_Screening_Report_"+candidateName.trim().replace(/[^a-z0-9]+/gi,"_")+".jpg";a.href=c.toDataURL("image/jpeg",.97);a.click()}catch{alert("Unable to generate the JPG report.")}}
 async function reportPdf(){try{const c=await buildReport();const p=new jsPDF({orientation:"portrait",unit:"mm",format:"a4",compress:true});p.addImage(c.toDataURL("image/jpeg",.97),"JPEG",0,0,210,297,undefined,"FAST");p.save("FUOYE_Screening_Report_"+candidateName.trim().replace(/[^a-z0-9]+/gi,"_")+".pdf")}catch{alert("Unable to generate the PDF report.")}}
 return <main style={{maxWidth:900,margin:"0 auto",padding:"32px 18px 70px"}}>
  <section style={{background:"#087443",color:"white",padding:28,borderRadius:20,marginBottom:22}}><b>S.O.H CONSULTS</b><h1 style={{fontSize:"clamp(28px,5vw,44px)",margin:"8px 0"}}>FUOYE Screening Score Calculator</h1><p>JAMB + five relevant O'Level grades + sitting bonus.</p></section>
  <section style={{background:"#fff",border:"1px solid #ddd",borderRadius:18,padding:22}}>
   <b>Candidate Name</b><input type="text" value={candidateName} onChange={e=>{setCandidateName(e.target.value);setCalculated(false)}} placeholder="Enter candidate full name" style={input}/><div style={{height:18}}/><b>Programme / Course Applying For</b><select value={programme} onChange={e=>{setProgramme(e.target.value);setCalculated(false)}} style={input}><option value="">Select FUOYE programme</option>{programmes.map(p=><option key={p} value={p}>{p}</option>)}</select><div style={{height:18}}/><b>JAMB Score (0-400)</b><input type="number" min="0" max="400" value={jamb} onChange={e=>{setJamb(e.target.value);setCalculated(false)}} placeholder="e.g. 250" style={input}/><p style={{fontWeight:700,color:"#087443"}}>JAMB points: {jambPoints.toFixed(2)} / 60</p>
   <h2>O'Level sittings</h2><div style={{display:"flex",gap:12,flexWrap:"wrap",marginBottom:24}}>{[1,2].map(n=><button key={n} onClick={()=>{setSittings(n as 1|2);setCalculated(false)}} style={{...button,background:sittings===n?"#087443":"#eef6f1",color:sittings===n?"white":"#087443"}}>{n===1?"One sitting (+10)":"Two sittings (+6)"}</button>)}</div>
   <h2>Five relevant O'Level subjects</h2><p>Select five subjects relevant to your intended programme. Duplicate subjects are blocked.</p>
   {entries.map((e,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:10,marginBottom:10}}><select value={e.subject} onChange={x=>update(i,"subject",x.target.value)} style={input}><option value="">Select subject {i+1}</option>{subjects.filter(s=>s===e.subject||!entries.some(x=>x.subject===s)).map(s=><option key={s}>{s}</option>)}</select><select value={e.grade} onChange={x=>update(i,"grade",x.target.value)} style={input}><option value="">Grade</option>{grades.map(g=><option key={g} value={g}>{g} ({gradePoints[g]} pts)</option>)}</select></div>)}
   <p><b>O'Level points: {olevelPoints} / 30</b></p><button disabled={!complete} onClick={()=>setCalculated(true)} style={{...button,width:"100%",background:complete?"#087443":"#aaa",color:"white"}}>Calculate Screening Score</button>
  </section>
  {calculated&&<section style={{marginTop:22,border:"2px solid #087443",borderRadius:18,padding:24,background:"#f5fbf7"}}><h2>Your FUOYE Screening Score</h2><p><b>{programme}</b></p><div style={{fontSize:48,fontWeight:900,color:"#087443"}}>{total.toFixed(2)}<span style={{fontSize:22}}>/100</span></div><p>JAMB: <b>{jambPoints.toFixed(2)}/60</b> | O'Level: <b>{olevelPoints}/30</b> | Sitting bonus: <b>{bonus}</b></p><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button onClick={reportPdf} style={{...button,background:"#087443",color:"white"}}>Download PDF Report</button><button onClick={reportImage} style={{...button,background:"white",color:"#087443",border:"1px solid #087443"}}>Download Image Report</button></div><p style={{fontSize:13,color:"#555"}}>This is a screening estimate and does not guarantee admission.</p></section>}
  <section style={{marginTop:30}}><SiteContact/></section>
 </main>
}
const input:React.CSSProperties={width:"100%",boxSizing:"border-box",padding:"13px 12px",border:"1px solid #cfd8d3",borderRadius:10,fontSize:16,background:"#fff",marginTop:8};
const button:React.CSSProperties={border:0,borderRadius:10,padding:"13px 18px",fontWeight:800,cursor:"pointer"};
