"use client";
import FounderProfile from "./FounderProfile";

import { useEffect, useMemo, useState } from "react";
import type { CmsSection, SiteSettings } from "../lib/site-manager";
import CmsSwipeGallery from "./CmsSwipeGallery";

type Update = { id:string; title:string; summary:string; category:string; date:string; slug:string; updatedAt:string };
const fallbackNav=[{title:"Home",link:"/"},{title:"Updates",link:"/updates"},{title:"Opportunities",link:"/opportunities"},{title:"Deadlines",link:"/deadlines"},{title:"Guides",link:"/guides"},{title:"Screening Calculator",link:"/screening-calculator"},{title:"CGPA Simulator / Planner",link:"/cgpa-calculator"}];
const fallbackServices=[{id:"admission",title:"Admission Support",description:"Post-UTME, Direct Entry, part-time and other applications.",link:"/updates",image:""},{id:"jamb",title:"JAMB Services",description:"CAPS guidance, O’Level uploads, results and admission letters.",link:"/guides",image:""},{id:"docs",title:"Documentation",description:"Certificates, result checking and academic documents.",link:"/guides",image:""},{id:"consult",title:"Educational Consultation",description:"Personal guidance on programmes and admission choices.",link:"#contact",image:""},{id:"exam",title:"Examination Support",description:"WAEC, NECO and NABTEB-related assistance.",link:"/updates",image:""},{id:"opps",title:"Opportunities",description:"Find educational opportunities and relevant updates.",link:"/opportunities",image:""}];
const fallbackTools=[{id:"screening",title:"Screening Calculator",description:"Calculate your Post-UTME screening or admission aggregate.",link:"/screening-calculator",image:""},{id:"cgpa",title:"CGPA Simulator / Planner",description:"Calculate your CGPA and plan towards a target CGPA.",link:"/cgpa-calculator",image:""}];
function grid(layout:string){if(layout==="grid-4")return"grid-cols-1 sm:grid-cols-2 lg:grid-cols-4";if(layout==="grid-3")return"grid-cols-1 sm:grid-cols-2 lg:grid-cols-3";if(layout==="grid-2")return"grid-cols-1 md:grid-cols-2";if(layout==="list")return"grid-cols-1";if(layout==="split-left"||layout==="split-right")return"grid-cols-1 md:grid-cols-2";return"grid-cols-1 sm:grid-cols-2 lg:grid-cols-3"}
function pad(spacing?:string){return spacing==="compact"?"py-5":spacing==="spacious"?"py-14":"py-9"}
function responsive(s:CmsSection){return `${s.mobileVisible===false?"hidden sm:block":""} ${s.tabletVisible===false?"sm:hidden lg:block":""} ${s.desktopVisible===false?"lg:hidden":""}`}
function SectionShell({s,children}:{s:CmsSection;children:React.ReactNode}){const bg=s.background&&s.background!=="default"?s.background:"transparent";return <section id={s.id} className={`${responsive(s)} ${pad(s.spacing)}`} style={{background:bg}}><div className={s.layout==="full"?"w-full":"mx-auto max-w-[1440px] px-4 sm:px-7 lg:px-10"}>{children}</div></section>}
function Cards({s,items}:{s:CmsSection;items:CmsSection["items"]}){return <div className={`grid gap-4 ${grid(s.layout)}`}>{items.map(i=><article key={i.id} className="overflow-hidden rounded-2xl border border-[#e2e5dc] bg-white shadow-sm">{i.image&&<img src={i.image} alt="" className="h-44 w-full object-cover"/>}<div className="p-5"><h3 className="font-black">{i.title}</h3>{i.description&&<p className="mt-2 text-sm leading-6 text-[#52615a]">{i.description}</p>}{i.link&&<a href={i.link} className="mt-4 inline-block text-sm font-bold text-[#075738] hover:underline">Learn more →</a>}</div></article>)}</div>}
export default function CmsHomepage({settings}:{settings:SiteSettings}){const[menu,setMenu]=useState(false);const[updates,setUpdates]=useState<Update[]>([]);const wa=`https://wa.me/${settings.whatsapp}`;const nav=settings.navigation?.length?settings.navigation:fallbackNav.map((x,i)=>({id:`nav-${i}`,title:x.title,description:"",link:x.link,image:""}));useEffect(()=>{fetch("/api/public/updates",{cache:"no-store"}).then(r=>r.ok?r.json():[]).then((x:Update[])=>setUpdates(x.sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt)).slice(0,settings.latestUpdatesCount))).catch(()=>setUpdates([]))},[settings.latestUpdatesCount]);const sections=useMemo(()=>settings.sections.filter(s=>s.visible),[settings.sections]);const render=(s:CmsSection)=>{if(s.type==="hero")return <section key={s.id} id={s.id} className={`${responsive(s)} bg-gradient-to-br from-[#043b29] via-[#06452f] to-[#07583b] text-white`}><div className="mx-auto grid max-w-[1440px] items-center gap-7 px-4 py-10 sm:px-7 lg:grid-cols-[1.1fr_.9fr] lg:px-10 lg:py-16"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#efc46e]">{settings.heroEyebrow}</p><h1 className="mt-3 text-4xl font-black leading-tight sm:text-5xl lg:text-6xl">{settings.heroTitle}<br/><span className="text-[#efc46e]">{settings.heroAccent}</span></h1><p className="mt-4 max-w-2xl leading-7 text-[#edf5ef]">{settings.heroDescription}</p><div className="mt-6 flex flex-wrap gap-2"><a href="/opportunities" className="rounded-xl bg-[#efc46e] px-5 py-3 text-sm font-black text-[#102720]">Explore Opportunities →</a><a href="/screening-calculator" className="rounded-xl border border-white px-5 py-3 text-sm font-bold">Screening Calculator</a><a href="/cgpa-calculator" className="rounded-xl border border-white px-5 py-3 text-sm font-bold">CGPA Calculator</a></div></div><img src="/hero-students.png" alt="Students using S.O.H CONSULTS" className="mx-auto max-h-[390px] w-full object-contain"/></div></section>;
if(s.type==="updates")return <SectionShell key={s.id} s={s}><div className="mb-5 flex items-end justify-between gap-3"><div><h2 className="text-2xl font-black">{s.title}</h2><p className="text-sm text-[#52615a]">{s.description}</p></div><a href="/updates" className="shrink-0 text-sm font-bold text-[#075738]">View all →</a></div><div className={`grid gap-4 ${grid(s.layout)}`}>{updates.map(u=><article key={u.id} className="min-w-0 rounded-2xl border border-[#e2e5dc] bg-white p-5 shadow-sm"><p className="text-xs font-bold text-[#087245]">{u.category} · {u.date}</p><h3 className="mt-2 break-words font-black leading-snug">{u.title}</h3><p className="mt-2 line-clamp-3 text-sm leading-6 text-[#52615a]">{u.summary}</p><a href={`/updates/${u.slug}`} className="mt-4 inline-block text-sm font-bold text-[#075738]">Read more →</a></article>)}</div></SectionShell>;
if(s.type==="gallery")return <SectionShell key={s.id} s={s}><h2 className="text-2xl font-black">{s.title}</h2>{s.description&&<p className="mb-5 mt-1 max-w-3xl text-sm leading-6 text-[#52615a]">{s.description}</p>}<CmsSwipeGallery items={s.items}/></SectionShell>;
if(s.type==="tools"){const items=s.items.length?s.items:fallbackTools;return <SectionShell key={s.id} s={s}><h2 className="text-2xl font-black">{s.title}</h2><p className="mb-5 mt-1 text-sm text-[#52615a]">{s.description}</p><Cards s={s} items={items}/></SectionShell>}if(s.type==="services"){const items=s.items.length?s.items:fallbackServices;return <SectionShell key={s.id} s={s}><h2 className="text-2xl font-black">{s.title}</h2><p className="mb-5 mt-1 text-sm text-[#52615a]">{s.description}</p><Cards s={s} items={items}/></SectionShell>}if(s.type==="contact")return <SectionShell key={s.id} s={s}><div className="rounded-2xl bg-[#06452f] p-7 text-white sm:p-10"><h2 className="text-3xl font-black">{s.title}</h2><p className="mt-2 max-w-2xl text-[#e6f0e9]">{s.description}</p><a href={`${wa}?text=${encodeURIComponent("Hello S.O.H CONSULTS, I need guidance.")}`} className="mt-5 inline-block rounded-xl bg-[#efc46e] px-5 py-3 font-black text-[#102720]">Chat on WhatsApp →</a></div></SectionShell>;if(s.type==="founder")return <SectionShell key={s.id} s={s}><FounderProfile/></SectionShell>;const items=s.items;return <SectionShell key={s.id} s={s}><h2 className="text-2xl font-black">{s.title}</h2>{s.description&&<p className="mb-5 mt-1 max-w-3xl text-sm leading-6 text-[#52615a]">{s.description}</p>}{items.length?<Cards s={s} items={items}/>:null}</SectionShell>};return <main className="min-h-screen bg-[#faf8f2] text-[#102720]"><header className="sticky top-0 z-50 border-b border-[#e7e9df] bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-4 py-2 sm:px-7 lg:px-10"><a href="/"><img src="/soh-logo.jpg" alt={settings.siteName} className="h-12 w-auto sm:h-14"/></a><nav className="hidden items-center gap-5 lg:flex">{nav.map(n=><a key={n.id} href={n.link} className="text-sm font-bold hover:text-[#087245]">{n.title}</a>)}</nav><div className="flex gap-2"><a href={wa} className="hidden rounded-xl bg-[#075738] px-4 py-2.5 text-sm font-bold text-white sm:block">WhatsApp Us</a><button onClick={()=>setMenu(!menu)} className="rounded-lg border px-3 py-2 text-xl lg:hidden" aria-label="Toggle menu">{menu?"×":"☰"}</button></div></div>{menu&&<nav className="grid grid-cols-1 gap-1 border-t bg-white p-4 sm:grid-cols-2 lg:hidden">{nav.map(n=><a key={n.id} href={n.link} onClick={()=>setMenu(false)} className="rounded-lg px-3 py-2 text-sm font-semibold hover:bg-[#edf5ee]">{n.title}</a>)}</nav>}</header>{sections.map(render)}<footer className="mt-6 bg-[#032c20] px-4 py-8 text-center text-sm text-[#dcece3]">{settings.footerText||`${settings.siteName} · ${settings.tagline}`}</footer></main>}
