import Link from "next/link";
import { redirect } from "next/navigation";
import { isAdmin } from "../../../lib/admin-auth";

const modules=[
 {title:"Opportunities Manager",note:"Scholarships, internships, jobs, NYSC, grants and fellowships.",href:"/admin/opportunities",state:"Manager ready"},
 {title:"Forms Manager",note:"Control admission forms and open/closed programme status from one place.",href:"/admin/forms",state:"Workspace"},
 {title:"LASU Calculator Control",note:"Protect the working calculator while preparing admin-managed notices and rules.",href:"/admin/calculator",state:"Workspace"},
 {title:"Media Library",note:"Central management point for update images, flyers and PDF attachments.",href:"/admin/media",state:"Workspace"},
 {title:"Content Calendar",note:"Use deadline intelligence to plan admission, scholarship and registration content.",href:"/admin/calendar",state:"Workspace"},
 {title:"SEO Control",note:"Review public content structure, titles and discoverability from the content workflow.",href:"/admin/seo",state:"Workspace"},
 {title:"Enquiries & Leads",note:"Website enquiries and WhatsApp source tracking.",href:"/admin/enquiries",state:"Workspace"},
 {title:"Analytics",note:"Visitor, CTA, search and Ask S.O.H reporting centre.",href:"/admin/analytics",state:"Workspace"},
 {title:"System Settings",note:"Business contact details and global website settings.",href:"/admin/settings",state:"Workspace"},
];
export default async function AdminModulesPage(){if(!(await isAdmin()))redirect("/admin/updates");return <main className="min-h-screen bg-gray-50 text-gray-950"><header className="border-b bg-white"><div className="mx-auto flex max-w-[1450px] flex-wrap items-center justify-between gap-4 px-5 py-5"><div><p className="text-[11px] font-black uppercase tracking-[.22em] text-green-700">S.O.H CONSULTS · PRIVATE</p><h1 className="text-2xl font-black">Operations Modules</h1><p className="mt-1 text-sm text-gray-500">Manage the routine operations of S.O.H CONSULTS from one private control centre.</p></div><div className="flex gap-2"><Link href="/admin" className="rounded-xl border px-4 py-2 text-sm font-black">Dashboard</Link><Link href="/admin/updates" className="rounded-xl bg-green-700 px-4 py-2 text-sm font-black text-white">Manage Updates</Link></div></div></header><section className="mx-auto max-w-[1450px] px-5 py-7"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{modules.map(m=><Link key={m.title} href={m.href} className="group rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-green-300 hover:shadow-md"><div className="flex items-start justify-between gap-3"><h2 className="text-lg font-black group-hover:text-green-800">{m.title}</h2><span className="shrink-0 rounded-full bg-green-50 px-2.5 py-1 text-[10px] font-black uppercase text-green-700">{m.state}</span></div><p className="mt-3 text-sm font-medium leading-6 text-gray-600">{m.note}</p><p className="mt-5 text-sm font-black text-green-700">Manage →</p></Link>)}</div><div className="mt-6 rounded-2xl border border-green-200 bg-green-50 p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-green-700">Management architecture</p><h2 className="mt-1 text-xl font-black">Every module now has a private management destination</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-gray-700">Opportunities is the first data workspace connected to current records. The remaining workspaces are being introduced safely before write controls are connected to persistent storage, so existing production data stays protected.</p></div></section></main>}
