"use client";
import { useMemo,useState } from "react";
import Link from "next/link";
const programmes=["Cooperative and Business Management","Cooperative Management and Rural Development","Agricultural Economics","Agricultural Extension and Rural Sociology","Home and Hotel Management","Catering, Hotel, and Tourism Management","Child Development and Family Studies","Clothing and Textiles","Food Nutrition and Dietetics","Animal Production","Crop Production","Crop Protection","Crop Improvement and Genetics","Soil and Farm Mechanisation","Fisheries Production","Forestry and Wildlife","Agricultural Engineering","Civil Engineering","Computer Engineering","Electrical and Electronics Engineering","Mechanical Engineering","Architecture","Building Technology","Estate Management","Quantity Surveying","Fine And Applied Arts","Urban And Regional Planning","Anatomy","Biochemistry","Pharmacology","Physiology","Nursing","Medical Laboratory Science","Forensic Science","Medicine and Surgery","Accounting","Taxation","Banking and Finance","Business Administration","Industrial Relations and Personnel Management","Public Administration","Transport Planning and Management","English","Performing Arts","Music","History and Diplomatic Studies","French","Yoruba","Linguistics","Christian Religious Studies","Islamic Religious Studies","Religion and Science","Philosophy","Adult Education","Business Administration Education","Christian Religious Studies Education","Economics Education","English Education","French Education","Geography Education","History Education","Islamic Religious Studies Education","Political Science Education","Social Studies Education","Yoruba Education","Early Child Education","Guidance and Counselling Education","Nursery and Primary Education","Accounting Education","Business Education","Educational Management","Secretarial Administration Education","Health Education","Sports Science Education","Biology Education","Chemistry Education","Computer Science Education","Integrated Science Education","Mathematics Education","Physics Education","Vocational and Technical Education","Law","Pharmacy","Chemistry","Industrial Chemistry","Computer Science","Applied Geophysics","Geology","Geography and Regional Planning","Mathematics","Microbiology","GeoPhysics","Physics with Electronics","Physics","Applied Zoology","Botany","Plant Science","Statistics","Economics","Library and Information Science","Mass Communication","Political Science","Psychology","Criminology and Security Studies","Industrial & Labour Relations","Sociology"];

export default function OOUCalculator(){
 const [name,setName]=useState(""); const [programme,setProgramme]=useState(""); const [jamb,setJamb]=useState(""); const [putme,setPutme]=useState("");
 const j=Math.max(0,Math.min(400,Number(jamb)||0)); const p=Math.max(0,Math.min(100,Number(putme)||0));
 const jambPart=j*0.15, putmePart=p*0.4, aggregate=jambPart+putmePart;
 const requiredPutme=useMemo(()=>j?Math.max(0,(40-jambPart)/0.4):0,[j,jambPart]);
 const hasPutme=putme!=="";
 return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">
  <header className="overflow-hidden rounded-3xl bg-gradient-to-br from-green-700 via-green-600 to-emerald-500 p-6 text-white shadow-xl sm:p-8">
   <nav className="flex flex-wrap gap-2 text-sm font-bold"><Link className="rounded-full bg-white px-4 py-2 text-green-800" href="/">Home</Link><Link className="rounded-full bg-white/15 px-4 py-2" href="/screening-calculator">Screening Calculators</Link><Link className="rounded-full bg-white/15 px-4 py-2" href="/updates">Latest Updates</Link><Link className="rounded-full bg-white/15 px-4 py-2" href="/opportunities">Opportunities</Link></nav>
   <p className="mt-7 text-sm font-black uppercase tracking-widest text-green-100">S.O.H CONSULTS</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">OOU Aggregate Calculator</h1><p className="mt-3 max-w-3xl text-green-50">Estimate your position before OOU Post-UTME, then enter your actual Post-UTME score when available to see your live final aggregate.</p>
  </header>
  <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7">
   <h2 className="text-xl font-black">Candidate Information</h2><label className="mt-5 block text-sm font-bold">Candidate Name</label><input className="mt-2 w-full rounded-xl border border-slate-300 p-3" value={name} onChange={e=>setName(e.target.value)} placeholder="Enter candidate full name"/>
   <label className="mt-5 block text-sm font-bold">Programme</label><select className="mt-2 w-full rounded-xl border border-slate-300 p-3" value={programme} onChange={e=>setProgramme(e.target.value)}><option value="">Select programme</option>{programmes.map(x=><option key={x}>{x}</option>)}</select><div className="mt-7 border-t border-slate-200 pt-6"><h2 className="text-xl font-black">UTME Score</h2><label className="mt-4 block text-sm font-bold">JAMB Score (0-400)</label><input type="number" min="0" max="400" className="mt-2 w-full rounded-xl border border-slate-300 p-3" value={jamb} onChange={e=>setJamb(e.target.value)} placeholder="e.g. 250"/></div>{j>0&&j<160&&<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">OOU states 160 as the general minimum UTME score for Post-UTME eligibility. Some programmes may require a higher score.</p>}
   <div className="mt-7 border-t border-slate-200 pt-6"><h2 className="text-xl font-black">Post-UTME Score</h2><p className="mt-1 text-sm text-slate-600">Before the exam, leave this empty. After your result is released, enter the score to calculate your final aggregate.</p><input type="number" min="0" max="100" className="mt-3 w-full rounded-xl border border-slate-300 p-3" value={putme} onChange={e=>setPutme(e.target.value)} placeholder="Enter when available, e.g. 65"/></div>
   <div className="mt-7 border-t border-slate-200 pt-6"><h2 className="text-lg font-black">Live Aggregate</h2><div className="mt-3 grid grid-cols-3 gap-2"><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs font-bold text-slate-500">UTME</span><p className="mt-1 font-black">{jambPart.toFixed(2)}/60</p></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs font-bold text-slate-500">POST-UTME</span><p className="mt-1 font-black">{hasPutme?putmePart.toFixed(2):"0.00"}/40</p></div><div className="rounded-xl bg-green-50 p-3"><span className="text-xs font-bold text-green-700">{hasPutme?"AGGREGATE":"UTME POSITION"}</span><p className="mt-1 font-black text-green-700">{(hasPutme?aggregate:jambPart).toFixed(2)}/100</p></div></div>
   {!hasPutme&&j>0&&<div className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm"><b>Before Post-UTME:</b> At the 40% benchmark, you would need approximately <b>{requiredPutme>100?"more than 100":requiredPutme.toFixed(2)}</b>{requiredPutme<=100?" / 100 in Post-UTME":""} based on this formula. This is a planning estimate, not an admission decision.</div>}
   {hasPutme&&<div className={"mt-4 rounded-2xl p-4 text-sm font-bold "+(aggregate>=40?"bg-green-50 text-green-800":"bg-red-50 text-red-700")}>{aggregate>=40?"Your calculated aggregate meets the 40% benchmark.":"Your calculated aggregate is below the 40% benchmark."}</div>}
  </div></section>
  <aside className="space-y-5"><section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><p className="text-xs font-black uppercase tracking-wider text-green-700">How the checker works</p><h2 className="mt-2 text-xl font-black">OOU screening calculation</h2><div className="mt-4 space-y-3 text-sm text-slate-600"><p><b className="text-slate-900">1. UTME:</b> contributes up to 60 points.</p><p><b className="text-slate-900">2. Post-UTME:</b> contributes up to 40 points.</p><p><b className="text-slate-900">3. Aggregate:</b> both contributions are added to produce a score out of 100.</p></div></section><section className="rounded-3xl bg-green-700 p-5 text-white"><p className="text-xs font-black uppercase tracking-wider text-green-100">S.O.H CONSULTS</p><h2 className="mt-2 text-xl font-black">Need admission guidance?</h2><p className="mt-2 text-sm text-green-50">Get help with screening, admission requirements and application guidance.</p><a className="mt-4 inline-block rounded-xl bg-white px-4 py-3 text-sm font-black text-green-800" href="https://wa.me/2348182141088">Chat on WhatsApp</a></section></aside></div>
  <section className="mt-8 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><p className="text-xs font-black uppercase tracking-wider text-green-700">OOU Admission Guide</p><h2 className="mt-2 text-2xl font-black">How to calculate your OOU aggregate score</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><b>1. UTME contribution</b><p className="mt-2 text-sm text-slate-600">(UTME score × 60) ÷ 400.</p></div><div className="rounded-2xl bg-slate-50 p-4"><b>2. Post-UTME contribution</b><p className="mt-2 text-sm text-slate-600">(Post-UTME score × 40) ÷ 100.</p></div><div className="rounded-2xl bg-green-50 p-4"><b>3. Final aggregate</b><p className="mt-2 text-sm text-slate-600">Add both contributions. The reference benchmark is 40%.</p></div></div><h2 className="mt-7 text-lg font-black">OOU Aggregate Calculator FAQ</h2><div className="mt-3 space-y-2"><details className="rounded-xl bg-slate-50 px-4 py-3"><summary className="cursor-pointer text-sm font-bold">Can I use this before writing Post-UTME?</summary><p className="mt-2 text-sm text-slate-600">Yes. Enter your UTME score and the calculator shows your current UTME contribution plus the Post-UTME score needed to reach the reference benchmark.</p></details><details className="rounded-xl bg-slate-50 px-4 py-3"><summary className="cursor-pointer text-sm font-bold">What happens after I get my Post-UTME score?</summary><p className="mt-2 text-sm text-slate-600">Enter it and the Live Aggregate immediately combines both components.</p></details></div></section>
 </div></main>
}