import type { QueuedStory, QueueStatus } from "./news-queue";

const SUPABASE_URL=process.env.SUPABASE_URL;
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const SYSTEM_PREFIX="S.O.H System:";
const TRASH_PREFIX="S.O.H Trash:";

function headers(prefer?:string){if(!SUPABASE_URL||!SERVICE_KEY)throw new Error("Supabase environment variables are not configured.");return{apikey:SERVICE_KEY,...(SERVICE_KEY.startsWith("eyJ")?{Authorization:`Bearer ${SERVICE_KEY}`} :{}),"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})};}
async function rawStory(id:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/news_queue?select=*&id=eq.${encodeURIComponent(id)}&limit=1`,{headers:headers(),cache:"no-store"});if(!r.ok)throw new Error("Unable to load update.");return((await r.json()) as QueuedStory[])[0]||null;}
async function patch(id:string,values:Partial<QueuedStory>){const r=await fetch(`${SUPABASE_URL}/rest/v1/news_queue?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:headers("return=representation"),body:JSON.stringify({...values,updated_at:new Date().toISOString()}),cache:"no-store"});if(!r.ok)throw new Error(`Unable to update recovery record (${r.status}).`);return((await r.json()) as QueuedStory[])[0]||null;}
async function systemRecord(kind:"history"|"audit",title:string,payload:unknown,storyId:string){const now=new Date().toISOString();const id=crypto.randomUUID();const row={id,source_name:`${SYSTEM_PREFIX}${kind}:${storyId}`,source_url:`system:${kind}:${storyId}:${id}`,source_published_at:null,title,institution:"Private admin record",category:`Admin ${kind}`,summary:kind==="audit"?title:"Previous update version",details:JSON.stringify(payload),deadline:null,deadline_iso:null,image_url:null,document_url:null,document_name:null,official_source_name:null,official_source_url:null,status:"archived",created_at:now,updated_at:now};const r=await fetch(`${SUPABASE_URL}/rest/v1/news_queue`,{method:"POST",headers:headers("return=minimal"),body:JSON.stringify(row),cache:"no-store"});if(!r.ok)throw new Error(`Unable to save ${kind} record (${r.status}).`);}
export function isSystemStory(story:QueuedStory){return story.source_name.startsWith(SYSTEM_PREFIX);}
export function isTrashedStory(story:QueuedStory){return story.source_name.startsWith(TRASH_PREFIX);}
export function visibleAdminStories(stories:QueuedStory[]){return stories.filter(s=>!isSystemStory(s)&&!isTrashedStory(s));}
export async function recordVersion(story:QueuedStory,action="edited"){await systemRecord("history",story.title,{action,snapshot:story},story.id);}
export async function recordAudit(action:string,story:Pick<QueuedStory,"id"|"title">,details=""){await systemRecord("audit",`${action}: ${story.title}`,{action,story_id:story.id,title:story.title,details,at:new Date().toISOString()},story.id);}
export async function moveStoryToTrash(id:string){const story=await rawStory(id);if(!story||isSystemStory(story)||isTrashedStory(story))return null;await recordVersion(story,"moved_to_trash");const meta=encodeURIComponent(JSON.stringify({source_name:story.source_name,status:story.status}));const updated=await patch(id,{source_name:`${TRASH_PREFIX}${meta}`,status:"archived"});if(updated)await recordAudit("Moved to Trash",updated,"Recoverable for 30 days; permanent deletion remains protected.");return updated;}
export async function restoreStoryFromTrash(id:string){const story=await rawStory(id);if(!story||!isTrashedStory(story))return null;let source_name="S.O.H CONSULTS";let status:QueueStatus="draft";try{const meta=JSON.parse(decodeURIComponent(story.source_name.slice(TRASH_PREFIX.length))) as {source_name?:string;status?:QueueStatus};source_name=meta.source_name||source_name;status=meta.status||status;}catch{}
const restored=await patch(id,{source_name,status});if(restored)await recordAudit("Restored from Trash",restored,`Restored to ${status}.`);return restored;}
export async function listTrash(){const r=await fetch(`${SUPABASE_URL}/rest/v1/news_queue?select=*&source_name=like.${encodeURIComponent(TRASH_PREFIX+"*")}&order=updated_at.desc`,{headers:headers(),cache:"no-store"});if(!r.ok)throw new Error("Unable to load Trash.");return r.json() as Promise<QueuedStory[]>;}
export type HistoryEntry={id:string;story_id:string;title:string;created_at:string;action:string;snapshot:QueuedStory};
export type AuditEntry={id:string;story_id:string;title:string;created_at:string;action:string;details:string};
async function listSystem(kind:"history"|"audit"){const prefix=`${SYSTEM_PREFIX}${kind}:`;const r=await fetch(`${SUPABASE_URL}/rest/v1/news_queue?select=*&source_name=like.${encodeURIComponent(prefix+"*")}&order=created_at.desc&limit=250`,{headers:headers(),cache:"no-store"});if(!r.ok)throw new Error(`Unable to load ${kind}.`);return r.json() as Promise<QueuedStory[]>;}
export async function listHistory():Promise<HistoryEntry[]>{return(await listSystem("history")).flatMap(row=>{try{const p=JSON.parse(row.details) as {action:string;snapshot:QueuedStory};return[{id:row.id,story_id:row.source_name.split(":").pop()||"",title:row.title,created_at:row.created_at,action:p.action,snapshot:p.snapshot}];}catch{return[];}});}
export async function listAudit():Promise<AuditEntry[]>{return(await listSystem("audit")).flatMap(row=>{try{const p=JSON.parse(row.details) as {action:string;story_id:string;title:string;details:string;at:string};return[{id:row.id,story_id:p.story_id,title:p.title,created_at:p.at||row.created_at,action:p.action,details:p.details||""}];}catch{return[];}});}
export async function restoreVersion(historyId:string){const row=await rawStory(historyId);if(!row||!row.source_name.startsWith(`${SYSTEM_PREFIX}history:`))return null;const payload=JSON.parse(row.details) as {snapshot:QueuedStory};const current=await rawStory(payload.snapshot.id);if(!current)return null;await recordVersion(current,"before_version_restore");const s=payload.snapshot;const restored=await patch(s.id,{title:s.title,institution:s.institution,category:s.category,summary:s.summary,details:s.details,deadline:s.deadline,deadline_iso:s.deadline_iso,image_url:s.image_url,document_url:s.document_url,document_name:s.document_name,official_source_name:s.official_source_name,official_source_url:s.official_source_url,status:s.status,source_name:s.source_name,source_url:s.source_url,source_published_at:s.source_published_at});if(restored)await recordAudit("Restored previous version",restored,`History record ${historyId}.`);return restored;}
