import { createStory, deleteStory, listStories, updateStory, type QueuedStory } from "./news-queue";
export type ModuleKey="forms"|"calendar"|"seo"|"enquiries"|"settings"|"calculator"|"media"|"analytics";
export type ModuleRecord={id:string;module:ModuleKey;title:string;subtitle:string;status:string;details:string;value:string;url:string|null;deadline:string|null;created_at:string;updated_at:string};
const PREFIX="S.O.H Module:";
const source=(m:ModuleKey,s:string)=>`${PREFIX}${m}:${s||"ACTIVE"}`;
function parse(s:string){if(!s.startsWith(PREFIX))return null;const [module,...rest]=s.slice(PREFIX.length).split(":");return {module:module as ModuleKey,status:rest.join(":")||"ACTIVE"}}
function mapped(s:QueuedStory):ModuleRecord|null{const p=parse(s.source_name);if(!p)return null;return{id:s.id,module:p.module,title:s.title,subtitle:s.institution,status:p.status,details:s.summary,value:s.details||"",url:s.official_source_url,deadline:s.deadline,created_at:s.created_at,updated_at:s.updated_at}}
async function getModuleStory(module:ModuleKey,id:string){const story=(await listStories()).find(s=>s.id===id);if(!story)return null;const record=mapped(story);return record?.module===module?story:null;}
export async function listModuleRecords(module:ModuleKey){return(await listStories()).map(mapped).filter((r):r is ModuleRecord=>!!r&&r.module===module).sort((a,b)=>+new Date(b.updated_at)-+new Date(a.updated_at))}
export async function createModuleRecord(module:ModuleKey,v:Partial<ModuleRecord>){const row=await createStory({title:v.title||"Untitled",institution:v.subtitle||"",category:`Admin ${module}`,summary:v.details||"",details:v.value||"",deadline:v.deadline||null,official_source_url:v.url||null,status:"archived"});const u=await updateStory(row.id,{source_name:source(module,v.status||"ACTIVE"),source_url:`module:${module}:${row.id}`});return mapped(u!)!}
export async function updateModuleRecord(module:ModuleKey,id:string,v:Partial<ModuleRecord>){const existing=await getModuleStory(module,id);if(!existing)throw new Error("Record not found");const patch:Partial<QueuedStory>={source_name:source(module,v.status||parse(existing.source_name)?.status||"ACTIVE")};if(v.title!==undefined)patch.title=v.title;if(v.subtitle!==undefined)patch.institution=v.subtitle;if(v.details!==undefined)patch.summary=v.details;if(v.value!==undefined)patch.details=v.value;if(v.deadline!==undefined)patch.deadline=v.deadline||null;if(v.url!==undefined)patch.official_source_url=v.url||null;const u=await updateStory(id,patch);if(!u)throw new Error("Record not found");return mapped(u)!}
export async function deleteModuleRecord(module:ModuleKey,id:string){const existing=await getModuleStory(module,id);if(!existing)return false;return deleteStory(id)}
export function isModuleKey(v:string):v is ModuleKey{return ["forms","calendar","seo","enquiries","settings","calculator","media","analytics"].includes(v)}
