import { upsertStories, type QueuedStory } from "./news-queue";

type Source = { name: string; url: string; baseUrl: string; official?: boolean };
const sources: Source[] = [
  { name: "WAEC Nigeria", url: "https://www.waecnigeria.org/news", baseUrl: "https://www.waecnigeria.org", official: true },
  { name: "JAMB", url: "https://www.jamb.gov.ng/Bulletins", baseUrl: "https://www.jamb.gov.ng", official: true },
  { name: "NYSC", url: "https://nysc.gov.ng/", baseUrl: "https://nysc.gov.ng", official: true },
  { name: "LASU", url: "https://www.lasu.edu.ng/home/index.php", baseUrl: "https://www.lasu.edu.ng", official: true },
  { name: "Myschool", url: "https://myschool.ng/news", baseUrl: "https://myschool.ng" },
  { name: "MySchoolGist", url: "https://myschoolgist.com/", baseUrl: "https://myschoolgist.com" },
];
const usefulTerms = /admission|post[- ]?utme|direct entry|screening|jamb|waec|wassce|neco|nabteb|scholarship|application form|admission list|cut[- ]?off|nysc|resumption|clearance|acceptance fee|registration|timetable|mobilisation|mobilization|matriculation|convocation|deadline|result|bursary|fellowship/i;
const lowValueTerms = /browser for all centres?|jambtest|test download|registration templates?|cbt centre|commissions? .*cbt|syllabus system|e[- ]?facility.*download|software download|photo gallery|press release|speech|courtesy visit|stakeholders? meeting|advertorial|procurement|tender|vacanc(?:y|ies)|staff recruitment|birthday|condolence|anniversary message/i;
const actionableSignals = /deadline|closing date|closes?|opens?|commence[sd]?|application|apply|form|admission list|result|timetable|scholarship|bursary|fellowship|mobilisation|mobilization|resumption|clearance|acceptance fee|matriculation|convocation|cut[- ]?off|candidate|examination|exam|utme|direct entry|wassce|waec|nysc|registration/i;
const FRESH_HOURS = 168;
function decodeHtml(v: string) { return v.replace(/<[^>]+>/g, " ").replace(/&amp;/g, "&").replace(/&#8211;|&ndash;/g, "-").replace(/&#8217;|&rsquo;/g, "'").replace(/&quot;|&#8220;|&#8221;/g, '"').replace(/&#(\d+);/g, (_, c) => String.fromCharCode(Number(c))).replace(/\s+/g, " ").trim(); }
function categoryFor(t: string) { if (/scholarship|bursary|fellowship/i.test(t)) return "Scholarship"; if (/jamb|utme|direct entry/i.test(t)) return "JAMB"; if (/waec|wassce|neco|nabteb|o.level/i.test(t)) return "O'Level"; if (/nysc|mobilisation|mobilization/i.test(t)) return "NYSC"; if (/admission list/i.test(t)) return "Admission List"; return "Admission"; }
function extractInstitution(t: string, s: Source) { if (s.official) return s.name; return t.match(/^([A-Z][A-Z0-9-]{2,12})(?:\s|:)/)?.[1] || "To be confirmed"; }
function isUsefulNews(t: string) { return usefulTerms.test(t) && !lowValueTerms.test(t) && actionableSignals.test(t); }
function extractLinks(html: string, s: Source) { const results = new Map<string, { title: string; url: string }>(); const pattern = /<a\b[^>]*href=["']([^"'#]+)["'][^>]*>([\s\S]*?)<\/a>/gi; const host = new URL(s.baseUrl).hostname.replace(/^www\./, ""); for (const m of html.matchAll(pattern)) { const title = decodeHtml(m[2]); if (title.length < 20 || title.length > 180 || !isUsefulNews(title)) continue; let url: URL; try { url = new URL(m[1], s.baseUrl); } catch { continue; } if (url.hostname.replace(/^www\./, "") !== host || url.protocol !== "https:") continue; url.hash = ""; results.set(url.toString(), { title, url: url.toString() }); } return [...results.values()].slice(0, s.official ? 25 : 15); }
/** Only article publication metadata counts; discovery time is never treated as publication time. */
export function articlePublicationDate(html: string): string | null { const tags = html.match(/<meta\b[^>]*>/gi) || []; for (const tag of tags) { const key = tag.match(/(?:property|name)\s*=\s*["']([^"']+)["']/i)?.[1]?.toLowerCase(); if (!key || !["article:published_time", "datepublished", "pubdate", "publish_date", "dc.date.issued", "citation_publication_date"].includes(key)) continue; const value = tag.match(/content\s*=\s*["']([^"']+)["']/i)?.[1]; if (value && !Number.isNaN(Date.parse(value))) return new Date(value).toISOString(); } for (const match of html.matchAll(/"datePublished"\s*:\s*"([^"\n]+)"/gi)) { if (!Number.isNaN(Date.parse(match[1]))) return new Date(match[1]).toISOString(); } return null; }
export function isFreshPublication(publishedAt: string | null, now = Date.now()) { if (!publishedAt) return false; const time = Date.parse(publishedAt); return Number.isFinite(time) && time <= now + 5 * 60_000 && time >= now - FRESH_HOURS * 60 * 60_000; }
export type DiscoverySuggestion = { source_name: string; source_url: string; source_published_at: string | null; title: string; institution: string; category: string; official: boolean };
export async function discoverLatestStories() { const suggestions: DiscoverySuggestion[] = [], failures: string[] = []; let skippedOld = 0, skippedUndated = 0; await Promise.all(sources.map(async s => { try { const r = await fetch(s.url, { headers: { "User-Agent": "S.O.H CONSULTS update monitor (+https://sohconsults.com.ng)" }, cache: "no-store", signal: AbortSignal.timeout(15000) }); if (!r.ok) throw new Error(`HTTP ${r.status}`); const links = extractLinks(await r.text(), s); if (!links.length) failures.push(`${s.name}: no qualifying article links found; check source layout or URL.`); await Promise.all(links.map(async item => { try { const article = await fetch(item.url, { cache: "no-store", signal: AbortSignal.timeout(10000) }); if (!article.ok) throw new Error(`HTTP ${article.status}`); const published = articlePublicationDate(await article.text()); if (!published) skippedUndated++; else if (!isFreshPublication(published)) { skippedOld++; return; } suggestions.push({ source_name: s.name, source_url: item.url, source_published_at: published, title: item.title, institution: extractInstitution(item.title, s), category: categoryFor(item.title), official: !!s.official }); } catch (error) { failures.push(`${s.name}: article fetch failed (${item.url}): ${error instanceof Error ? error.message : "Unknown error"}`); } })); } catch (error) { failures.push(`${s.name}: ${error instanceof Error ? error.message : "Unknown error"}`); } })); suggestions.sort((a, b) => (b.source_published_at || "").localeCompare(a.source_published_at || "")); return { suggestions, failures, skippedOld, skippedUndated }; }
export async function importLatestStories() { const { suggestions, failures, skippedOld, skippedUndated } = await discoverLatestStories(); const imported: Partial<QueuedStory>[] = suggestions.map(item => ({ source_name: item.source_name, source_url: item.source_url, source_published_at: item.source_published_at, title: item.title, institution: item.institution, category: item.category, summary: `${item.title}. ${item.official ? "Official-source" : "Discovery-source"} draft. Verify the original article and prepare an original S.O.H CONSULTS summary before approval.`, details: item.source_published_at ? "Verify dates, requirements and application links before publishing." : "Publication date could not be verified. Confirm publication date, dates, requirements and links before publishing.", official_source_name: item.official ? item.source_name : "", official_source_url: item.official ? item.source_url : "", status: "draft" })); const saved = await upsertStories(imported); return { discovered: imported.length, added: saved.length, skippedOld, skippedUndated, failures }; }
