import { getUpdateImage, getUpdateSlug, updates } from "../data/updates";

export type QueueStatus = "draft" | "approved" | "published" | "rejected" | "archived";
export type QueuedStory = { id:string; source_name:string; source_url:string; source_published_at:string|null; title:string; institution:string; category:string; summary:string; details:string; deadline:string|null; deadline_iso:string|null; image_url:string|null; document_url:string|null; document_name:string|null; official_source_name:string|null; official_source_url:string|null; status:QueueStatus; created_at:string; updated_at:string };
const SUPABASE_URL=process.env.SUPABASE_URL; const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY; const ATTACHMENT_PREFIX="/storage/v1/object/public/news-attachments/"; const OPPORTUNITY_PREFIX="S.O.H Opportunity:";
function headers(prefer?:string){if(!SUPABASE_URL||!SERVICE_KEY)throw new Error("Supabase environment variables are not configured.");return{apikey:SERVICE_KEY,...(SERVICE_KEY.startsWith("eyJ")?{Authorization:`Bearer ${SERVICE_KEY}`} :{}),"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})};}
export function slugifyStoryTitle(title:string){return title.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80);}
export function getStorySlug(story:Pick<QueuedStory,"id"|"title"|"source_url">){const legacy=story.source_url?.match(/^legacy:\d+:(.+)$/);return legacy?.[1]||slugifyStoryTitle(story.title)||`update-${story.id}`;}
function legacyDate(value:string,id:number){const parsed=new Date(value);return Number.isNaN(parsed.getTime())?new Date(`2026-09-${Math.max(1,Math.min(30,id))}T12:00:00Z`).toISOString():parsed.toISOString();}
let migrationPromise:Promise<void>|null=null;
async function ensureLegacyUpdatesMigrated(){if(migrationPromise)return migrationPromise;migrationPromise=(async()=>{if(!SUPABASE_URL||!SERVICE_KEY)return;const rows=updates.map(update=>{const when=legacyDate(update.date,update.id);return{id:crypto.randomUUID(),source_name:"S.O.H CONSULTS Legacy",source_url:`legacy:${update.id}:${getUpdateSlug(update)}`,source_published_at:when,title:update.title,institution:update.institution,category:update.category,summary:update.summary,details:update.details,deadline:update.deadline||null,deadline_iso:update.deadlineISO||null,image_url:getUpdateImage(update)||null,document_url:null,document_name:null,official_source_name:update.source||null,official_source_url:update.sourceUrl||null,status:"published",created_at:when,updated_at:when};});const r=await fetch(`${SUPABASE_URL}/rest/v1/news_queue?on_conflict=source_url`,{method:"POST",headers:headers("resolution=ignore-duplicates,return=minimal"),body:JSON.stringify(rows),cache:"no-store"});if(!r.ok)throw new Error(`Unable to migrate legacy updates (${r.status}).`);})().catch(error=>{migrationPromise=null;throw error;});return migrationPromise;}
export async function listStories(includeOpportunities=false):Promise<QueuedStory[]>{await ensureLegacyUpdatesMigrated();const r=await fetch(`${SUPABASE_URL}/rest/v1/news_queue?select=*&order=created_at.desc`,{headers:headers(),cache:"no-store"});if(!r.ok)throw new Error(`Unable to load approval queue (${r.status}).`);const rows=await r.json() as QueuedStory[];return includeOpportunities?rows:rows.filter(s=>!s.source_name.startsWith(OPPORTUNITY_PREFIX));}
export async function listPublishedStories():Promise<QueuedStory[]>{try{await ensureLegacyUpdatesMigrated();const r=await fetch(`${SUPABASE_URL}/rest/v1/news_queue?select=*&status=eq.published&order=updated_at.desc`,{headers:headers(),next:{revalidate:300}});if(!r.ok)return[];const rows=await r.json() as QueuedStory[];return rows.filter(s=>!s.source_name.startsWith(OPPORTUNITY_PREFIX));}catch{return[];}}
export async function getPublishedStory(id:string):Promise<QueuedStory|null>{await ensureLegacyUpdatesMigrated().catch(()=>{});const r=await fetch(`${SUPABASE_URL}/rest/v1/news_queue?select=*&id=eq.${encodeURIComponent(id)}&status=eq.published&limit=1`,{headers:headers(),next:{revalidate:300}});if(!r.ok)return null;const rows=await r.json() as QueuedStory[];const story=rows[0]||null;return story?.source_name.startsWith(OPPORTUNITY_PREFIX)?null:story;}
export async function getPublishedStoryBySlug(slug:string):Promise<QueuedStory|null>{const stories=await listPublishedStories();return stories.find(story=>getStorySlug(story)===slug)||null;}
export async function upsertStories(stories:Array<Partial<QueuedStory>>){if(!stories.length)return[];const r=await fetch(`${SUPABASE_URL}/rest/v1/news_queue?on_conflict=source_url`,{method:"POST",headers:headers("resolution=ignore-duplicates,return=representation"),body:JSON.stringify(stories),cache:"no-store"});if(!r.ok)throw new Error(`Unable to save imported stories (${r.status}).`);return r.json();}
export async function createStory(values:Partial<QueuedStory>){const id=crypto.randomUUID();const now=new Date().toISOString();const row={id,source_name:"S.O.H CONSULTS",source_url:`manual:${id}`,source_published_at:null,title:values.title,institution:values.institution,category:values.category,summary:values.summary,details:values.details,deadline:values.deadline||null,deadline_iso:values.deadline_iso||null,image_url:values.image_url||null,document_url:values.document_url||null,document_name:values.document_name||null,official_source_name:values.official_source_name||null,official_source_url:values.official_source_url||null,status:values.status||"draft",created_at:now,updated_at:now};const r=await fetch(`${SUPABASE_URL}/rest/v1/news_queue`,{method:"POST",headers:headers("return=representation"),body:JSON.stringify(row),cache:"no-store"});if(!r.ok)throw new Error(`Unable to create story (${r.status}).`);return(await r.json())[0] as QueuedStory;}
async function getStory(id:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/news_queue?select=*&id=eq.${encodeURIComponent(id)}&limit=1`,{headers:headers(),cache:"no-store"});if(!r.ok)throw new Error("Unable to load story.");return (await r.json())[0] as QueuedStory|undefined;}
function attachmentPath(url:string|null){if(!url||!SUPABASE_URL||!url.startsWith(`${SUPABASE_URL}${ATTACHMENT_PREFIX}`))return null;const path=decodeURIComponent(url.slice(`${SUPABASE_URL}${ATTACHMENT_PREFIX}`.length));return /^(images|documents)\/[a-f0-9-]+\.[a-z0-9]+$/i.test(path)?path:null;}
async function deleteAttachment(url:string|null){const path=attachmentPath(url);if(!path)return;const r=await fetch(`${SUPABASE_URL}/storage/v1/object/news-attachments/${path.split("/").map(encodeURIComponent).join("/")}`,{method:"DELETE",headers:headers(),cache:"no-store"});if(!r.ok&&r.status!==404)console.error(`Attachment cleanup failed (${r.status}).`);}
export async function updateStory(id:string,values:Partial<QueuedStory>){const previous=await getStory(id);const r=await fetch(`${SUPABASE_URL}/rest/v1/news_queue?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:headers("return=representation"),body:JSON.stringify({...values,updated_at:new Date().toISOString()}),cache:"no-store"});if(!r.ok)throw new Error(`Unable to update story (${r.status}).`);const updated=(await r.json())[0] as QueuedStory|undefined;if(previous&&updated){const cleanup:Promise<void>[]=[];if(previous.image_url&&previous.image_url!==updated.image_url)cleanup.push(deleteAttachment(previous.image_url));if(previous.document_url&&previous.document_url!==updated.document_url)cleanup.push(deleteAttachment(previous.document_url));await Promise.all(cleanup);}return updated;}
export async function deleteStory(id:string){const story=await getStory(id);if(!story)return false;const r=await fetch(`${SUPABASE_URL}/rest/v1/news_queue?id=eq.${encodeURIComponent(id)}`,{method:"DELETE",headers:headers("return=minimal"),cache:"no-store"});if(!r.ok)throw new Error(`Unable to permanently delete story (${r.status}).`);await Promise.all([deleteAttachment(story.image_url),deleteAttachment(story.document_url)]);return true;}
export async function uploadStoryFile(file:File,kind:"image"|"document"){if(!SUPABASE_URL||!SERVICE_KEY)throw new Error("Supabase environment variables are not configured.");const extensions:Record<string,string>={"image/jpeg":"jpg","image/png":"png","image/webp":"webp","application/pdf":"pdf"};const extension=extensions[file.type];if(!extension)throw new Error("Unsupported verified file type.");const safeName=`${kind}s/${crypto.randomUUID()}.${extension}`;const r=await fetch(`${SUPABASE_URL}/storage/v1/object/news-attachments/${safeName}`,{method:"POST",headers:{...headers("return=minimal"),"Content-Type":file.type,"x-upsert":"false"},body:await file.arrayBuffer()});if(!r.ok)throw new Error(`Unable to upload file (${r.status}).`);return`${SUPABASE_URL}/storage/v1/object/public/news-attachments/${safeName}`;}
