import type {QueuedStory} from "./news-queue";
import {readArticleBlocks} from "./article-blocks";
export type OperationsModule="opportunities"|"forms"|"media"|"calendar";
const opportunity=/opportunit|scholarship|internship|fellowship|vacanc|recruit|\bjob\b|\bgrant\b|nysc|employment|career/i;
const forms=/admission|application|registration|screening|post.?utme|postgraduate|pre.?degree|sandwich|part.?time|jupeb|\bform\b/i;
export function publishedOperations(stories:QueuedStory[]){return stories.filter(s=>s.status==="published"&&!s.source_name.startsWith("S.O.H Module:")&&!s.source_name.startsWith("S.O.H Opportunity:"));}
export function articleMedia(story:QueuedStory){const blocks=readArticleBlocks(story.details)||[];const blockImages=blocks.flatMap(block=>block.type==="image"?[block.url]:block.type==="gallery"?block.urls:[]);return{images:[...new Set([story.image_url||"",...blockImages].filter(Boolean))],documentUrl:story.document_url,documentName:story.document_name};}
export function moduleFor(story:QueuedStory,module:OperationsModule){const category=story.category||"",title=story.title||"",text=`${category} ${title}`;if(module==="opportunities")return opportunity.test(text);if(module==="forms")return forms.test(text)&&!opportunity.test(text);if(module==="media"){const media=articleMedia(story);return media.images.length>0||Boolean(media.documentUrl);}return Boolean(deadlineDate(story));}
export function deadlineDate(story:QueuedStory){const raw=story.deadline_iso;if(!raw||!/^\d{4}-\d{2}-\d{2}(?:$|T|\s)/.test(raw))return null;const date=new Date(`${raw.slice(0,10)}T00:00:00Z`);return Number.isNaN(date.getTime())||date.toISOString().slice(0,10)!==raw.slice(0,10)?null:raw.slice(0,10);}
export function deadlineState(story:QueuedStory,today:string){const date=deadlineDate(story);if(!date)return "Date unverified" as const;if(date<today)return "Closed" as const;const days=Math.round((Date.parse(`${date}T00:00:00Z`)-Date.parse(`${today}T00:00:00Z`))/86400000);return days<=7?"Closing soon" as const:"Open" as const;}
/** Nigeria-local day: UTC dates lag by one day between midnight and 00:59 WAT. */
export function todayUTC(){const parts=new Intl.DateTimeFormat("en-GB",{timeZone:"Africa/Lagos",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const get=(type:string)=>parts.find(p=>p.type===type)?.value||"";return `${get("year")}-${get("month")}-${get("day")}`;}
