import { opportunities as seedOpportunities } from "../data/updates";
import { createStory, deleteStory, listStories, updateStory, type QueuedStory } from "./news-queue";

export type ManagedOpportunity={id:string;institution:string;programme:string;category:string;status:string;deadline:string;description:string;application_url:string|null;created_at:string;updated_at:string};
const PREFIX="S.O.H Opportunity:";
function statusFrom(source:string){return source.startsWith(PREFIX)?source.slice(PREFIX.length)||"OPEN":"OPEN"}
function toManaged(s:QueuedStory):ManagedOpportunity{return{id:s.id,institution:s.institution,programme:s.title,category:s.category,status:statusFrom(s.source_name),deadline:s.deadline||"Check latest deadline",description:s.summary,application_url:s.official_source_url,created_at:s.created_at,updated_at:s.updated_at}}
let seedPromise:Promise<void>|null=null;
async function ensureSeeded(){if(seedPromise)return seedPromise;seedPromise=(async()=>{const all=await listStories();if(all.some(s=>s.source_name.startsWith(PREFIX)))return;for(const item of seedOpportunities){const row=await createStory({title:item.programme,institution:item.institution,category:item.category,summary:item.description,details:item.description,deadline:item.deadline,status:"archived"});await updateStory(row.id,{source_name:`${PREFIX}${item.status}`,source_url:`opportunity:${row.id}`,official_source_url:null});}})().catch(e=>{seedPromise=null;throw e});return seedPromise}
export async function listManagedOpportunities(){await ensureSeeded();return(await listStories()).filter(s=>s.source_name.startsWith(PREFIX)).map(toManaged).sort((a,b)=>+new Date(b.updated_at)-+new Date(a.updated_at))}
export async function createManagedOpportunity(v:Partial<ManagedOpportunity>){const row=await createStory({title:v.programme||"",institution:v.institution||"",category:v.category||"Other",summary:v.description||"",details:v.description||"",deadline:v.deadline||null,official_source_url:v.application_url||null,status:"archived"});const updated=await updateStory(row.id,{source_name:`${PREFIX}${v.status||"OPEN"}`,source_url:`opportunity:${row.id}`});return toManaged(updated!)}
export async function updateManagedOpportunity(id:string,v:Partial<ManagedOpportunity>){const updated=await updateStory(id,{title:v.programme,institution:v.institution,category:v.category,summary:v.description,details:v.description,deadline:v.deadline||null,official_source_url:v.application_url||null,source_name:`${PREFIX}${v.status||"OPEN"}`});if(!updated)throw new Error("Opportunity not found.");return toManaged(updated)}
export async function deleteManagedOpportunity(id:string){return deleteStory(id)}
