import{createModuleRecord,listModuleRecords,updateModuleRecord}from"./admin-module-store";
export type CmsSectionType="hero"|"updates"|"services"|"tools"|"opportunities"|"founder"|"contact"|"text"|"cta"|"cards"|"faq"|"gallery"|"stats";
export type CmsLayout="full"|"contained"|"grid-2"|"grid-3"|"list"|"split-left"|"split-right";
export type CmsItem={id:string;title:string;description:string;link:string;image:string};
export type CmsSection={id:string;type:CmsSectionType;name:string;title:string;description:string;layout:CmsLayout;visible:boolean;items:CmsItem[]};
export type SiteSettings={siteName:string;tagline:string;heroEyebrow:string;heroTitle:string;heroAccent:string;heroDescription:string;whatsapp:string;email:string;instagram:string;facebook:string;whatsappChannel:string;latestUpdatesCount:number;showHero:boolean;showQuickServices:boolean;showScreeningTool:boolean;showLatestUpdates:boolean;showServices:boolean;showFounder:boolean;showContact:boolean;maintenanceNote:string;sections:CmsSection[];draftVersion:number;publishedVersion:number};
const TITLE="Site Manager Settings";
const section=(id:string,type:CmsSectionType,name:string,title:string,description:string,layout:CmsLayout="contained"):CmsSection=>({id,type,name,title,description,layout,visible:true,items:[]});
export const defaultSections:CmsSection[]=[section("hero","hero","Hero","Your Guide. Your Success.","Trusted admission support, educational opportunities and professional guidance for a brighter future.","full"),section("quick-services","services","Quick services","Start here","Fast access to the services and information students use most.","grid-3"),section("screening-tool","tools","Screening tool","Check Your Post-UTME Screening Aggregate","Calculate your screening or admission aggregate.","contained"),section("latest-updates","updates","Latest updates","Latest Updates","Admission and education news in one place.","grid-3"),section("services","services","Services","Our Services","Practical admission, documentation and educational support.","grid-3"),section("founder","founder","Meet the Founder","Meet the Founder","The story and leadership behind S.O.H CONSULTS.","split-left"),section("contact","contact","Contact","Need Guidance?","Reach S.O.H CONSULTS through our official channels.","contained")];
export const defaultSiteSettings:SiteSettings={siteName:"S.O.H CONSULTS",tagline:"Your Guide. Your Success.",heroEyebrow:"Admissions • Education • Consultation",heroTitle:"Your Guide.",heroAccent:"Your Success.",heroDescription:"Trusted admission support, educational opportunities and professional guidance for a brighter future.",whatsapp:"2348182141088",email:"support@sohconsults.com.ng",instagram:"https://www.instagram.com/sohconsults/",facebook:"https://www.facebook.com/share/19Mzqo5Ggg/",whatsappChannel:"https://whatsapp.com/channel/0029VbD6QQp3GJP68dl9TK29",latestUpdatesCount:3,showHero:true,showQuickServices:true,showScreeningTool:true,showLatestUpdates:true,showServices:true,showFounder:true,showContact:true,maintenanceNote:"",sections:defaultSections,draftVersion:1,publishedVersion:1};
export async function getSiteSettings(){const row=(await listModuleRecords("settings")).find(r=>r.title===TITLE);if(!row)return defaultSiteSettings;try{const parsed=JSON.parse(row.value);return{...defaultSiteSettings,...parsed,sections:Array.isArray(parsed.sections)&&parsed.sections.length?parsed.sections:defaultSections} as SiteSettings}catch{return defaultSiteSettings}}
export async function saveSiteSettings(value:SiteSettings){const rows=await listModuleRecords("settings"),row=rows.find(r=>r.title===TITLE),payload=JSON.stringify(value);if(row)return updateModuleRecord("settings",row.id,{...row,value:payload,status:"ACTIVE",details:"Professional S.O.H CMS configuration managed from Admin."});return createModuleRecord("settings",{title:TITLE,subtitle:"S.O.H Website Builder / CMS",details:"Professional S.O.H CMS configuration managed from Admin.",value:payload,status:"ACTIVE"})}
const txt=(v:unknown,f:string,n:number)=>String(v??f).trim().slice(0,n);const bool=(v:unknown,f:boolean)=>typeof v==="boolean"?v:f;
const TYPES:CmsSectionType[]=["hero","updates","services","tools","opportunities","founder","contact","text","cta","cards","faq","gallery","stats"];const LAYOUTS:CmsLayout[]=["full","contained","grid-2","grid-3","list","split-left","split-right"];
function cleanSections(v:unknown){if(!Array.isArray(v))return defaultSections;return v.slice(0,40).map((s:any,i)=>({id:txt(s?.id,`section-${i+1}`,80).replace(/[^a-zA-Z0-9-_]/g,"-"),type:TYPES.includes(s?.type)?s.type:"text",name:txt(s?.name,"Section",80),title:txt(s?.title,"",160),description:txt(s?.description,"",1200),layout:LAYOUTS.includes(s?.layout)?s.layout:"contained",visible:bool(s?.visible,true),items:Array.isArray(s?.items)?s.items.slice(0,30).map((x:any,j:number)=>({id:txt(x?.id,`item-${j+1}`,80),title:txt(x?.title,"",160),description:txt(x?.description,"",600),link:txt(x?.link,"",400),image:txt(x?.image,"",400)})):[]})) as CmsSection[]}
export function sanitizeSiteSettings(b:Partial<SiteSettings>):SiteSettings{return{siteName:txt(b.siteName,defaultSiteSettings.siteName,60),tagline:txt(b.tagline,defaultSiteSettings.tagline,100),heroEyebrow:txt(b.heroEyebrow,defaultSiteSettings.heroEyebrow,100),heroTitle:txt(b.heroTitle,defaultSiteSettings.heroTitle,100),heroAccent:txt(b.heroAccent,defaultSiteSettings.heroAccent,100),heroDescription:txt(b.heroDescription,defaultSiteSettings.heroDescription,280),whatsapp:txt(b.whatsapp,defaultSiteSettings.whatsapp,20).replace(/[^0-9]/g,""),email:txt(b.email,defaultSiteSettings.email,120),instagram:txt(b.instagram,defaultSiteSettings.instagram,300),facebook:txt(b.facebook,defaultSiteSettings.facebook,300),whatsappChannel:txt(b.whatsappChannel,defaultSiteSettings.whatsappChannel,300),latestUpdatesCount:Math.max(1,Math.min(12,Number(b.latestUpdatesCount)||3)),showHero:bool(b.showHero,true),showQuickServices:bool(b.showQuickServices,true),showScreeningTool:bool(b.showScreeningTool,true),showLatestUpdates:bool(b.showLatestUpdates,true),showServices:bool(b.showServices,true),showFounder:bool(b.showFounder,true),showContact:bool(b.showContact,true),maintenanceNote:txt(b.maintenanceNote,"",300),sections:cleanSections(b.sections),draftVersion:Math.max(1,Number(b.draftVersion)||1),publishedVersion:Math.max(1,Number(b.publishedVersion)||1)}}
