import { NextRequest,NextResponse } from "next/server";
import { isAdmin } from "../../../../lib/admin-auth";
import { createModuleRecord,deleteModuleRecord,isModuleKey,listModuleRecords,updateModuleRecord } from "../../../../lib/admin-module-store";
const no=()=>NextResponse.json({error:"Unauthorized"},{status:401});
const safeHttpUrl=(value:unknown)=>{if(!value)return null;const raw=String(value).trim();if(!raw)return null;try{const u=new URL(raw);return u.protocol==="http:"||u.protocol==="https:"?u.toString():null}catch{return null}};
function clean(body:Record<string,unknown>){const deadline=body.deadline?String(body.deadline).trim():null;const url=body.url?String(body.url).trim():null;return{title:String(body.title||"").trim(),subtitle:String(body.subtitle||"").trim(),status:String(body.status||"").trim(),details:String(body.details||"").trim(),value:String(body.value||"").trim(),deadline,url:url?safeHttpUrl(url):null};}
export async function GET(r:NextRequest){if(!(await isAdmin()))return no();const m=r.nextUrl.searchParams.get("module")||"";if(!isModuleKey(m))return NextResponse.json({error:"Invalid module"},{status:400});return NextResponse.json({records:await listModuleRecords(m)});}
export async function POST(r:NextRequest){if(!(await isAdmin()))return no();const b=await r.json().catch(()=>null) as Record<string,unknown>|null;if(!b||!isModuleKey(String(b.module||"")))return NextResponse.json({error:"Invalid module"},{status:400});const module=String(b.module);if(!isModuleKey(module))return NextResponse.json({error:"Invalid module"},{status:400});const v=clean(b);if(!v.title)return NextResponse.json({error:"Title is required"},{status:400});if(b.url&& !v.url)return NextResponse.json({error:"URL must use http:// or https://"},{status:400});if(v.deadline&&Number.isNaN(Date.parse(v.deadline)))return NextResponse.json({error:"Date must be valid"},{status:400});return NextResponse.json({record:await createModuleRecord(module,v)},{status:201});}
export async function PATCH(r:NextRequest){if(!(await isAdmin()))return no();const b=await r.json().catch(()=>null) as Record<string,unknown>|null;if(!b||!isModuleKey(String(b.module||""))||!b.id)return NextResponse.json({error:"Invalid request"},{status:400});const module=String(b.module);if(!isModuleKey(module))return NextResponse.json({error:"Invalid module"},{status:400});const v=clean(b);if(!v.title)return NextResponse.json({error:"Title is required"},{status:400});if(b.url&& !v.url)return NextResponse.json({error:"URL must use http:// or https://"},{status:400});if(v.deadline&&Number.isNaN(Date.parse(v.deadline)))return NextResponse.json({error:"Date must be valid"},{status:400});try{return NextResponse.json({record:await updateModuleRecord(module,String(b.id),v)})}catch{return NextResponse.json({error:"Record not found"},{status:404})}}
export async function DELETE(r:NextRequest){if(!(await isAdmin()))return no();const b=await r.json().catch(()=>null) as Record<string,unknown>|null;if(!b||!isModuleKey(String(b.module||""))||!b.id||b.confirmation!=="PERMANENTLY DELETE")return NextResponse.json({error:"Module, record and typed confirmation are required"},{status:400});const module=String(b.module);if(!isModuleKey(module))return NextResponse.json({error:"Invalid module"},{status:400});const deleted=await deleteModuleRecord(module,String(b.id));if(!deleted)return NextResponse.json({error:"Record not found"},{status:404});return NextResponse.json({ok:true});}
