import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { isAdmin } from "../../../lib/admin-auth";

const modules:Record<string,{title:string;description:string;actions:string[]}>={
 forms:{title:"Forms Manager",description:"Manage admission forms, availability and open or closed status.",actions:["Add Form","Edit Form","Open / Close","Archive / Restore","Remove"]},
 calculator:{title:"LASU Calculator Control",description:"Manage calculator notices and future admin-controlled admission rules without disturbing the live calculation engine.",actions:["Edit Notice","Manage Cut-off","Programme Rules","Special Requirements","Publish Changes"]},
 media:{title:"Media Library",description:"Manage images, flyers and PDF attachments used across S.O.H CONSULTS content.",actions:["Upload Media","View","Replace","Reuse","Remove"]},
 calendar:{title:"Content Calendar",description:"Plan publications, deadlines, examinations and registration closing dates.",actions:["Add Event","Edit","Schedule","Reschedule","Remove"]},
 seo:{title:"SEO Control",description:"Review content titles, descriptions, links and public discoverability.",actions:["Review Issues","Edit Metadata","Check Links","Prioritise","Resolve"]},
 enquiries:{title:"Enquiries & Leads",description:"Manage future website enquiries and WhatsApp lead sources.",actions:["View Lead","Mark Responded","Close","Reopen","Remove"]},
 analytics:{title:"Analytics",description:"Monitor future visitors, popular pages, CTA clicks, search and Ask S.O.H usage.",actions:["Visitors","Top Pages","WhatsApp Clicks","Search","Ask S.O.H"]},
 settings:{title:"System Settings",description:"Manage future business contact details and global website configuration.",actions:["Business Details","WhatsApp","Email","Social Links","Website Settings"]},
};
export default async function ModuleWorkspace({params}:{params:Promise<{module:string}>}){if(!(await isAdmin()))redirect("/admin/updates");const {module}=await params;const item=modules[module];if(!item)notFound();return <main className="min-h-screen bg-gray-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-[1200px] flex-wrap items-center justify-between gap-4 px-5 py-5"><div><p className="text-[11px] font-black uppercase tracking-[.2em] text-green-700">S.O.H CONSULTS · PRIVATE</p><h1 className="text-2xl font-black">{item.title}</h1><p className="mt-1 text-sm text-gray-500">{item.description}</p></div><div className="flex gap-2"><Link href="/admin/modules" className="rounded-xl border px-4 py-2 text-sm font-black">All Modules</Link><Link href="/admin" className="rounded-xl bg-green-700 px-4 py-2 text-sm font-black text-white">Dashboard</Link></div></div></header><section className="mx-auto max-w-[1200px] px-5 py-7"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-amber-700">Private workspace ready</p><h2 className="mt-1 text-xl font-black">Management controls are staged safely</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-gray-700">This module now has its own admin destination. Write actions will activate when its persistent Supabase storage is connected. Until then, existing production content remains unchanged.</p></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{item.actions.map(a=><div key={a} className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-black">{a}</h3><p className="mt-2 text-sm text-gray-500">Control prepared for this workspace.</p><button disabled className="mt-5 cursor-not-allowed rounded-lg bg-gray-100 px-3 py-2 text-xs font-black text-gray-400">Awaiting storage connection</button></div>)}</div></section></main>}
