import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {isAdmin} from "../../../lib/admin-auth";
import {isModuleKey,listModuleRecords} from "../../../lib/admin-module-store";
import {analyticsSummary,latestHealth,serverSnapshotTime} from "../../../lib/business-intelligence";
import PublishedUpdateModuleFeed from "../PublishedUpdateModuleFeed";
import MediaIntelligence from "../media/MediaIntelligence";
import ModuleManagerClient from "./ModuleManagerClient";
const modules:Record<string,{title:string;description:string}>= {forms:{title:"Forms Manager",description:"Add, edit and control admission forms and programme availability."},calculator:{title:"LASU Calculator Control",description:"Manage notices and configuration records without changing the protected live calculation engine."},media:{title:"Media Library",description:"Search, preview and reuse images and documents already attached to S.O.H CONSULTS updates."},calendar:{title:"Content Calendar",description:"Manage publications, deadlines, examinations and registration dates."},seo:{title:"SEO Control",description:"Track and manage titles, metadata, links and discoverability tasks."},enquiries:{title:"Enquiries & Leads",description:"Manage website enquiries and WhatsApp lead records."},analytics:{title:"Analytics",description:"Privacy-conscious event totals for article views, calculator interactions and WhatsApp clicks."},settings:{title:"System Settings",description:"Manage business and website configuration records from the private dashboard."}};
export default async function Page({params}:{params:Promise<{module:string}>}){if(!(await isAdmin()))redirect("/admin/updates");const {module}=await params;if(!modules[module]||!isModuleKey(module))notFound();const item=modules[module];const records=await listModuleRecords(module);const now=await serverSnapshotTime();const counts=module==="analytics"?await analyticsSummary():null;const health=module==="settings"?await latestHealth():null;const overdue=module==="enquiries"?records.filter(r=>r.deadline&&Number.isFinite(Date.parse(r.deadline))&&new Date(r.deadline).getTime()<now&&!(["CLOSED","CONVERTED"].includes(r.status))):[];return <main className="min-h-screen bg-gray-50 text-gray-950"><header className="border-b bg-white"><div className="mx-auto max-w-[1300px] flex flex-wrap items-center justify-between gap-4 px-5 py-5"><div><p className="text-[11px] font-black uppercase tracking-[.2em] text-green-700">S.O.H CONSULTS · PRIVATE</p><h1 className="text-2xl font-black">{item.title}</h1><p className="mt-1 text-sm text-gray-500">{item.description}</p></div><div className="flex gap-2"><Link href="/admin/modules" className="rounded-xl border px-4 py-2 text-sm font-black">All Modules</Link><Link href="/admin" className="rounded-xl bg-green-700 px-4 py-2 text-sm font-black text-white">Dashboard</Link></div></div></header><section className="mx-auto max-w-[1300px] px-5 py-7">{counts&&<section className="mb-6 grid gap-3 sm:grid-cols-3">{Object.entries(counts).map(([name,count])=><div key={name} className="rounded-xl border bg-white p-5"><p className="text-3xl font-black text-green-800">{count}</p><p className="mt-2 text-sm font-bold">{name.replaceAll("_"," ")}</p></div>)}</section>}{health&&<section className="mb-6 rounded-xl border bg-white p-5"><h2 className="text-xl font-black">Operations health · latest 20 runs</h2>{health.length?health.map(r=><p key={r.id} className="mt-2 text-sm"><b className={r.status==="FAILED"?"text-red-700":"text-green-700"}>{r.status}</b> · {r.title} · {r.created_at} · {r.details}</p>):<p className="mt-2 text-sm">No cron health records yet. A successful run has not been verified.</p>}{health[0]&&now-new Date(health[0].created_at).getTime()>36*60*60*1000&&<p className="mt-3 font-bold text-red-700">Latest health record is older than 36 hours. Check scheduled tasks.</p>}</section>}{module==="enquiries"&&<section className="mb-6 rounded-xl border bg-white p-5"><h2 className="text-xl font-black">Overdue follow-ups: {overdue?.length||0}</h2>{overdue?.slice(0,10).map(r=><p key={r.id} className="mt-2 text-sm text-red-700">{r.title} · {r.deadline}</p>)}</section>}{module==="media"&&<MediaIntelligence/>}{(module==="forms"||module==="media"||module==="calendar")&&<PublishedUpdateModuleFeed module={module}/>}<ModuleManagerClient module={module} initial={records.filter(r=>module!=="analytics"||r.status!=="MEASURED").filter(r=>module!=="settings"||!r.title.startsWith("Health: "))}/></section></main>}
