"use client";
import Link from "next/link"; import {useMemo,useState} from "react"; import {lasuedGradePoints,lasuedRules,lasuedSubjects} from "@/data/lasued"; import LasuStyleOLevel,{type OLevelResultEntry} from "../components/LasuStyleOLevel";
const grades=Object.keys(lasuedGradePoints);
export default function LASUEDCalculator(){
 const[name,setName]=useState(""),[programme,setProgramme]=useState(""),[jamb,setJamb]=useState(""),[sittings,setSittings]=useState<1|2>(1);
 const[results,setResults]=useState<OLevelResultEntry[]>([]); const rows=results.filter(r=>r.subject||r.grade).map(r=>({s:r.subject,g:r.grade,sit:r.sitting}));
 const rule=lasuedRules.find(r=>r.name===programme); const j=Math.max(0,Math.min(400,Number(jamb)||0)); const jp=j/8;
 const entered=rows.filter(r=>r.s||r.g); const relevant=rule?entered.filter(r=>rule.required.includes(r.s)||rule.alternatives.includes(r.s)||(rule.either||[]).includes(r.s)):entered; const bestFive=[...relevant].sort((a,b)=>(lasuedGradePoints[b.g]||0)-(lasuedGradePoints[a.g]||0)).slice(0,5); const op=bestFive.reduce((a,r)=>a+(lasuedGradePoints[r.g]||0),0); const total=jp+op;
 const chosen=rows.filter(r=>r.s&&["A1","B2","B3","C4","C5","C6"].includes(r.g)).map(r=>r.s);
 const unique=new Set(entered.map(r=>r.s).filter(Boolean)).size===entered.filter(r=>r.s).length;
 const reqOK=!!rule&&rule.required.every(x=>chosen.includes(x))&&(!rule.either||rule.either.some(x=>chosen.includes(x)))&&bestFive.length===5&&entered.length>=5&&entered.every(r=>r.s&&r.g)&&unique;
 const download=async(kind:"jpg"|"pdf")=>{if(!programme||!jamb||!reqOK)return alert("Complete valid candidate, UTME and five relevant O'Level entries first.");
  const c=document.createElement("canvas");c.width=1240;c.height=1754;const x=c.getContext("2d")!;x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height);x.fillStyle="#15803d";x.fillRect(0,0,1240,220);x.fillStyle="#fff";x.font="700 34px Arial";x.fillText("S.O.H CONSULTS",70,80);x.font="700 46px Arial";x.fillText("LASUED SCREENING REPORT",70,145);x.font="22px Arial";x.fillText("Your Guide. Your Success.",70,190);x.fillStyle="#111827";x.font="700 28px Arial";x.fillText("Candidate Information",70,290);x.font="22px Arial";x.fillText("Name: "+(name||"Not supplied"),70,340);x.fillText("Programme: "+programme,70,380);x.fillText("JAMB Score: "+j+"   |   JAMB Average: "+jp.toFixed(2),70,420);x.font="700 28px Arial";x.fillText("O'Level Result",70,500);x.font="22px Arial";rows.forEach((r,i)=>x.fillText((i+1)+". "+r.s+"  "+r.g+(sittings===2?"  (Sitting "+r.sit+")":""),90,550+i*48));x.font="700 30px Arial";x.fillStyle="#15803d";x.fillText("O'Level Score: "+op.toFixed(0),70,850);x.fillText("E-Screening Assessment Score: "+total.toFixed(2)+"%",70,905);x.fillStyle="#111827";x.font="20px Arial";x.fillText(reqOK?"Programme O'Level requirement fulfilled.":"Programme O'Level requirement not fulfilled.",70,960);x.font="18px Arial";x.fillText("Screening formula: JAMB ÷ 8 + O'Level points.",70,1040);x.fillText("A1=10, B2=9, B3=8, C4=7, C5=6, C6=5.",70,1080);x.fillText("S.O.H CONSULTS | sohconsults.com.ng | 0818 214 1088",70,1650);
  if(kind==="jpg"){const a=document.createElement("a");a.download="LASUED-screening-report.jpg";a.href=c.toDataURL("image/jpeg",.95);a.click()}else{const{jsPDF}=await import("jspdf");const p=new jsPDF({orientation:"portrait",unit:"px",format:[1240,1754]});p.addImage(c.toDataURL("image/jpeg",.95),"JPEG",0,0,1240,1754);p.save("LASUED-screening-report.pdf")}};
 return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">
 <header className="rounded-3xl bg-gradient-to-br from-green-700 via-green-600 to-emerald-500 p-6 text-white shadow-xl sm:p-8"><nav className="flex flex-wrap gap-2 text-sm font-bold"><Link className="rounded-full bg-white px-4 py-2 !text-green-800" href="/">Home</Link><Link className="rounded-full bg-white/15 px-4 py-2" href="/screening-calculator">Screening Calculators</Link><Link className="rounded-full bg-white/15 px-4 py-2" href="/updates">Latest Updates</Link></nav><p className="mt-7 text-sm font-black uppercase tracking-widest text-green-100">S.O.H CONSULTS</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">LASUED Screening Aggregate Calculator</h1><p className="mt-3 max-w-3xl text-green-50">Calculate your Lagos State University of Education e-screening assessment score using JAMB and five programme-relevant O'Level subjects.</p></header>
 <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 className="text-xl font-black">Candidate Information</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Candidate Name<input className="mt-2 w-full rounded-xl border p-3 font-normal" value={name} onChange={e=>setName(e.target.value)} placeholder="Enter full name"/></label><label className="text-sm font-bold">Programme<select className="mt-2 w-full rounded-xl border p-3 font-normal" value={programme} onChange={e=>setProgramme(e.target.value)}><option value="">Select programme</option>{lasuedRules.map(r=><option key={r.name}>{r.name}</option>)}</select></label></div>
 {rule&&<div className="mt-5 rounded-2xl bg-green-50 p-4 text-sm"><b>O'Level requirement:</b> {rule.required.join(", ")}{rule.either&&<> plus either {rule.either.join(" or ")}</>} plus enough approved subjects to make five credits.</div>}
 <div className="mt-7 border-t pt-6"><h2 className="text-xl font-black">JAMB Score</h2><input type="number" min="0" max="400" className="mt-3 w-full rounded-xl border p-3" value={jamb} onChange={e=>setJamb(e.target.value)} placeholder="e.g. 193"/><p className="mt-2 text-sm text-slate-500">LASUED JAMB Average Score: <b>{jp.toFixed(2)}</b> (JAMB ÷ 8)</p></div>
 <div className="mt-7 border-t pt-6"><h2 className="text-xl font-black">O'Level Screening</h2><p className="mt-1 text-sm text-slate-600">Enter 5 to 9 O'Level subjects and grades. The calculator automatically selects the best five relevant subjects for your programme.</p><LasuStyleOLevel subjects={lasuedSubjects} grades={grades} value={results} onChange={setResults} sittings={sittings} onSittingsChange={setSittings} note="Select 2 Sittings to enter the first and second O-Level results separately. Enter up to 9 subjects in each sitting."/><p className="mt-3 text-sm text-slate-500">LASUED points: A1=10, B2=9, B3=8, C4=7, C5=6, C6=5.</p>{programme&&!reqOK&&entered.length>=5&&entered.every(r=>r.s&&r.g)&&<p className="mt-3 rounded-xl bg-amber-50 p-4 text-sm font-bold text-amber-800">The selected five subjects do not satisfy the published O'Level requirement for {programme}.</p>}</div>
 <div className="mt-7 border-t pt-6"><h2 className="text-lg font-black">Live Aggregate</h2><div className="mt-3 grid grid-cols-3 gap-2"><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs font-bold text-slate-500">JAMB AVG.</span><p className="font-black">{jp.toFixed(2)}</p></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs font-bold text-slate-500">O'LEVEL</span><p className="font-black">{op.toFixed(0)}</p></div><div className="rounded-xl bg-green-50 p-3"><span className="text-xs font-bold text-green-700">E-SCREENING</span><p className="font-black text-green-700">{total.toFixed(2)}%</p></div></div><div className="mt-4 flex flex-wrap gap-3"><button onClick={()=>download("pdf")} className="rounded-xl bg-green-700 px-4 py-3 text-sm font-black text-white">Download PDF Report</button><button onClick={()=>download("jpg")} className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-black text-white">Download JPG Report</button></div></div></section>
 <aside className="space-y-5"><section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><p className="text-xs font-black uppercase tracking-wider text-green-700">How the checker works</p><h2 className="mt-2 text-xl font-black">LASUED calculation</h2><div className="mt-4 space-y-3 text-sm text-slate-600"><p><b>1. JAMB:</b> divide the UTME score by 8.</p><p><b>2. O'Level:</b> score the five relevant subjects from 10 to 5 points for A1 to C6.</p><p><b>3. E-Screening:</b> JAMB Average + total O'Level points.</p></div></section><section className="rounded-3xl bg-green-700 p-5 text-white"><h2 className="text-xl font-black">Need admission guidance?</h2><p className="mt-2 text-sm">Get help with LASUED screening, O'Level selection and admission guidance.</p><a className="mt-4 inline-block rounded-xl bg-white px-4 py-3 text-sm font-black !text-green-800" href="https://wa.me/2348182141088">Chat on WhatsApp</a></section></aside></div>
 <section className="mt-8 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><p className="text-xs font-black uppercase tracking-wider text-green-700">LASUED Admission Guide</p><h2 className="mt-2 text-2xl font-black">How to calculate your LASUED screening score</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><b>1. JAMB average</b><p className="mt-2 text-sm text-slate-600">Divide your total JAMB score by 8.</p></div><div className="rounded-2xl bg-slate-50 p-4"><b>2. O'Level points</b><p className="mt-2 text-sm text-slate-600">A1=10, B2=9, B3=8, C4=7, C5=6 and C6=5 across the five relevant subjects.</p></div><div className="rounded-2xl bg-green-50 p-4"><b>3. Assessment score</b><p className="mt-2 text-sm text-slate-600">Add the JAMB average and total O'Level score.</p></div></div><h2 className="mt-7 text-lg font-black">LASUED Screening Calculator FAQ</h2><details className="mt-3 rounded-xl bg-slate-50 px-4 py-3"><summary className="cursor-pointer text-sm font-bold">Does LASUED use a Post-UTME exam score?</summary><p className="mt-2 text-sm text-slate-600">This checker follows LASUED's online e-screening report method, which combines JAMB Average Score and O'Level points.</p></details><details className="mt-3 rounded-xl bg-slate-50 px-4 py-3"><summary className="cursor-pointer text-sm font-bold">Can I use two O'Level sittings?</summary><p className="mt-2 text-sm text-slate-600">LASUED's published admission requirement permits not more than two sittings.</p></details><p className="mt-5 text-xs text-slate-500">This tool is for admission guidance. Always confirm current admission requirements on the LASUED portal.</p></section>
 </div></main>
}