"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
const grades={"A1":8,"B2":7,"B3":6,"C4":5,"C5":4,"C6":3.5} as const;
const programmes=["Food Science and Technology","Horticulture and Landscape Management","Agribusiness","Forestry and Wildlife Management","Family and Consumer Science","Water Resources Management and Agro-Meteorology","Fisheries and Aquaculture","Agriculture","Accounting","Economics","Business Administration","Entrepreneurship","Peace Studies and Conflict Resolution","Computer Science","Mathematics","Physics with Electronics","Industrial Chemistry","Plant Science (Botany)","Animal and Environmental Biology (Zoology)","Chemistry","Biochemistry","Meteorology","Microbiology"];
const subjects=["English Language","Mathematics","Biology","Chemistry","Physics","Agricultural Science","Economics","Government","Commerce","Geography","Further Mathematics","Financial Accounting","Civic Education"];
export default function FUADSICalculator(){
 const [name,setName]=useState(""),[programme,setProgramme]=useState(""),[jamb,setJamb]=useState("");
 const [rows,setRows]=useState([{s:"English Language",g:""},{s:"Mathematics",g:""},{s:"",g:""},{s:"",g:""},{s:"",g:""}]);
 const j=Math.max(0,Math.min(400,Number(jamb)||0)); const jp=j*60/400;
 const op=useMemo(()=>rows.reduce((a,r)=>a+(grades[r.g as keyof typeof grades]||0),0),[rows]); const total=jp+op;
 const valid=rows.every(r=>r.s&&r.g)&&new Set(rows.map(r=>r.s)).size===5;
 const setRow=(i:number,k:"s"|"g",v:string)=>setRows(x=>x.map((r,n)=>n===i?{...r,[k]:v}:r));
 return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">
 <header className="overflow-hidden rounded-3xl bg-gradient-to-br from-green-700 via-green-600 to-emerald-500 p-6 text-white shadow-xl sm:p-8"><nav className="flex flex-wrap gap-2 text-sm font-bold"><Link className="rounded-full bg-white px-4 py-2 text-green-800" href="/">Home</Link><Link className="rounded-full bg-white/15 px-4 py-2" href="/screening-calculator">Screening Calculators</Link><Link className="rounded-full bg-white/15 px-4 py-2" href="/updates">Latest Updates</Link></nav><p className="mt-7 text-sm font-black uppercase tracking-widest text-green-100">S.O.H CONSULTS</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">FUADSI Screening Aggregate Calculator</h1><p className="mt-3 max-w-3xl text-green-50">Federal University of Agriculture and Development Studies, Iragbiji. Calculate your screening score from UTME and five relevant O'Level subjects.</p></header>
 <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 className="text-xl font-black">Candidate Information</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Candidate Name<input className="mt-2 w-full rounded-xl border border-slate-300 p-3 font-normal" value={name} onChange={e=>setName(e.target.value)} placeholder="Enter full name"/></label><label className="text-sm font-bold">Programme<select className="mt-2 w-full rounded-xl border border-slate-300 p-3 font-normal" value={programme} onChange={e=>setProgramme(e.target.value)}><option value="">Select programme</option>{programmes.map(x=><option key={x}>{x}</option>)}</select></label></div>
 <div className="mt-7 border-t pt-6"><h2 className="text-xl font-black">UTME Score</h2><input type="number" min="0" max="400" className="mt-3 w-full rounded-xl border border-slate-300 p-3" value={jamb} onChange={e=>setJamb(e.target.value)} placeholder="e.g. 211"/><p className="mt-2 text-sm text-slate-500">UTME contributes 60%. Current points: <b>{jp.toFixed(2)}/60</b></p></div>
 <div className="mt-7 border-t pt-6"><h2 className="text-xl font-black">O'Level Screening</h2><p className="mt-1 text-sm text-slate-600">Select five relevant subjects. English Language and Mathematics are compulsory.</p><div className="mt-4 space-y-3">{rows.map((r,i)=><div key={i} className="grid grid-cols-[1fr_110px] gap-3"><select disabled={i<2} className="rounded-xl border border-slate-300 p-3 disabled:bg-slate-100" value={r.s} onChange={e=>setRow(i,"s",e.target.value)}><option value="">Select subject</option>{subjects.map(x=><option key={x} disabled={rows.some((q,n)=>n!==i&&q.s===x)}>{x}</option>)}</select><select className="rounded-xl border border-slate-300 p-3" value={r.g} onChange={e=>setRow(i,"g",e.target.value)}><option value="">Grade</option>{Object.keys(grades).map(g=><option key={g} value={g}>{g}</option>)}</select></div>)}</div><p className="mt-3 text-sm text-slate-500">Grade points: A1=8, B2=7, B3=6, C4=5, C5=4, C6=3.5.</p></div>
 <div className="mt-7 border-t pt-6"><h2 className="text-lg font-black">Live Aggregate</h2><div className="mt-3 grid grid-cols-3 gap-2"><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs font-bold text-slate-500">UTME</span><p className="mt-1 font-black">{jp.toFixed(2)}/60</p></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs font-bold text-slate-500">O'LEVEL</span><p className="mt-1 font-black">{op.toFixed(1)}/40</p></div><div className="rounded-xl bg-green-50 p-3"><span className="text-xs font-bold text-green-700">SCREENING SCORE</span><p className="mt-1 font-black text-green-700">{total.toFixed(2)}%</p></div></div>{j>0&&j<150&&<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">FUADSI's 2026/2027 minimum UTME eligibility score is 150.</p>}{!valid&&<p className="mt-3 text-xs text-slate-500">Complete five unique subjects and grades for a complete screening estimate.</p>}</div></section>
 <aside className="space-y-5"><section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><p className="text-xs font-black uppercase tracking-wider text-green-700">How the checker works</p><h2 className="mt-2 text-xl font-black">FUADSI screening calculation</h2><div className="mt-4 space-y-3 text-sm text-slate-600"><p><b className="text-slate-900">1. UTME:</b> (score × 60) ÷ 400.</p><p><b className="text-slate-900">2. O'Level:</b> points from five relevant subjects, including English and Mathematics.</p><p><b className="text-slate-900">3. Score:</b> UTME points + O'Level points.</p></div></section><section className="rounded-3xl bg-green-700 p-5 text-white"><p className="text-xs font-black uppercase tracking-wider text-green-100">S.O.H CONSULTS</p><h2 className="mt-2 text-xl font-black">Need admission guidance?</h2><p className="mt-2 text-sm text-green-50">Get help with screening registration, O'Level selection and admission guidance.</p><a className="mt-4 inline-block rounded-xl bg-white px-4 py-3 text-sm font-black text-green-800" href="https://wa.me/2348182141088">Chat on WhatsApp</a></section></aside></div>
 <section className="mt-8 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><p className="text-xs font-black uppercase tracking-wider text-green-700">FUADSI Admission Guide</p><h2 className="mt-2 text-2xl font-black">How to calculate your FUADSI screening score</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><b>1. Calculate JAMB points</b><p className="mt-2 text-sm text-slate-600">Multiply your UTME score by 60 and divide by 400.</p></div><div className="rounded-2xl bg-slate-50 p-4"><b>2. Add O'Level points</b><p className="mt-2 text-sm text-slate-600">Use five core subjects. English and Mathematics are compulsory.</p></div><div className="rounded-2xl bg-green-50 p-4"><b>3. Screening score</b><p className="mt-2 text-sm text-slate-600">Add your UTME points and O'Level grade points.</p></div></div><h2 className="mt-7 text-lg font-black">FUADSI Screening Calculator FAQ</h2><details className="mt-3 rounded-xl bg-slate-50 px-4 py-3"><summary className="cursor-pointer text-sm font-bold">Does FUADSI write a Post-UTME examination?</summary><p className="mt-2 text-sm text-slate-600">This calculator is configured for the screening method supplied for FUADSI: UTME plus O'Level screening points. It does not request a Post-UTME exam score.</p></details><p className="mt-5 text-xs text-slate-500">This tool is for admission guidance. FUADSI's official 2026/2027 notice confirms a minimum UTME score of 150 and that the University conducts screening and notifies candidates of their aggregate scores. The detailed grade-point formula used here follows the screening formula supplied to S.O.H CONSULTS.</p></section>
 </div></main>}