"use client";
import {useMemo,useState} from "react"; import LasuStyleOLevel,{type OLevelResultEntry} from "../components/LasuStyleOLevel";

type Rule={utme:string;slots:string[][];olevel:string;note?:string};
const S=(...x:string[])=>x;
const commonAgri=S("Physics","Geography","Economics","Marketing","Data Processing/Computer Studies");
const engExtra=S("Biology/Agricultural Science","Technical Drawing","Further Mathematics","Economics","Computer Studies","Geography");
const mathsExtra=S("Further Mathematics","Chemistry","Biology/Agricultural Science","Economics","Geography","Computer Studies/Data Processing/ICT");
const socialExtra=S("Financial Accounting","Principles of Accounting","Business Methods","Commerce","Book Keeping","Marketing","Insurance","Government","Civic Education","Geography","Data Processing/Computer Studies","Office Practice","CRS/IRS","Agricultural Science/Biology/Physics");
const rules:Record<string,Rule>={
"Accounting":{utme:"English Language, Mathematics, Economics + Commerce/Government/Geography/Principles of Accounting",slots:[S("English Language"),S("Mathematics"),S("Economics"),socialExtra,socialExtra],olevel:"English Language, Mathematics, Economics and any two approved subjects, at not more than two sittings."},
"Actuarial Science":{utme:"English Language, Mathematics + any two of Economics, Principles of Accounting, Commerce, Government, Agricultural Science/Biology/Physics",slots:[S("English Language"),S("Mathematics"),S("Economics"),socialExtra,socialExtra],olevel:"English Language, Mathematics, Economics and any two approved subjects, at not more than two sittings."},
"Agricultural and Biosystems Engineering":{utme:"English Language, Physics, Chemistry and Mathematics",slots:[S("English Language"),S("Mathematics"),S("Physics"),S("Chemistry"),engExtra],olevel:"English Language, Mathematics, Physics, Chemistry and one approved science/technical subject, at not more than two sittings."},
"Agricultural Economics and Farm Management":{utme:"English Language, Chemistry, Biology/Agricultural Science + Mathematics/Physics/Economics",slots:[S("English Language"),S("Mathematics"),S("Chemistry"),S("Biology","Agricultural Science","Fisheries"),commonAgri],olevel:"English Language, Mathematics, Chemistry, Agriculture/Biology/Fisheries and one approved subject, at not more than two sittings."},
"Agricultural Extension and Rural Development":{utme:"English Language, Chemistry, Biology/Agricultural Science + Mathematics/Physics/Economics",slots:[S("English Language"),S("Mathematics"),S("Chemistry"),S("Biology","Agricultural Science","Fisheries"),commonAgri],olevel:"English Language, Mathematics, Chemistry, Agriculture/Biology/Fisheries and one approved subject, at not more than two sittings."},
"Animal Production":{utme:"English Language, Chemistry, Biology/Agricultural Science + Mathematics/Physics/Economics",slots:[S("English Language"),S("Mathematics"),S("Chemistry"),S("Biology","Agricultural Science","Fisheries"),commonAgri],olevel:"English Language, Mathematics, Chemistry, Agriculture/Biology/Fisheries and one approved subject, at not more than two sittings."},
"Aquaculture and Fisheries Management":{utme:"English Language, Chemistry, Biology/Agricultural Science, Physics/Mathematics",slots:[S("English Language"),S("Mathematics"),S("Chemistry"),S("Geography","Economics"),S("Biology","Agricultural Science","Fisheries")],olevel:"English Language, Mathematics, Chemistry, Geography/Economics and Biology/Agricultural Science/Fisheries; LASUSTECH states minimum P7 in Physics. Not more than two sittings.",note:"Physics requires at least P7 under the published requirement."},
"Architecture":{utme:"English Language, Mathematics, Physics + Chemistry/Geography/Biology/Economics/Further Mathematics",slots:[S("English Language"),S("Mathematics"),S("Physics"),S("Chemistry","Geography","Biology","Economics","Technical Drawing","Further Mathematics","Graphic Design","Plumbing & Pipe Fitting","Carpentry & Joinery","Painting & Decoration"),S("Chemistry","Geography","Biology","Economics","Technical Drawing","Further Mathematics","Graphic Design","Plumbing & Pipe Fitting","Carpentry & Joinery","Painting & Decoration")],olevel:"English Language, Mathematics, Physics and any two approved subjects, at not more than two sittings."},
"Art and Industrial Design":{utme:"English Language + any other three Arts, Science or Social Science subjects",slots:[S("English Language"),S("Mathematics"),S("Literature in English","Government","Economics","Biology","Chemistry","Physics","Geography","Fine Arts","CRS","IRS"),S("Literature in English","Government","Economics","Biology","Chemistry","Physics","Geography","Fine Arts","CRS","IRS"),S("Literature in English","Government","Economics","Biology","Chemistry","Physics","Geography","Fine Arts","CRS","IRS")],olevel:"English Language, Mathematics and any other three Arts, Science or Social Science subjects. Fine/Visual Arts is an added advantage."},
"Chemical Engineering":{utme:"English Language, Physics, Chemistry and Mathematics",slots:[S("English Language"),S("Mathematics"),S("Physics"),S("Chemistry"),engExtra],olevel:"English Language, Mathematics, Physics, Chemistry and one approved science/technical subject, at not more than two sittings."},
"Chemistry":{utme:"English Language, Chemistry + any two of Biology, Physics and Mathematics",slots:[S("English Language"),S("Mathematics"),S("Chemistry"),S("Physics"),S("Biology","Agricultural Science")],olevel:"English Language, Mathematics, Chemistry, Physics and Biology/Agricultural Science, at not more than two sittings."},
"Civil and Construction Engineering":{utme:"English Language, Physics, Chemistry and Mathematics",slots:[S("English Language"),S("Mathematics"),S("Physics"),S("Chemistry"),engExtra],olevel:"English Language, Mathematics, Physics, Chemistry and one approved science/technical subject, at not more than two sittings."},
"Computer Engineering":{utme:"English Language, Physics, Chemistry and Mathematics",slots:[S("English Language"),S("Mathematics"),S("Physics"),S("Chemistry"),engExtra],olevel:"English Language, Mathematics, Physics, Chemistry and one approved science/technical subject, at not more than two sittings."},
"Computer Science":{utme:"English Language, Mathematics, Physics and Chemistry",slots:[S("English Language"),S("Mathematics"),S("Physics"),S("Chemistry"),S("Biology","Agricultural Science","Further Mathematics","Technical Drawing","Computer Studies")],olevel:"English Language, Mathematics, Physics, Chemistry and one of Biology/Agriculture, Further Mathematics, Technical Drawing or Computer Studies, at not more than two sittings."},
"Crop Science":{utme:"English Language, Chemistry, Biology/Agricultural Science + Mathematics/Physics/Economics",slots:[S("English Language"),S("Mathematics"),S("Chemistry"),S("Biology","Agricultural Science","Fisheries"),commonAgri],olevel:"English Language, Mathematics, Chemistry, Agriculture/Biology/Fisheries and one approved subject, at not more than two sittings."},
"Economics":{utme:"English Language, Mathematics, Economics + one approved Social Science/Science subject",slots:[S("English Language"),S("Mathematics"),S("Economics"),socialExtra,socialExtra],olevel:"English Language, Mathematics, Economics and any two approved subjects, at not more than two sittings."},
"Electrical and Electronics Engineering":{utme:"English Language, Physics, Chemistry and Mathematics",slots:[S("English Language"),S("Mathematics"),S("Physics"),S("Chemistry"),engExtra],olevel:"English Language, Mathematics, Physics, Chemistry and one approved science/technical subject, at not more than two sittings."},
"Estate Management and Valuation":{utme:"English Language, Mathematics, Economics + Chemistry/Physics/Biology/Geography/Government",slots:[S("English Language"),S("Mathematics"),S("Economics"),S("Physics","Chemistry","Biology"),S("Government","History","Civic Education","Biology","Physics","Chemistry","Geography","Agricultural Science","Computer Studies","Data Processing","ICT","Technical Drawing","Literature in English","Principles of Accounts","Book Keeping","Financial Accounting")],olevel:"English Language, Mathematics, Economics, one basic science and one approved subject, at not more than two sittings."},
"Food Science and Technology":{utme:"English Language, Physics, Chemistry and Biology",slots:[S("English Language"),S("Mathematics"),S("Physics"),S("Chemistry"),S("Biology","Agricultural Science")],olevel:"English Language, Mathematics, Physics, Chemistry and Biology/Agricultural Science, at not more than two sittings."},
"Horticulture and Landscape Management":{utme:"English Language, Chemistry, Biology/Agricultural Science, Mathematics/Physics",slots:[S("English Language"),S("Mathematics"),S("Chemistry"),S("Biology","Agricultural Science"),S("Physics","Technical Drawing","Geography","Fine Art")],olevel:"English Language, Mathematics, Chemistry, Biology and Physics. Published exceptions allow D7/E8 Biology with credit Agricultural Science, and D7/E8 Physics with credit Technical Drawing, Geography or Fine Art.",note:"Special D7/E8 substitution rules apply to Biology and Physics."},
"Hospitality & Tourism Management":{utme:"English Language, Mathematics, Economics + one approved subject",slots:[S("English Language"),S("Mathematics"),S("Economics"),S("Geography","Financial Accounting","Commerce","Business Methods","Government","Physics","Chemistry","Biology","Agricultural Science","Food and Nutrition","Home Economics"),S("Geography","Financial Accounting","Commerce","Business Methods","Government","Physics","Chemistry","Biology","Agricultural Science","Food and Nutrition","Home Economics")],olevel:"English Language, Mathematics, Economics and any two approved subjects, at not more than two sittings."},
"Industrial Chemistry":{utme:"English Language, Chemistry, Mathematics + Biology/Agriculture/Physics",slots:[S("English Language"),S("Mathematics"),S("Chemistry"),S("Physics"),S("Biology","Agricultural Science")],olevel:"English Language, Mathematics, Chemistry, Physics and Biology/Agricultural Science, at not more than two sittings."},
"Industrial Mathematics":{utme:"English Language, Mathematics, Physics + Chemistry/Biology/Geography/Economics",slots:[S("English Language"),S("Mathematics"),S("Physics"),mathsExtra,mathsExtra],olevel:"English Language, Mathematics, Physics and any other two approved subjects, at not more than two sittings."},
"Insurance":{utme:"English Language, Mathematics, Economics + Principles of Accounting/Commerce/Government/Agricultural Science/Biology/Physics",slots:[S("English Language"),S("Mathematics"),S("Economics"),socialExtra,socialExtra],olevel:"English Language, Mathematics, Economics and any two approved subjects, at not more than two sittings."},
"Marketing":{utme:"English Language, Mathematics + any two of Economics, Commerce, Government and Principles of Accounting",slots:[S("English Language"),S("Mathematics"),S("Economics"),socialExtra,socialExtra],olevel:"English Language, Mathematics, Economics and any two approved subjects, at not more than two sittings."},
"Mass Communication":{utme:"English Language + any three approved Arts/Social Science subjects",slots:[S("English Language"),S("Mathematics"),S("Literature in English","History","Financial Accounting","Economics","Commerce","Government","Civic Education","Geography","Data Processing","Computer Studies","Statistics","CRS","IRS","Fine Arts","French","Yoruba","Igbo","Hausa"),S("Literature in English","History","Financial Accounting","Economics","Commerce","Government","Civic Education","Geography","Data Processing","Computer Studies","Statistics","CRS","IRS","Fine Arts","French","Yoruba","Igbo","Hausa"),S("Literature in English","History","Financial Accounting","Economics","Commerce","Government","Civic Education","Geography","Data Processing","Computer Studies","Statistics","CRS","IRS","Fine Arts","French","Yoruba","Igbo","Hausa")],olevel:"English Language, Mathematics and any three approved subjects, at not more than two sittings."},
"Mathematics":{utme:"English Language, Mathematics, Physics + Chemistry/Biology/Geography/Economics",slots:[S("English Language"),S("Mathematics"),S("Physics"),mathsExtra,mathsExtra],olevel:"English Language, Mathematics, Physics and any other two approved subjects, at not more than two sittings."},
"Mechanical Engineering":{utme:"English Language, Physics, Chemistry and Mathematics",slots:[S("English Language"),S("Mathematics"),S("Physics"),S("Chemistry"),engExtra],olevel:"English Language, Mathematics, Physics, Chemistry and one approved science/technical subject, at not more than two sittings."},
"Mechatronics Engineering":{utme:"English Language, Physics, Chemistry and Mathematics",slots:[S("English Language"),S("Mathematics"),S("Physics"),S("Chemistry"),engExtra],olevel:"English Language, Mathematics, Physics, Chemistry and one approved science/technical subject, at not more than two sittings."},
"Microbiology":{utme:"English Language, Biology/Agriculture, Chemistry and Physics",slots:[S("English Language"),S("Mathematics"),S("Biology","Agricultural Science"),S("Chemistry"),S("Physics","Geography","Further Mathematics","Food and Nutrition","Economics","Health Science")],olevel:"English Language, Mathematics, Biology/Agriculture, Chemistry and one approved subject, at not more than two sittings."},
"Office and Information Technology":{utme:"English Language, Mathematics, Economics + one approved subject",slots:[S("English Language"),S("Mathematics"),S("Economics"),socialExtra,S("Financial Accounting","Commerce","Government","Civic Education","Geography","Data Processing","Computer Studies","Office Practice","Typewriting","Shorthand","CRS","IRS","Agricultural Science","Biology","Physics")],olevel:"English Language, Mathematics, Economics and any two approved subjects, at not more than two sittings."},
"Physics with Electronics":{utme:"English Language, Mathematics, Physics and Chemistry",slots:[S("English Language"),S("Mathematics"),S("Physics"),S("Chemistry"),S("Biology","Agricultural Science","Further Mathematics","Technical Drawing","Economics","Data Processing","Computer Studies")],olevel:"English Language, Mathematics, Physics, Chemistry and one approved subject, at not more than two sittings."},
"Quantity Surveying":{utme:"English Language, Mathematics + any two of Chemistry, Physics, Biology and Geography",slots:[S("English Language"),S("Mathematics"),S("Physics"),S("Building Construction","Technical Drawing","Economics","Computer Studies","Geography","Chemistry","Biology","Commerce"),S("Building Construction","Technical Drawing","Economics","Computer Studies","Geography","Chemistry","Biology","Commerce")],olevel:"English Language, Mathematics, Physics and two approved subjects, at not more than two sittings."},
"Statistics":{utme:"English Language, Mathematics, Physics + Chemistry/Biology/Geography/Economics",slots:[S("English Language"),S("Mathematics"),S("Physics"),mathsExtra,mathsExtra],olevel:"English Language, Mathematics, Physics and any other two approved subjects, at not more than two sittings."},
"Urban and Regional Planning":{utme:"English Language, Mathematics + any two approved subjects",slots:[S("English Language"),S("Mathematics"),S("Geography"),S("Physics","Chemistry","Biology","Economics","Commerce","Further Mathematics","Data Processing","Agricultural Science","ICT","Civic Education","Fine Art","Technical Drawing","History","Government","Marketing","Computer Studies","Home Economics"),S("Physics","Chemistry","Biology","Economics","Commerce","Further Mathematics","Data Processing","Agricultural Science","ICT","Civic Education","Fine Art","Technical Drawing","History","Government","Marketing","Computer Studies","Home Economics")],olevel:"English Language, Mathematics, Geography and any two approved subjects, at not more than two sittings."},
"Zoology":{utme:"English Language, Biology/Agriculture, Chemistry and Physics",slots:[S("English Language"),S("Mathematics"),S("Biology","Agricultural Science"),S("Chemistry"),S("Physics","Geography","Further Mathematics","Food and Nutrition","Economics","Health Science")],olevel:"English Language, Mathematics, Biology/Agriculture, Chemistry and one approved subject, at not more than two sittings."}
};
const grades=["","A1","B2","B3","C4","C5","C6","D7","E8","F9"];
const pts:Record<string,number>={A1:8,B2:7.2,B3:6.7,C4:6.2,C5:5.7,C6:5.2,D7:0,E8:0,F9:0};
const programmes=Object.keys(rules).sort();
const olevelSubjects=["English Language","Mathematics","Physics","Chemistry","Biology","Agricultural Science","Economics","Commerce","Government","Geography","Financial Accounting","Principles of Accounting","Book Keeping","Business Methods","Marketing","Insurance","Civic Education","Data Processing","Computer Studies","ICT","Office Practice","Typewriting","Shorthand","Literature in English","History","CRS","IRS","Fine Arts","French","Yoruba","Igbo","Hausa","Further Mathematics","Technical Drawing","Building Construction","Food and Nutrition","Home Economics","Health Science","Fisheries","Statistics"];
const utmeSubjects=["English Language","Mathematics","Physics","Chemistry","Biology","Agricultural Science","Economics","Commerce","Government","Geography","Principles of Accounting","Literature in English","History","CRS","IRS","French","Fine Arts","Yoruba","Igbo","Hausa","Further Mathematics"];
function okGrade(g:string){return ["A1","B2","B3","C4","C5","C6"].includes(g)}
export default function LASUSTECHCalculator(){
 const [name,setName]=useState(""); const [programme,setProgramme]=useState(""); const [jamb,setJamb]=useState("");
 const [utme,setUtme]=useState(["English Language","","",""]); const [sittings,setSittings]=useState<1|2>(1); const [results,setResults]=useState<OLevelResultEntry[]>([]); const entered=results.filter(x=>x.subject&&x.grade);
 const r=rules[programme]; const jambN=Number(jamb)||0; const jambPts=jambN*.15; const relevant=r?entered.filter(e=>r.slots.some(slot=>slot.some(a=>a.split("/").map(x=>x.trim()).includes(e.subject)))):entered; const bestBySubject=useMemo(()=>{const m=new Map<string,OLevelResultEntry>();relevant.forEach(e=>{const old=m.get(e.subject);if(!old||(pts[e.grade]||0)>(pts[old.grade]||0))m.set(e.subject,e)});return [...m.values()]},[relevant]); const bestFive=[...bestBySubject].sort((a,b)=>(pts[b.grade]||0)-(pts[a.grade]||0)).slice(0,5); const oPts=bestFive.reduce((a,e)=>a+(pts[e.grade]||0),0); const aggregate=jambPts+oPts;
 const oEligible=useMemo(()=>{if(!r)return false; return r.slots.every((allowed,i)=>entered.some(e=>allowed.some(a=>a.split("/").map(x=>x.trim()).includes(e.subject))&&(okGrade(e.grade)||(programme==="Horticulture and Landscape Management"&&(i===3||i===4)&&["D7","E8"].includes(e.grade)))))},[r,entered,programme]);
 const uEligible=useMemo(()=>{if(!r)return false; const text=r.utme.toLowerCase(); const chosen=utme.map(x=>x.toLowerCase()); const mandatory=["english language",...(text.includes("mathematics")?["mathematics"]:[]),...(text.includes("physics")&&["engineering","computer science","physics with electronics","food science and technology"].includes(programme.toLowerCase())?["physics"]:[])]; return mandatory.every(x=>chosen.includes(x))&&new Set(utme.filter(Boolean)).size===4},[r,utme,programme]);
 const complete=!!r&&jambN>0&&bestFive.length===5&&utme.every(Boolean);
 function pickProgramme(v:string){setProgramme(v);setResults([]);setUtme(["English Language","","",""])}
 return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl">
 <header className="overflow-hidden rounded-3xl bg-gradient-to-br from-green-700 via-green-600 to-emerald-500 p-6 text-white shadow-xl sm:p-8"><nav className="mb-6 flex flex-wrap gap-3"><a href="/" className="rounded-full bg-white px-4 py-2 text-sm font-black !text-green-700">Home</a><a href="/screening-calculator" className="rounded-full bg-white/15 px-4 py-2 text-sm font-black text-white">Screening Calculators</a></nav><p className="text-sm font-bold uppercase tracking-[.2em] text-green-100">S.O.H CONSULTS</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">LASUSTECH Screening & Eligibility Calculator</h1><p className="mt-3 max-w-3xl text-green-50">Check your programme-specific UTME and O'Level requirements and calculate your LASUSTECH screening aggregate.</p></header>
 <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><section className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200 sm:p-8">
 <h2 className="text-2xl font-black">Candidate Information</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="font-bold">Candidate Name<input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal" placeholder="Enter candidate name"/></label><label className="font-bold">Programme<select value={programme} onChange={e=>pickProgramme(e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal"><option value="">Select programme</option>{programmes.map(p=><option key={p}>{p}</option>)}</select></label></div>
 {r&&<div className="mt-6 rounded-2xl bg-green-50 p-5"><h3 className="font-black text-green-800">Official programme requirements</h3><p className="mt-2 text-sm"><b>UTME:</b> {r.utme}</p><p className="mt-2 text-sm"><b>O'Level:</b> {r.olevel}</p>{r.note&&<p className="mt-2 text-sm font-bold text-amber-800">{r.note}</p>}</div>}
 <hr className="my-7"/><h2 className="text-2xl font-black">UTME Details</h2><label className="mt-4 block font-bold">JAMB Score (0-400)<input type="number" min="0" max="400" value={jamb} onChange={e=>setJamb(e.target.value)} className="mt-2 w-full rounded-xl border p-3" placeholder="e.g. 207"/></label>
 <div className="mt-4 grid gap-3 sm:grid-cols-2">{utme.map((v,i)=><label key={i} className="text-sm font-bold">UTME Subject {i+1}<select value={v} onChange={e=>{const a=[...utme];a[i]=e.target.value;setUtme(a)}} className="mt-1 w-full rounded-xl border p-3 font-normal"><option value="">Select subject</option>{utmeSubjects.map(x=><option key={x}>{x}</option>)}</select></label>)}</div>
 <hr className="my-7"/><h2 className="text-2xl font-black">O'Level Screening Subjects</h2><p className="mt-2 text-sm text-slate-500">Choose one or two sittings, then enter 5 to 9 O'Level subjects and grades. The checker uses the best five relevant subjects and validates them against the selected programme requirements.</p>
 <LasuStyleOLevel subjects={olevelSubjects} grades={grades.filter(Boolean)} value={results} onChange={setResults} sittings={sittings} onSittingsChange={setSittings} note="Select 2 Sittings to enter the first and second O-Level results separately. Enter up to 9 subjects in each sitting. The checker selects the best five relevant subjects for the programme."/>{programme&&<div className="mt-7 rounded-3xl bg-slate-950 p-6 text-white"><p className="text-xs font-black uppercase tracking-widest text-green-300">Live Screening Aggregate</p><p className="mt-2 text-5xl font-black">{aggregate.toFixed(2)}%</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-white/10 p-3">JAMB contribution<br/><b>{jambPts.toFixed(2)} / 60</b></div><div className="rounded-xl bg-white/10 p-3">O'Level points<br/><b>{oPts.toFixed(2)} / 40</b></div></div><p className={"mt-4 font-black "+(complete&&oEligible&&uEligible?"text-green-300":"text-amber-300")}>{!complete?"Complete all fields to check eligibility.":oEligible&&uEligible?"SUBJECT REQUIREMENTS SATISFIED":"CHECK SUBJECT REQUIREMENTS"}</p><p className="mt-2 text-xs text-slate-300">This checker assesses published subject requirements and computes the screening score. It does not guarantee admission.</p></div>}
 </section>
 <aside className="space-y-6"><div className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><p className="text-sm font-black uppercase tracking-wider text-green-700">How the checker works</p><h2 className="mt-2 text-2xl font-black">LASUSTECH calculation</h2><p className="mt-4 text-sm leading-7"><b>1. JAMB:</b> score × 0.15, maximum 60 points.<br/><b>2. O'Level:</b> five relevant subjects, maximum 40 points.<br/><b>3. Aggregate:</b> JAMB points + O'Level points.</p><div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm"><b>Grade points</b><br/>A1=8, B2=7.2, B3=6.7, C4=6.2, C5=5.7, C6=5.2. Others=0.</div></div><div className="rounded-3xl bg-green-700 p-6 text-white"><p className="text-sm font-black">S.O.H CONSULTS</p><h3 className="mt-2 text-2xl font-black">Need admission guidance?</h3><p className="mt-2 text-sm text-green-50">Get help with screening, requirements and application guidance.</p><a href="https://wa.me/2348182141088" className="mt-5 inline-block rounded-xl bg-white px-5 py-3 font-black !text-green-700">Chat on WhatsApp</a></div></aside></div>
 <section className="mt-8 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200 sm:p-8"><h2 className="text-2xl font-black">LASUSTECH Admission Guide</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-5"><b>1. Select your programme</b><p className="mt-2 text-sm">The checker loads that programme's published UTME and O'Level requirements.</p></div><div className="rounded-2xl bg-slate-50 p-5"><b>2. Enter your results</b><p className="mt-2 text-sm">Provide your JAMB score, UTME subjects and the five relevant O'Level grades.</p></div><div className="rounded-2xl bg-slate-50 p-5"><b>3. Review the result</b><p className="mt-2 text-sm">See your calculated aggregate and whether your subject requirements are satisfied.</p></div></div><h2 className="mt-8 text-2xl font-black">LASUSTECH Calculator FAQ</h2><p className="mt-4"><b>What formula is used?</b><br/><span className="text-sm text-slate-600">JAMB score × 0.15 plus the points from five relevant O'Level subjects.</span></p><p className="mt-4"><b>Does a qualifying result guarantee admission?</b><br/><span className="text-sm text-slate-600">No. It only checks the configured academic requirements and screening calculation. Final admission remains with LASUSTECH/JAMB.</span></p></section>
 </div></main>
}