import type {Metadata} from "next";
import {notFound,permanentRedirect} from "next/navigation";
import {getPublishedStoryBySlug,getStorySlug,listPublishedStories} from "../../../lib/news-queue";
import {getGalleryImages} from "../../../lib/story-gallery";
import {readArticleBlocks} from "../../../lib/article-blocks";
import StructuredArticle from "./StructuredArticle";
import ShareButtons from "../../components/ShareButtons";
import SiteContact from "../../components/SiteContact";
import {getSiteUrl} from "../../site-url";
const whatsappLink=(message:string)=>`https://wa.me/2348182141088?text=${encodeURIComponent(message)}`;
type Props={params:Promise<{id:string}>};
export const dynamic="force-dynamic";
export async function generateStaticParams(){return [];}
async function resolveStory(id:string){let story=await getPublishedStoryBySlug(id);if(!story&&/^\d+$/.test(id)){const stories=await listPublishedStories();story=stories.find(item=>item.source_url.startsWith(`legacy:${id}:`))||null;}return story;}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {id}=await params;const story=await resolveStory(id);if(!story)return{title:"Update Not Found"};const slug=getStorySlug(story),image=story.image_url||"/soh-logo.jpg";return{title:story.title,...(story.summary?{description:story.summary}:{}),alternates:{canonical:`/updates/${slug}`},openGraph:{type:"article",title:story.title,...(story.summary?{description:story.summary}:{}),url:`/updates/${slug}`,images:[{url:image,alt:story.title}]},twitter:{card:"summary_large_image",title:story.title,...(story.summary?{description:story.summary}:{}),images:[image]}};}
export default async function UpdateDetailsPage({params}:Props){
 const {id}=await params;const story=await resolveStory(id);if(!story)notFound();const slug=getStorySlug(story);if(id!==slug)permanentRedirect(`/updates/${slug}`);
 const pageUrl=`${getSiteUrl()}/updates/${slug}`;const structured=readArticleBlocks(story.details)!==null;
 const gallery=[...new Set([...(story.image_url?[story.image_url]:[]),...getGalleryImages(story.details)])].slice(0,5);const [featuredImage,...supportingImages]=gallery;
 const related=(await listPublishedStories()).filter(item=>item.id!==story.id&&item.category===story.category).slice(0,4);
 const publishedDate=new Date(story.source_published_at||story.updated_at).toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"});
 return <main className="min-h-screen min-w-0 bg-gray-50 text-gray-900"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-3 sm:px-5 sm:py-4"><a href="/" aria-label="S.O.H CONSULTS homepage"><img src="/soh-logo.jpg" alt="S.O.H CONSULTS" className="h-12 w-auto sm:h-16"/></a><a href={whatsappLink(`Hello S.O.H CONSULTS, I need help with: ${story.title}`)} target="_blank" rel="noopener noreferrer" className="shrink-0 rounded-full bg-green-700 px-4 py-3 text-xs font-black text-white sm:px-5 sm:text-sm">WhatsApp Us</a></div></header>
 <section className="bg-gradient-to-br from-green-950 to-green-700 py-9 text-white sm:py-14"><div className="mx-auto max-w-6xl px-4 sm:px-5"><a href="/updates" className="text-sm font-bold text-green-100">← Back to Latest Updates</a><p className="mt-5 break-words text-xs font-black text-green-200 sm:mt-6 sm:text-sm">{story.category} · {story.institution} · {publishedDate}</p><h1 className="mt-4 break-words text-3xl font-black leading-tight sm:text-5xl">{story.title}</h1>{Boolean(story.summary?.trim())&&<p className="mt-4 max-w-4xl break-words text-lg leading-8 text-green-50 sm:mt-5 sm:text-xl sm:leading-9">{story.summary}</p>}</div></section>
 <section className="py-6 sm:py-12"><div className="mx-auto grid max-w-6xl grid-cols-1 items-start gap-6 px-4 sm:px-5 lg:grid-cols-[minmax(0,1fr)_280px] lg:gap-8"><article className="min-w-0 rounded-2xl border bg-white p-4 shadow-sm sm:rounded-3xl sm:p-8 lg:p-10">{featuredImage&&<img src={featuredImage} alt={`${story.title} featured image`} className="mb-8 max-h-[540px] w-full rounded-2xl border bg-white object-contain shadow-sm"/>}<StructuredArticle details={story.details}/>{!structured&&supportingImages.length>0&&<div className="mt-10 grid grid-cols-1 gap-4 sm:grid-cols-2" aria-label="Supporting update pictures">{supportingImages.map((url,i)=><img key={`${url}-${i}`} src={url} alt={`${story.title} supporting picture ${i+1}`} className="max-h-[460px] w-full rounded-2xl border bg-white object-contain shadow-sm"/>)}</div>}
 {story.deadline&&<div className="mt-8 rounded-2xl bg-amber-50 p-5"><p className="text-xs font-black uppercase text-amber-800">Application deadline</p><p className="mt-2 text-lg font-black">{story.deadline}</p></div>}{story.document_url&&<a href={story.document_url} target="_blank" rel="noopener noreferrer" className="mt-8 flex w-full items-center justify-center rounded-2xl border-2 border-green-700 px-4 py-4 text-center font-black text-green-700 sm:px-6">View or Download {story.document_name||"Supporting Document"} →</a>}<div className="mt-8 rounded-2xl bg-green-50 p-5 sm:p-6"><h2 className="text-xl font-black">Need registration assistance?</h2><a href={whatsappLink(`Hello S.O.H CONSULTS, I need assistance with: ${story.title}`)} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex rounded-xl bg-green-700 px-5 py-3 font-black text-white">Chat on WhatsApp</a></div>{story.official_source_name&&<div className="mt-8 border-t pt-6"><p className="text-sm font-bold text-gray-500">Official source</p>{story.official_source_url?<a href={story.official_source_url} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex break-all font-black text-green-700">{story.official_source_name} →</a>:<p className="mt-2 break-words font-black text-green-700">{story.official_source_name}</p>}</div>}<div className="mt-8 border-t pt-6"><ShareButtons url={pageUrl} title={story.title}/></div></article><aside aria-label="Related updates" className="min-w-0 rounded-2xl border bg-white p-5 shadow-sm lg:sticky lg:top-6"><h2 className="text-xl font-black text-green-950">Related Updates</h2><p className="mt-1 text-sm text-gray-600">More {story.category} news</p><div className="mt-4 divide-y">{related.length?related.map(item=><a key={item.id} href={`/updates/${getStorySlug(item)}`} className="block py-4 first:pt-0 hover:text-green-700"><span className="block break-words font-bold leading-6">{item.title}</span><span className="mt-1 block text-xs text-gray-500">{item.institution}</span></a>):<p className="py-4 text-sm text-gray-600">No related updates yet.</p>}</div><a href="/updates" className="mt-4 inline-flex rounded-lg bg-green-700 px-4 py-3 text-sm font-bold text-white">View all updates →</a></aside></div></section><SiteContact/></main>;
}
