import {readArticleBlocks,removeArticleBlocks} from "../../../lib/article-blocks";
import {cleanGalleryDetails} from "../../../lib/story-gallery";

function Paragraph({text}:{text:string}){return <p className="whitespace-pre-line break-words text-[18px] leading-8 text-gray-800 sm:text-xl sm:leading-10">{text.split(/(https?:\/\/[^\s]+)/g).map((part,index)=>part.startsWith("http")?<a key={index} href={part.replace(/[.,;:]$/,"")} target="_blank" rel="noopener noreferrer" className="break-all font-bold text-green-700 underline">{part}</a>:part)}</p>}
export default function StructuredArticle({details}:{details:string}){
 const blocks=readArticleBlocks(details);
 if(!blocks){const legacy=removeArticleBlocks(cleanGalleryDetails(details)).replace(/\[SOH:(?:FEATURED|BREAKING)\]\s*/gi,"").replace(/\[(?:SCHEDULE|EXPIRES):\s*[^\]]+\]\s*/gi,"").trim();return <div className="space-y-7">{legacy.split("\n\n").map((part,index)=>part.trim()).filter(Boolean).map((part,index)=>part===part.toUpperCase()&&part.length<=80?<h2 key={index} className="break-words pt-6 text-2xl font-black sm:text-3xl">{part}</h2>:<Paragraph key={index} text={part}/>)}</div>}
 return <div className="space-y-7">{blocks.map((block,index)=>block.type==="paragraph"?<Paragraph key={index} text={block.text}/>:block.type==="heading"?<h2 key={index} className="break-words pt-5 text-2xl font-black leading-tight text-gray-950 sm:text-3xl">{block.text}</h2>:block.type==="image"?<figure key={index}><img src={block.url} alt={block.alt||"Article picture"} className="max-h-[650px] w-full rounded-2xl border bg-white object-contain"/>{block.alt&&<figcaption className="mt-2 text-center text-sm text-gray-600">{block.alt}</figcaption>}</figure>:block.type==="gallery"?<div key={index} className="grid grid-cols-1 gap-4 sm:grid-cols-2">{block.urls.map((url,i)=><img key={`${url}-${i}`} src={url} alt={`Article gallery picture ${i+1}`} className="max-h-[500px] w-full rounded-2xl border bg-white object-contain"/>)}</div>:<div key={index} aria-label="Reserved advertising space" className="rounded-xl border border-dashed border-gray-200 p-4 text-center text-xs text-gray-500">Advertisement space</div>)}</div>;
}
