import {readArticleBlocks,removeArticleBlocks,type Typography} from "../../../lib/article-blocks";
import {cleanGalleryDetails} from "../../../lib/story-gallery";
import RichText from "./RichText";
const fontFamilies: Record<NonNullable<Typography["font"]>,string> = {Arial:"Arial, sans-serif",Georgia:"Georgia, serif",Verdana:"Verdana, sans-serif","Trebuchet MS":"'Trebuchet MS', sans-serif","Times New Roman":"'Times New Roman', serif"};
const colors: Record<NonNullable<Typography["color"]>,string> = {default:"#1f2937",green:"#166534",blue:"#1d4ed8",red:"#b91c1c"};
const heights = {normal:1.5,relaxed:1.8,loose:2} as const;
function textStyle(block:Typography){return {fontFamily:block.font?fontFamilies[block.font]:undefined,fontSize:block.size?(block.size>24?`clamp(20px, 5vw, ${block.size}px)`:`${block.size}px`):undefined,textAlign:block.align||undefined,color:block.color?colors[block.color]:undefined,lineHeight:block.spacing?heights[block.spacing]:undefined,backgroundColor:block.highlight?"#fef08a":undefined} as const;}
function Paragraph({text,formatted=false,typography}:{text:string;formatted?:boolean;typography?:Typography}){const className="whitespace-pre-line break-words text-[18px] leading-8 text-gray-800 sm:text-xl sm:leading-10";if(formatted)return <div className={className} style={textStyle(typography||{})}><RichText text={text}/></div>;return <p className={className}>{text.split(/(https?:\/\/[^\s]+)/g).map((part,index)=>part.startsWith("http")?<a key={index} href={part.replace(/[.,;:]$/,"")} target="_blank" rel="noopener noreferrer" className="break-all font-bold text-green-700 underline">{part}</a>:part)}</p>}
export default function StructuredArticle({details}:{details:string}){const blocks=readArticleBlocks(details);if(!blocks){const legacy=removeArticleBlocks(cleanGalleryDetails(details)).replace(/\[SOH:(?:FEATURED|BREAKING)\]\s*/gi,"").replace(/\[(?:SCHEDULE|EXPIRES):\s*[^\]]+\]\s*/gi,"").trim();return <div className="space-y-7">{legacy.split("\n\n").map(part=>part.trim()).filter(Boolean).map((part,index)=>part===part.toUpperCase()&&part.length<=80?<h2 key={index} className="break-words pt-6 text-2xl font-black sm:text-3xl">{part}</h2>:<Paragraph key={index} text={part}/>)}</div>;}return <div className="space-y-7">{blocks.map((block,index)=>block.type==="paragraph"?<Paragraph key={index} text={block.text} formatted typography={block}/>:block.type==="heading"?<h2 key={index} style={textStyle(block)} className="break-words pt-5 text-2xl font-black leading-tight text-gray-950 sm:text-3xl"><RichText text={block.text} heading/></h2>:block.type==="image"?<figure key={index}><img src={block.url} alt={block.alt||"Article picture"} className="max-h-[650px] w-full rounded-2xl border bg-white object-contain"/>{block.alt&&<figcaption className="mt-2 text-center text-sm text-gray-600">{block.alt}</figcaption>}</figure>:block.type==="gallery"?<div key={index} className="grid grid-cols-1 gap-4 sm:grid-cols-2">{block.urls.map((url,i)=><img key={`${url}-${i}`} src={url} alt={`Article gallery picture ${i+1}`} className="max-h-[500px] w-full rounded-2xl border bg-white object-contain"/>)}</div>:<div key={index} aria-label="Reserved advertising space" className="rounded-xl border border-dashed border-gray-200 p-4 text-center text-xs text-gray-500">Advertisement space</div>)}</div>;}
