import {articleAdPositions} from "../../../lib/article-ad-positions";
import ArticleAd from "../../components/ArticleAd";
import {readArticleBlocks,removeArticleBlocks,type Typography} from "../../../lib/article-blocks";
import {cleanGalleryDetails} from "../../../lib/story-gallery";
import RichText from "./RichText";
import GalleryCarousel from "./GalleryCarousel";
const fontFamilies: Record<NonNullable<Typography["font"]>,string> = {Arial:"Arial, sans-serif",Georgia:"Georgia, serif",Verdana:"Verdana, sans-serif","Trebuchet MS":"'Trebuchet MS', sans-serif","Times New Roman":"'Times New Roman', serif"};
const colors: Record<NonNullable<Typography["color"]>,string> = {default:"#1f2937",green:"#166534",blue:"#1d4ed8",red:"#b91c1c"};
const heights = {normal:1.5,relaxed:1.8,loose:2} as const;
function textStyle(block:Typography){return {fontFamily:block.font?fontFamilies[block.font]:undefined,fontSize:block.size?(block.size>24?`clamp(20px, 5vw, ${block.size}px)`:`${block.size}px`):undefined,textAlign:block.align||undefined,color:block.color?colors[block.color]:undefined,lineHeight:block.spacing?heights[block.spacing]:undefined,backgroundColor:block.highlight?"#fef08a":undefined} as const;}
function Paragraph({text,formatted=false,typography}:{text:string;formatted?:boolean;typography?:Typography}){const className="whitespace-pre-line break-normal [overflow-wrap:normal] [word-break:normal] text-[18px] leading-8 text-gray-800 sm:text-xl sm:leading-10";if(formatted)return <div className={className} style={textStyle(typography||{})}><RichText text={text}/></div>;return <p className={className}>{text.split(/(https?:\/\/[^\s]+)/g).map((part,index)=>part.startsWith("http")?<a key={index} href={part.replace(/[.,;:]$/,"")} target="_blank" rel="noopener noreferrer" className="soh-article-link">{part}</a>:part)}</p>}
export default function StructuredArticle({details,adsEnabled=false}:{details:string;adsEnabled?:boolean}){const blocks=readArticleBlocks(details);if(!blocks){const legacy=removeArticleBlocks(cleanGalleryDetails(details)).replace(/\[SOH:(?:FEATURED|BREAKING)\]\s*/gi,"").replace(/\[(?:SCHEDULE|EXPIRES):\s*[^\]]+\]\s*/gi,"").trim();return <div className="space-y-7">{legacy.split("\n\n").map(part=>part.trim()).filter(Boolean).map((part,index)=>part===part.toUpperCase()&&part.length<=80?<h2 key={index} className="break-words pt-6 text-2xl font-black sm:text-3xl">{part}</h2>:<Paragraph key={index} text={part}/>)}</div>;}const adPositions=articleAdPositions(blocks);return <div className="space-y-7">{blocks.map((block,index)=>block.type==="paragraph"?<Paragraph key={index} text={block.text} formatted typography={block}/>:block.type==="heading"?<h2 key={index} style={textStyle(block)} className="break-words pt-5 text-2xl font-black leading-tight text-gray-950 sm:text-3xl"><RichText text={block.text} heading/></h2>:block.type==="image"?<figure key={index}><img src={block.url} alt={block.alt||"Article picture"} loading="lazy" decoding="async" className="max-h-[650px] w-full rounded-2xl border bg-white object-contain"/>{block.alt&&<figcaption className="mt-2 text-center text-sm text-gray-600">{block.alt}</figcaption>}</figure>:block.type==="gallery"?<GalleryCarousel key={index} urls={block.urls}/>:block.type==="document"?<a key={index} href={block.url} target="_blank" rel="noopener noreferrer" className="soh-article-link flex min-h-12 items-center gap-3 rounded-xl border border-green-200 bg-green-50 p-4 font-bold break-words"><span aria-hidden="true">📄</span>Open PDF: {block.name||"Article attachment"}</a>:block.type==="video"?<figure key={index} className="space-y-2">{block.mode==="player"?<video controls playsInline preload="metadata" src={block.url} aria-label={block.title||"Article video"} className="max-h-[650px] w-full rounded-xl bg-black"><a href={block.url}>Open video</a></video>:<a href={block.url} target="_blank" rel="noopener noreferrer" className="soh-article-link inline-flex min-h-12 items-center rounded-xl border border-green-200 bg-green-50 p-4 font-bold">▶ Watch video: {block.title||"Open video"}</a>}{block.mode==="player"&&block.title&&<figcaption className="text-sm text-gray-600">{block.title}</figcaption>}</figure>:block.type==="ad"&&adPositions.has(index)?<ArticleAd key={index} slot={block.slot} enabled={adsEnabled}/>:null)}</div>;}
