"use client";
import {useState} from "react";
import ArticleBlockEditor from "../ArticleBlockEditor";
import ArticleLivePreview from "../ArticleLivePreview";
import MediaPicker from "../MediaPicker";
import DuplicateReview from "../DuplicateReview";
import {writeArticleBlocks,type ArticleBlock} from "../../../../lib/article-blocks";
const field="mt-1 w-full min-w-0 rounded-xl border border-gray-300 bg-white p-3 text-base text-gray-950 focus:border-green-700 focus:outline-none focus:ring-2 focus:ring-green-200";
export default function NewStructuredUpdate(){
 const [form,setForm]=useState({title:"",institution:"",category:"Admission",summary:"",deadline:"",official_source_name:"",official_source_url:""});const [blocks,setBlocks]=useState<ArticleBlock[]>([{type:"paragraph",text:""}]);const [featured,setFeatured]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 function change(key:keyof typeof form,value:string){setForm(current=>({...current,[key]:value}));}
 async function upload(file:File){setBusy(true);setMessage("Uploading featured image...");try{const data=new FormData();data.append("file",file);data.append("kind","image");const response=await fetch("/api/admin/uploads",{method:"POST",body:data});const result=await response.json();if(!response.ok||!result.url)throw Error(result.error||"Upload failed");setFeatured(result.url);setMessage("Featured image uploaded.");}catch(error){setMessage(error instanceof Error?error.message:"Upload failed");}finally{setBusy(false);}}
 async function submit(status:"draft"|"published"){if(!form.title.trim()){setMessage("Enter a headline first.");return;}if(status==="published"&&(!form.summary.trim()||!blocks.some(block=>block.type==="paragraph"&&block.text.trim()))){setMessage("A summary and at least one paragraph are required to publish.");return;}if(blocks.some(block=>(block.type==="image"&&!block.url)||(block.type==="gallery"&&!block.urls.length))){setMessage("Complete or remove empty picture blocks before saving.");return;}setBusy(true);setMessage("Saving update...");try{const details=writeArticleBlocks("",blocks);const response=await fetch("/api/admin/stories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,details,image_url:featured||null,status})});const result=await response.json();if(!response.ok)throw Error(result.error||"Unable to save update.");setMessage(status==="published"?"Published successfully.":"Draft saved successfully.");window.location.assign(`/admin/updates?created=${encodeURIComponent(result.story.id)}`);}catch(error){setMessage(error instanceof Error?error.message:"Unable to save update.");}finally{setBusy(false);}}
 return <main className="min-h-screen bg-gray-50 px-3 py-6 text-gray-950 sm:px-6"><div className="mx-auto w-full max-w-7xl space-y-5"><a href="/admin/updates" className="inline-flex rounded-xl border bg-white px-4 py-3 font-bold text-green-800">← Updates dashboard</a><header><h1 className="text-3xl font-black">Create New Update</h1><p className="mt-2 text-gray-600">Build your article in reading order. The featured image appears above the article. Select words and use the formatting toolbar for emphasis. The live preview below displays the final formatting before publishing.</p></header><section className="grid min-w-0 gap-4 rounded-2xl border bg-white p-4 sm:grid-cols-2 sm:p-6">{([['title','Headline'],['institution','Institution'],['category','Category'],['summary','Summary'],['deadline','Deadline text'],['official_source_name','Official source name'],['official_source_url','Official source link']] as const).map(([key,label])=><label key={key} className={`min-w-0 text-sm font-bold ${key==='title'||key==='summary'?'sm:col-span-2':''}`}>{label}{key==='summary'?<textarea rows={3} value={form[key]} onChange={event=>change(key,event.target.value)} className={field}/>:<input type={key==='official_source_url'?'url':'text'} value={form[key]} onChange={event=>change(key,event.target.value)} className={field}/>}</label>)}<div className="sm:col-span-2"><h2 className="font-black">Featured image (optional)</h2><p className="text-sm text-gray-600">This appears beneath the headline, separately from pictures inside the article.</p><MediaPicker imagesOnly onSelect={setFeatured}/><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file);event.target.value="";}} className="mt-3 block w-full text-sm"/>{featured&&<div className="mt-3"><img src={featured} alt="Featured preview" className="max-h-72 w-full object-contain"/><button type="button" onClick={()=>setFeatured("")} className="mt-2 rounded-lg border px-3 py-2 text-red-700">Remove featured image</button></div>}</div></section><ArticleBlockEditor value={blocks} onChange={setBlocks} disabled={busy}/><ArticleLivePreview blocks={blocks} title={form.title} summary={form.summary} featured={featured}/><DuplicateReview title={form.title} sourceUrl={form.official_source_url}/>{message&&<p role="status" className="rounded-xl border bg-white p-4 font-bold">{message}</p>}<div className="flex flex-wrap gap-3 pb-10"><button type="button" disabled={busy} onClick={()=>void submit("draft")} className="rounded-xl border border-green-700 bg-white px-6 py-4 font-black text-green-800 disabled:opacity-50">Save Draft</button><button type="button" disabled={busy} onClick={()=>void submit("published")} className="rounded-xl bg-green-700 px-6 py-4 font-black text-white disabled:opacity-50">Publish Now</button></div></div></main>;
}
