import type { Metadata } from "next";

export const metadata: Metadata = { title: "Disclaimer", description: "Read the S.O.H CONSULTS business, admission guidance, calculator, privacy and service disclaimer.", alternates: { canonical: "/disclaimer" } };

const sections = [
  { title: "General Information", paragraphs: ["S.O.H CONSULTS is a business name registered with the Corporate Affairs Commission (CAC) of Nigeria. We provide educational information, admission guidance, online registration assistance, documentation support, educational consultation and related business centre services.", "Information published on this website is provided for general information and guidance. We make reasonable efforts to ensure that our content is accurate, reliable and up to date. However, admission requirements, application deadlines, fees, examination procedures and institutional policies may change without prior notice.", "We do not guarantee that all information published on this website will always be complete, current or free from errors. Users are strongly encouraged to verify important information through the official websites and communication channels of the relevant institutions and examination bodies."] },
  { title: "Business Registration and No Official Affiliation", paragraphs: ["S.O.H CONSULTS is registered with the Corporate Affairs Commission under Business Name Registration Number BN8780171. Our business operates independently and is not a government agency, examination body or educational institution.", "Unless expressly stated and verified, S.O.H CONSULTS is not affiliated with, endorsed by or acting on behalf of the Joint Admissions and Matriculation Board (JAMB), West African Examinations Council (WAEC), National Examinations Council (NECO), National Business and Technical Examinations Board (NABTEB), Lagos State University (LASU) or any other institution or government agency.", "References to these organisations are provided for informational purposes and to assist applicants in understanding relevant educational processes. Our registration, documentation and consultancy services are independently provided based on client requests and officially available platforms.", "CAC registration should not be interpreted as an endorsement of our services by any educational institution or examination body."] },
  { title: "Admission and Examination Disclaimer", paragraphs: ["S.O.H CONSULTS provides admission guidance and registration assistance but does not guarantee admission, examination success, scholarship awards or any particular application outcome.", "Admission and examination decisions remain the exclusive responsibility of the relevant institutions and examination bodies. We do not influence admission decisions, provide preferential admission treatment or guarantee the approval of applications.", "Applicants should independently confirm admission requirements, application deadlines, screening procedures, fees and other important announcements through official channels before making decisions or payments."] },
  { title: "LASU Aggregate and Eligibility Calculator", paragraphs: ["The LASU Aggregate and Eligibility Calculator available on this website is an independent educational guidance tool. It provides estimated aggregate scores and eligibility assessments based on information entered by users and the admission requirements available to S.O.H CONSULTS.", "Although reasonable efforts are made to maintain accurate calculations, programme requirements and eligibility rules, results may be affected by changes in institutional policies, incomplete information or incorrect user entries.", "Calculator results do not constitute an official admission assessment, admission offer or guarantee of admission. Lagos State University retains final authority over its admission requirements, screening procedures, eligibility decisions and admission offers.", "Users should verify calculator results against the latest official LASU admission guidelines. S.O.H CONSULTS is not responsible for admission decisions made solely on the basis of calculator results, except to the extent that responsibility arises under applicable law."] },
  { title: "Third-Party Links", paragraphs: ["Our website may contain links to external websites, including educational institutions, examination bodies, government platforms and other information providers. These links are provided for additional information and user convenience.", "S.O.H CONSULTS does not control the content, security, availability or privacy practices of external websites. The inclusion of a third-party link does not constitute an endorsement of the organisation, website, product or service concerned.", "Users should verify the authenticity of external websites and review their applicable terms and privacy policies before submitting personal information or making payments."] },
  { title: "Advertisements", paragraphs: ["This website may display advertisements supplied by third-party advertising providers, including Google AdSense, subject to the necessary approvals. Advertisements appearing on this website do not constitute endorsements or recommendations by S.O.H CONSULTS.", "We encourage users to independently evaluate advertised products and services before making purchases, submitting personal information or entering into transactions. Third-party advertisers are responsible for their own advertising content, products and services, subject to applicable law."] },
  { title: "Limitation of Responsibility", paragraphs: ["Users are responsible for verifying information and ensuring that details submitted during registration and application processes are accurate. Clients must ensure that all personal information, academic records and documents supplied to S.O.H CONSULTS are accurate, complete and authentic.", "We are not responsible for errors, delays, rejections or other consequences arising from incorrect, incomplete, fraudulent or misleading information supplied by clients, except where responsibility arises from our own actions or omissions under applicable law.", "S.O.H CONSULTS is not responsible for decisions made by educational institutions, examination bodies, payment processors or other independent third parties. Users acknowledge that reliance on general information published on this website involves some degree of risk.", "To the extent permitted by applicable law, S.O.H CONSULTS shall not be liable for losses arising from circumstances beyond its reasonable control. Nothing in this disclaimer excludes or limits liability that cannot lawfully be excluded or restricts any rights or remedies available to consumers under applicable law."] },
  { title: "Contact Us", paragraphs: ["For enquiries, clarification, complaints or assistance, please contact S.O.H CONSULTS."] },
  { title: "Privacy and Personal Data Protection", paragraphs: ["S.O.H CONSULTS is committed to protecting the privacy and personal data of its clients and website users. Personal information provided through this website or during service engagement is collected and processed for legitimate purposes, including educational consultation, admission registration assistance, documentation support, payment facilitation where applicable, customer support and compliance with legal obligations.", "Depending on the requested service, we may collect names, contact information, identification details, academic records and other relevant documents reasonably necessary to provide assistance. We handle personal information with due care and seek to comply with applicable Nigerian data protection laws, including the Nigeria Data Protection Act 2023.", "We do not sell or trade clients' personal data. Where necessary and supported by an appropriate lawful basis, relevant information may be shared with educational institutions, examination bodies, government platforms, payment processors or other service providers to fulfil a client's request or comply with legal requirements.", "We implement reasonable administrative, technical and organisational safeguards to protect personal data against unauthorised access, loss, misuse or disclosure. However, no electronic transmission or storage system is completely secure, and absolute security cannot be guaranteed.", "For further information about how personal information is collected, used, stored and protected, users should consult our Privacy Policy."] },
  { title: "Service Engagement and Client Responsibilities", paragraphs: ["S.O.H CONSULTS provides registration assistance, documentation support, educational consultation and related services based on client requests. Clients are responsible for reviewing and confirming their personal details, academic records, programme choices and other application information before final submission.", "Where clients authorise S.O.H CONSULTS to complete registrations or submit information on their behalf, they remain responsible for providing accurate and authentic information and documents. Clients are encouraged to retain copies of payment receipts, application confirmations and other relevant documentation.", "Applicable service charges should be communicated before payment. Payments made directly to institutions, examination bodies or third-party platforms remain subject to the applicable provider's terms and conditions."] },
  { title: "Website Security and Availability", paragraphs: ["S.O.H CONSULTS makes reasonable efforts to maintain a secure, functional and accessible website. However, uninterrupted website availability cannot be guaranteed.", "Temporary disruptions may occur due to maintenance, internet connectivity, hosting infrastructure, third-party integrations or other technical circumstances. Users should avoid sharing passwords, one-time passwords, banking PINs or other sensitive authentication credentials through unofficial communication channels.", "We encourage users to report suspicious activity or security concerns through our official contact channels."] },
  { title: "Updates to This Disclaimer", paragraphs: ["S.O.H CONSULTS reserves the right to review and update this disclaimer to reflect changes in its services, website functionality, legal requirements or operational procedures. Any revised version will be published on this page with an updated revision date.", "Users are encouraged to review this disclaimer periodically. Changes will not retrospectively remove rights or obligations where doing so would be inconsistent with applicable law."] },
  { title: "Acknowledgement", paragraphs: ["By using this website or engaging our services, you acknowledge that you have had the opportunity to read and understand this disclaimer. Your use of this website remains subject to applicable laws and any service terms separately communicated to you.", "This disclaimer does not replace our Privacy Policy or any specific service agreement. Nothing in this disclaimer should be interpreted as removing statutory rights or protections available to users under Nigerian law."] },
];

export default function DisclaimerPage() {
  return <main className="mx-auto w-full max-w-4xl flex-1 px-5 py-12 text-slate-800 sm:px-8">
    <a href="/" className="text-sm font-semibold text-green-800 underline underline-offset-4">← Back to homepage</a>
    <header className="mt-7 rounded-2xl bg-green-900 p-7 text-white sm:p-10"><h1 className="text-3xl font-bold">Disclaimer</h1><p className="mt-2 font-semibold">S.O.H CONSULTS | Your Guide. Your Success.</p><p className="mt-3 text-sm">CAC Registration Number: BN8780171</p><p className="mt-1 text-sm">Last Updated: 19 September 2026</p></header>
    <div className="mt-9 space-y-9">{sections.map((section, index) => <section key={section.title} aria-labelledby={`disclaimer-${index + 1}`}><h2 id={`disclaimer-${index + 1}`} className="mb-3 text-xl font-bold text-green-900">{index + 1}. {section.title}</h2><div className="space-y-3 leading-7">{section.paragraphs.map((paragraph, paragraphIndex) => <p key={paragraphIndex}>{paragraph}</p>)}{index === 7 && <address className="not-italic leading-8"><p><strong>S.O.H CONSULTS</strong></p><p>CAC Registration Number: BN8780171</p><p>WhatsApp: <a className="text-green-800 underline" href="https://wa.me/2348182141088">0818 214 1088</a></p><p>Email: <a className="text-green-800 underline" href="mailto:oluyepeadetayo@gmail.com">oluyepeadetayo@gmail.com</a></p><p>Website: <a className="text-green-800 underline" href="https://sohconsults.com.ng">https://sohconsults.com.ng</a></p><p>Your Guide. Your Success.</p></address>}{index === 8 && <p><a className="font-semibold text-green-800 underline" href="/privacy-policy">Read our Privacy Policy</a>.</p>}</div></section>)}</div>
    <footer className="mt-12 border-t border-green-200 pt-6 text-center"><p className="font-bold text-green-900">S.O.H CONSULTS</p><p className="text-sm">CAC Registered Business | BN8780171</p><p className="italic">Your Guide. Your Success.</p></footer>
  </main>;
}
