"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import LasuStyleOLevel,{type OLevelResultEntry} from "../components/LasuStyleOLevel";
import {yabatechMeritCutoffs,yabatechCatchmentCutoffs,yabatechProgrammes} from "../../data/yabatech";
const gp:Record<string,number>={A1:3,B2:2.5,B3:2,C4:1.5,C5:1,C6:.5,D7:0,E8:0,F9:0};
const subjects=["English Language","Mathematics","Biology","Chemistry","Physics","Agricultural Science","Economics","Government","Commerce","Geography","Further Mathematics","Financial Accounting","Civic Education","Literature in English","Fine Art","Technical Drawing","Food and Nutrition"];
const states=["Abia","Adamawa","Akwa Ibom","Anambra","Bauchi","Bayelsa","Benue","Borno","Cross River","Delta","Ebonyi","Edo","Ekiti","Enugu","Gombe","Imo","Jigawa","Kaduna","Kano","Katsina","Kebbi","Kogi","Kwara","Lagos","Nasarawa","Niger","Ogun","Ondo","Osun","Oyo","Plateau","Rivers","Sokoto","Taraba","Yobe","Zamfara","FCT"];
export default function YabatechCalculator(){
 const [name,setName]=useState(""),[programme,setProgramme]=useState(""),[origin,setOrigin]=useState(""),[jamb,setJamb]=useState(""),[post,setPost]=useState("");
 const [sittings,setSittings]=useState<1|2>(1),[results,setResults]=useState<OLevelResultEntry[]>([]);
 const j=Math.max(0,Math.min(400,Number(jamb)||0)), postScore=Math.max(0,Math.min(30,Number(post)||0)), jambPoints=j/8, sittingBonus=sittings===1?5:2.5;
 const bestFive=useMemo(()=>{const m=new Map<string,OLevelResultEntry>();results.filter(r=>r.subject&&r.grade).forEach(r=>{const old=m.get(r.subject);if(!old||(gp[r.grade]||0)>(gp[old.grade]||0))m.set(r.subject,r)});return [...m.values()].sort((a,b)=>(gp[b.grade]||0)-(gp[a.grade]||0)).slice(0,5)},[results]);
 const olevelPoints=bestFive.reduce((n,r)=>n+(gp[r.grade]||0),0), total=jambPoints+olevelPoints+sittingBonus+postScore;
 const merit=programme?yabatechMeritCutoffs[programme as keyof typeof yabatechMeritCutoffs]:undefined;
 const cmap=programme?yabatechCatchmentCutoffs[programme as keyof typeof yabatechCatchmentCutoffs] as Record<string,number>|undefined:undefined;
 const catchment=cmap?.[origin], complete=!!programme&&!!origin&&bestFive.length===5&&j>0, eligible=complete&&merit!==undefined&&(total>=merit||(catchment!==undefined&&total>=catchment));
 return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">
 <header className="overflow-hidden rounded-3xl bg-gradient-to-br from-green-700 via-green-600 to-emerald-500 p-6 text-white shadow-xl sm:p-8"><nav className="flex flex-wrap gap-2 text-sm font-bold"><Link className="rounded-full bg-white px-4 py-2 text-green-800" href="/">Home</Link><Link className="rounded-full bg-white/15 px-4 py-2" href="/screening-calculator">Screening Calculators</Link><Link className="rounded-full bg-white/15 px-4 py-2" href="/updates">Latest Updates</Link></nav><p className="mt-7 text-sm font-black uppercase tracking-widest text-green-100">S.O.H CONSULTS</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">YABATECH Aggregate & Eligibility Checker</h1><p className="mt-3 max-w-3xl text-green-50">Yaba College of Technology ND Full-Time screening calculator with 2026/2027 merit and applicable catchment scores.</p></header>
 <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 className="text-xl font-black">Candidate Information</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Candidate Name<input className="mt-2 w-full rounded-xl border border-slate-300 p-3 font-normal" value={name} onChange={e=>setName(e.target.value)} placeholder="Enter full name"/></label><label className="text-sm font-bold">Programme<select className="mt-2 w-full rounded-xl border border-slate-300 p-3 font-normal" value={programme} onChange={e=>setProgramme(e.target.value)}><option value="">Select programme</option>{yabatechProgrammes.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-bold sm:col-span-2">State of Origin<select className="mt-2 w-full rounded-xl border border-slate-300 p-3 font-normal" value={origin} onChange={e=>setOrigin(e.target.value)}><option value="">Select state of origin</option>{states.map(x=><option key={x}>{x}</option>)}</select></label></div>
 {programme&&merit!==undefined&&<div className="mt-4 rounded-xl bg-green-50 p-4 text-sm"><b>2026/2027 Merit:</b> {merit}{catchment!==undefined&&<span> · <b>{origin} Catchment:</b> {catchment}</span>}</div>}
 <div className="mt-7 border-t pt-6"><h2 className="text-xl font-black">UTME Score</h2><input type="number" min="0" max="400" className="mt-3 w-full rounded-xl border border-slate-300 p-3" value={jamb} onChange={e=>setJamb(e.target.value)} placeholder="e.g. 240"/><p className="mt-2 text-sm text-slate-500">JAMB ÷ 8 = <b>{jambPoints.toFixed(2)}/50</b></p></div>
 <div className="mt-7 border-t pt-6"><h2 className="text-xl font-black">O'Level Result</h2><p className="mt-1 text-sm text-slate-600">Enter the actual result. Duplicate subjects are blocked within one sitting; across two sittings the better grade is used once.</p><LasuStyleOLevel subjects={subjects} grades={Object.keys(gp)} value={results} onChange={setResults} sittings={sittings} onSittingsChange={setSittings} note="One sitting adds 5 points. Two sittings add 2.5 points."/><p className="mt-3 text-sm text-slate-500">A1=3, B2=2.5, B3=2, C4=1.5, C5=1, C6=0.5. Selected five: <b>{olevelPoints.toFixed(1)}/15</b>.</p></div>
 <div className="mt-7 border-t pt-6"><h2 className="text-xl font-black">Post-UTME</h2><input type="number" min="0" max="30" className="mt-3 w-full rounded-xl border border-slate-300 p-3" value={post} onChange={e=>setPost(e.target.value)} placeholder="Enter score out of 30"/><p className="mt-2 text-sm text-slate-500">Post-UTME contributes up to 30 points.</p></div>
 <div className="mt-7 border-t pt-6"><h2 className="text-lg font-black">Live Aggregate</h2><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs font-bold text-slate-500">UTME</span><p className="font-black">{jambPoints.toFixed(2)}</p></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs font-bold text-slate-500">O'LEVEL</span><p className="font-black">{olevelPoints.toFixed(1)}</p></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs font-bold text-slate-500">SITTING</span><p className="font-black">{sittingBonus}</p></div><div className="rounded-xl bg-green-50 p-3"><span className="text-xs font-bold text-green-700">TOTAL</span><p className="font-black text-green-700">{total.toFixed(2)}%</p></div></div>{complete&&<div className={"mt-4 rounded-2xl p-4 "+(eligible?"bg-green-100 text-green-800":"bg-red-100 text-red-800")}><p className="text-xl font-black">{eligible?"ELIGIBLE":"NOT ELIGIBLE"}</p><p className="mt-1 text-sm font-bold">{eligible&&catchment!==undefined&&total<Number(merit)?"You meet the "+origin+" catchment score of "+catchment+".":"Merit score for this programme: "+merit+"."}</p></div>}</div></section>
 <aside className="space-y-5"><section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><p className="text-xs font-black uppercase tracking-wider text-green-700">How the checker works</p><h2 className="mt-2 text-xl font-black">YABATECH calculation</h2><div className="mt-4 space-y-3 text-sm text-slate-600"><p><b>1. UTME:</b> JAMB ÷ 8, maximum 50.</p><p><b>2. O'Level:</b> five grades, maximum 15.</p><p><b>3. Sitting bonus:</b> 5 for one sitting, 2.5 for two.</p><p><b>4. Post-UTME:</b> maximum 30.</p></div></section><section className="rounded-3xl bg-green-700 p-5 text-white"><p className="text-xs font-black uppercase tracking-wider text-green-100">S.O.H CONSULTS</p><h2 className="mt-2 text-xl font-black">Need admission guidance?</h2><a className="mt-4 inline-block rounded-xl bg-white px-4 py-3 text-sm font-black text-green-800" href="https://wa.me/2348182141088">Chat on WhatsApp</a></section></aside></div>
 <section className="mt-8 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><p className="text-xs font-black uppercase tracking-wider text-green-700">YABATECH Admission Guide</p><h2 className="mt-2 text-2xl font-black">How to calculate your YABATECH aggregate</h2><p className="mt-3 text-sm text-slate-600">Aggregate = (JAMB ÷ 8) + O'Level points + sitting bonus + Post-UTME score. The eligibility comparison uses the supplied 2026/2027 merit and catchment score sheet.</p><p className="mt-3 text-xs text-slate-500">Course-specific O'Level and UTME subject validation will only be enforced from verified YABATECH entry-requirement data.</p></section>
 </div></main>}